import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

const BJ = "/uploads/itinerary/beijing";

export function buildBeijingConfig(): ItineraryConfig {
  return {
    cityName: "Beijing",
    title: "Beijing Discovery",
    location: "Beijing, China",
    duration: "3 Days",
    heroImage: `${BJ}/forbidden1.jpg`,
    meiGreeting: "This is what a Beijing trip could look like. We handle tickets, restaurants, transport, and on-the-ground help — so you can just enjoy the trip.",
    departure: {
      time: "Morning",
      title: "Airport / Train Transfer",
      description: "We arrange a driver to take you to Beijing Capital Airport, Daxing Airport, or Beijing Railway Station. Beijing is also the starting point for bullet trains to Xi'an (4.5hrs), Shanghai (4.5hrs), and Chengdu (8hrs).",
    },
    departureNote: "This is just a sample — we'd tailor everything around your dates and what you want to do. Message us to get started.",
    days: [
      {
        label: "Day 1",
        subtitle: "Forbidden City · Jingshan Park · Hutongs · Shichahai",
        color: "#D0021B",
        items: [
          {
            id: "bj-d1-forbidden",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "The Forbidden City",
            subtitle: "Morning — 500 years of imperial history",
            description: "The world's largest palace complex — 980 buildings across 72 hectares where 24 emperors ruled China for 500 years. Enter through the Meridian Gate and walk the central axis through the Hall of Supreme Harmony, the Hall of Middle Harmony, and the Inner Court. The Treasure Gallery and Clock Museum are worth the extra ¥10 each.",
            image: `${BJ}/forbidden1.jpg`,
            tip: "Our tip: Tickets sell out days in advance and can only be booked through Chinese platforms using a Chinese ID. We book yours. Enter at 8:00 AM sharp — by 10 AM the central halls are packed.",
            previewImages: [`${BJ}/forbidden1.jpg`, `${BJ}/forbidden2.jpg`, `${BJ}/forbidden3.jpg`],
            previewLine: "980 buildings, 500 years of emperors — the world's largest palace complex.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk out the north gate to Jingshan Park" },
          },
          {
            id: "bj-d1-jingshan",
            time: "Midday · 11:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Jingshan Park",
            subtitle: "The best view of the Forbidden City",
            description: "A man-made hill directly behind the Forbidden City — climb for 10 minutes and get the single best panoramic view of all 980 golden roofs spread out below you. The entire Forbidden City unfolds in one shot. Only ¥2 entry. This is where the last Ming emperor hanged himself when rebels took the city in 1644.",
            image: `${BJ}/jingshan1.jpg`,
            tip: "Our tip: Go straight here after the Forbidden City while you're already at the north gate. The view is best before noon when the sun lights up the golden roofs.",
            previewImages: [`${BJ}/jingshan1.jpg`, `${BJ}/jingshan2.jpg`, `${BJ}/jingshan3.jpg`],
            previewLine: "10-minute climb for the iconic view of 980 golden roofs — ¥2 entry.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk south-west to lunch" },
          },
          {
            id: "bj-d1-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near the Forbidden City",
            description: "Beijing's food is iconic — Peking duck, hand-pulled noodles, and dumplings are the essentials:",
            restaurants: [
              { name: "四季民福", englishName: "Siji Minfu", cuisine: "Peking Duck", note: "The most popular Peking duck restaurant in Beijing — long queues but worth it. The duck is carved tableside and the pancakes are perfect.", price: "¥120–180 pp", rating: 4.8 },
              { name: "海碗居", englishName: "Haiwanju", cuisine: "Beijing noodles", note: "Old-school Beijing noodle house — zhajiang noodles (thick wheat noodles with soybean paste) is the signature. Huge portions, very local.", price: "¥30–50 pp", rating: 4.6 },
              { name: "庆丰包子", englishName: "Qingfeng Baozi", cuisine: "Steamed buns", note: "Famous after the president ate here. Simple, cheap, and genuinely good steamed pork buns.", price: "¥15–30 pp", rating: 4.5 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to Nanluoguxiang hutong area" },
          },
          {
            id: "bj-d1-hutong",
            time: "Afternoon · 2:30",
            icon: Footprints,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Hutong Walk",
            subtitle: "Afternoon — 740-year-old alleyways",
            description: "Wander the narrow alleyways that have been the backbone of Beijing life since the Yuan Dynasty. Start at Nanluoguxiang for the cafes and shops, then cut into the quieter side hutongs where the real courtyard houses are — washing hanging between doorways, old men playing chess, cats everywhere. This is old Beijing.",
            image: `${BJ}/hutong1.jpg`,
            tip: "Our tip: Skip the rickshaw tours (overpriced, ¥200+). The best hutongs are the ones without tourists — we'll mark the exact route on a map for you so you find the real ones.",
            previewImages: [`${BJ}/hutong1.jpg`, `${BJ}/hutong2.jpg`, `${BJ}/hutong3.jpg`],
            previewLine: "740-year-old alleyways, courtyard houses, and the real old Beijing.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk north to Shichahai lake area" },
          },
          {
            id: "bj-d1-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Lakeside dining at Shichahai",
            description: "Eat by the lake before the evening walk:",
            restaurants: [
              { name: "烤肉季", englishName: "Kaorouji", cuisine: "Mongolian BBQ", note: "A 170-year-old charcoal-grilled lamb restaurant right on the lake. The rooftop terrace has the best sunset view in Beijing.", price: "¥100–150 pp", rating: 4.7 },
              { name: "姚记炒肝", englishName: "Yaoji Chaogan", cuisine: "Old Beijing street food", note: "Famous for fried liver (an acquired taste) and baozi. It's a Beijing institution — go for the experience even if you stick to the buns.", price: "¥20–40 pp", rating: 4.5 },
            ],
            transportAfter: { mode: "walk", duration: "2 min", note: "Walk along the lake" },
          },
          {
            id: "bj-d1-shichahai",
            time: "Evening · 7:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Shichahai Evening Walk",
            subtitle: "Evening — Lakes, bars, and lanterns",
            description: "Three ancient lakes ringed by 700-year-old hutong alleys. Walk along the water as the lanterns come on — the Drum Tower and Bell Tower are lit up in the distance, rooftop bars line Houhai lake, and locals are out strolling, singing, and playing instruments. The most atmospheric evening in Beijing.",
            image: `${BJ}/shichahai1.jpg`,
            tip: "Our tip: Walk the quieter Qianhai and Xihai lakes first, then finish at Houhai where the bars are. Avoid the touts trying to get you into expensive bar seats.",
            previewImages: [`${BJ}/shichahai1.jpg`, `${BJ}/shichahai2.jpg`, `${BJ}/shichahai3.jpg`],
            previewLine: "Ancient lakes, rooftop bars, and Beijing's best evening atmosphere.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "bj-d1-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in to Hotel",
            subtitle: "Rest up — Great Wall tomorrow",
            description: "Get a good sleep. Tomorrow is an early start for the Great Wall — the most iconic thing you'll do in China.",
          },
        ],
      },
      {
        label: "Day 2",
        subtitle: "Mutianyu Great Wall · 798 Art District",
        color: "#1A1A1A",
        items: [
          {
            id: "bj-d2-wall",
            time: "Morning · 7:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Mutianyu Great Wall",
            subtitle: "Morning — The wall foreigners prefer",
            description: "5.4km of beautifully restored Ming Dynasty wall with 23 watchtowers winding through forested mountains. Take the cable car up, walk the wall for 2-3 hours, then ride the toboggan down (yes, a toboggan on the Great Wall). Mutianyu is consistently rated by foreigners above Badaling — fewer crowds, better scenery, and a more genuine experience.",
            image: `${BJ}/mutianyu1.jpg`,
            tip: "Our tip: Leave Beijing by 7 AM — it's 1.5 hours to Mutianyu. We arrange a private car so you go direct, not via tourist bus stops. The cable car + toboggan combo needs a Chinese app to book — we sort it.",
            previewImages: [`${BJ}/mutianyu1.jpg`, `${BJ}/mutianyu2.jpg`, `${BJ}/mutianyu3.jpg`],
            previewLine: "5.4km of wall, 23 watchtowers, cable car up, toboggan down.",
            transportAfter: { mode: "car", duration: "90 min", note: "Private car back to Beijing" },
          },
          {
            id: "bj-d2-lunch",
            time: "Afternoon · 2:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Late Lunch",
            subtitle: "Back in the city",
            description: "You'll be hungry after the wall — proper Beijing food to refuel:",
            restaurants: [
              { name: "大董烤鸭", englishName: "DaDong", cuisine: "Modern Peking Duck", note: "The upscale Peking duck experience — thinner, crispier, less fat. Beautiful plating. A good contrast if you had Siji Minfu on Day 1.", price: "¥200–300 pp", rating: 4.8 },
              { name: "东来顺", englishName: "Donglaishun", cuisine: "Hot pot", note: "Beijing's most famous hot pot — 100+ year history. Thinly sliced lamb in copper pot. Perfect after a cold morning on the wall.", price: "¥100–150 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to 798 Art District" },
          },
          {
            id: "bj-d2-798",
            time: "Afternoon · 4:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "798 Art District",
            subtitle: "Afternoon — Contemporary art in a weapons factory",
            description: "A Cold War-era weapons factory converted into China's most influential contemporary art district. Bauhaus industrial architecture — soaring ceilings, exposed pipes, red brick — filled with galleries, street art, and independent cafes. UCCA Center for Contemporary Art is the anchor gallery. The contrast with the morning's ancient wall is part of the appeal.",
            image: `${BJ}/art798_1.jpg`,
            tip: "Our tip: Most galleries are free. UCCA is ¥40-80 depending on the exhibition. The district is best from 3-6 PM — good light for the street art and less crowded than weekends.",
            previewImages: [`${BJ}/art798_1.jpg`, `${BJ}/art798_2.jpg`, `${BJ}/art798_3.jpg`],
            previewLine: "Bauhaus factories turned galleries — China's contemporary art epicentre.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to dinner" },
          },
          {
            id: "bj-d2-dinner",
            time: "Evening · 7:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Near Sanlitun or Gulou",
            description: "Beijing's best dinner scene:",
            restaurants: [
              { name: "局气", englishName: "Juqi", cuisine: "Creative Beijing", note: "Fun, Instagram-friendly Beijing food — beautifully presented traditional dishes with a modern twist. The 'birdcage tofu' is famous.", price: "¥80–120 pp", rating: 4.7 },
              { name: "胡大", englishName: "Huda", cuisine: "Crawfish & late-night", note: "Beijing's most famous spicy crawfish restaurant. Loud, messy, and packed — pure Beijing nightlife energy. Opens late.", price: "¥100–150 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "bj-d2-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — temples and gardens tomorrow",
            description: "One more day — the Temple of Heaven and Summer Palace are both beautiful and less intense than today.",
          },
        ],
      },
      {
        label: "Day 3",
        subtitle: "Temple of Heaven · Lama Temple · Summer Palace",
        color: "#B45309",
        items: [
          {
            id: "bj-d3-temple",
            time: "Morning · 7:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Temple of Heaven",
            subtitle: "Morning — Imperial worship & morning exercises",
            description: "The sacred complex where 22 emperors prayed for good harvests over 500 years. The Hall of Prayer for Good Harvests — with its iconic blue triple roof — is one of the most perfect buildings in China. But the real magic is the park around it: arrive early and you'll see hundreds of locals doing tai chi, dancing, singing opera, and playing badminton among 600-year-old cypress trees.",
            image: `${BJ}/temple_heaven1.jpg`,
            tip: "Our tip: Be here by 7:30 AM for the morning exercises — they're gone by 9 AM. The Echo Wall and Imperial Vault of Heaven are quieter than the main hall. ¥34 combo ticket needs Chinese platform booking.",
            previewImages: [`${BJ}/temple_heaven1.jpg`, `${BJ}/temple_heaven2.jpg`, `${BJ}/temple_heaven3.jpg`],
            previewLine: "Blue-roofed masterpiece, morning tai chi, and 600-year-old cypress trees.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Lama Temple" },
          },
          {
            id: "bj-d3-lama",
            time: "Morning · 10:30",
            icon: Navigation,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Lama Temple",
            subtitle: "Morning — Tibetan Buddhism in Beijing",
            description: "A Qing Dynasty prince's palace turned into Beijing's largest Tibetan Buddhist monastery. Five grand halls lead to the showstopper: a 26-metre Buddha carved from a single sandalwood tree (it's in the Guinness Book of Records). Incense fills the air and monks in saffron robes move between halls — this is still a living, active monastery.",
            image: `${BJ}/lama1.jpg`,
            tip: "Our tip: ¥25 entry, buy incense at the entrance (not from street sellers). The Wanfu Pavilion with the giant Buddha is at the back — don't miss it.",
            previewImages: [`${BJ}/lama1.jpg`, `${BJ}/lama2.jpg`, `${BJ}/lama3.jpg`],
            previewLine: "26-metre Buddha from a single tree trunk, saffron-robed monks, and incense.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to lunch" },
          },
          {
            id: "bj-d3-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near Yonghegong / Gulou area",
            description: "Your last Beijing lunch — make it count:",
            restaurants: [
              { name: "小吊梨汤", englishName: "Xiao Diao Li Tang", cuisine: "Old Beijing", note: "Beautiful traditional decor, famous for their pear soup. Classic Beijing dishes done right — reliable and atmospheric.", price: "¥80–120 pp", rating: 4.7 },
              { name: "方砖厂69号炸酱面", englishName: "No.69 Zhajiang Noodles", cuisine: "Noodles", note: "Tiny hutong noodle shop with the best zhajiang noodles in Beijing. Cash only, no English, huge portions. The real deal.", price: "¥20–35 pp", rating: 4.9 },
            ],
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi to Summer Palace" },
          },
          {
            id: "bj-d3-summer",
            time: "Afternoon · 2:30",
            icon: Sunset,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Summer Palace",
            subtitle: "Afternoon — Imperial gardens on the lake",
            description: "China's grandest imperial garden — 290 hectares, three-quarters of which is Kunming Lake. Built by Emperor Qianlong in 1750, then rebuilt by Empress Dowager Cixi using money meant for the navy. Walk the 728-metre Long Corridor (every panel is a different painting), climb Longevity Hill for the lake view, and take a boat across to the Seventeen-Arch Bridge.",
            image: `${BJ}/summer_palace1.jpg`,
            tip: "Our tip: Enter through the East Gate, walk the Long Corridor, climb the hill, then boat across the lake. Budget 2-3 hours. ¥60 combo ticket — needs advance booking on Chinese apps. We handle it.",
            previewImages: [`${BJ}/summer_palace1.jpg`, `${BJ}/summer_palace2.jpg`, `${BJ}/summer_palace3.jpg`],
            previewLine: "290 hectares of imperial gardens, a painted corridor, and a lake you can boat across.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi back to city for dinner" },
          },
          {
            id: "bj-d3-dinner",
            time: "Evening · 6:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Farewell Dinner",
            subtitle: "Your last night in Beijing",
            description: "End the trip properly:",
            restaurants: [
              { name: "便宜坊", englishName: "Bianyifang", cuisine: "Peking Duck (oldest)", note: "The oldest Peking duck restaurant in Beijing — since 1416. Uses a different roasting method (closed oven) from the more famous places. A fitting final meal.", price: "¥120–180 pp", rating: 4.6 },
              { name: "京A", englishName: "Jing-A Brewery", cuisine: "Craft beer & Western", note: "Beijing's best craft brewery. Good burgers, great beer, relaxed vibe. Good if you want something familiar after 3 days of Chinese food.", price: "¥100–150 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "bj-d3-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — onward tomorrow",
            description: "Get a good rest. Your transfer is arranged for the morning.",
          },
        ],
      },
    ],
    picks: [
      {
        id: "bj-pick-1",
        emoji: "🏯",
        type: "Imperial",
        title: "Beihai Park",
        desc: "China's oldest surviving imperial garden — a thousand-year-old lakeside park with the iconic White Dagoba, boating in summer, and ice skating in winter.",
        meiNote: "Right next to the Forbidden City — easy to add to Day 1. Only ¥20 entry.",
        image: `${BJ}/beihai.jpg`,
        tag: "Easy add-on",
        tagColor: "#059669",
      },
      {
        id: "bj-pick-2",
        emoji: "🎭",
        type: "Culture",
        title: "Peking Opera Show",
        desc: "A traditional Peking opera performance with English subtitles. Elaborate costumes, acrobatics, and 200 years of theatrical tradition.",
        meiNote: "We book the tickets and pick a show with English surtitles — most don't have them.",
        image: `${BJ}/opera.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "bj-pick-3",
        emoji: "🥟",
        type: "Food",
        title: "Dumpling-Making Class",
        desc: "A hands-on cooking class in a hutong courtyard — learn to make jiaozi, baozi, and spring rolls from a local family.",
        meiNote: "We arrange this with a family we know in the hutongs. About 2 hours, includes lunch.",
        image: `${BJ}/dumplings.jpg`,
        tag: "We can arrange",
        tagColor: "#D0021B",
      },
      {
        id: "bj-pick-4",
        emoji: "🌅",
        type: "Day Trip",
        title: "Gubei Water Town + Simatai Wall",
        desc: "A scenic water town at the foot of the only Great Wall section open at night. Watch the sunset from the wall, then walk the illuminated town.",
        meiNote: "About 2 hours from Beijing. We can swap this for Mutianyu if you prefer a more dramatic, less-restored wall.",
        image: `${BJ}/gubei.jpg`,
        tag: "Day trip",
        tagColor: "#B45309",
      },
    ],
  };
}
