// Shared types for Pipeline B (request flow).
// Keep in sync with /scripts/lib/taxonomy.ts (the closed vocabularies).

import type {
  KidBand,
  Mobility,
  IndoorOutdoor,
  Resilience,
  Energy,
  TimeOfDay,
  NarrativeRole,
  InterestTag,
} from "../../../scripts/lib/taxonomy";

export type Category = "attraction" | "experience" | "restaurant";
export type PriceTier = "free" | "budget" | "mid" | "premium" | "luxury";
export type GroupType =
  | "solo"
  | "couple"
  | "family"
  | "friends"
  | "multigen"
  | "business";
export type DietRestriction =
  | "halal"
  | "vegetarian"
  | "vegan"
  | "pork-free"
  | "none";
export type Pace = "fast" | "balanced" | "relaxed";
export type Purpose =
  | "first-time"
  | "honeymoon"
  | "family-vacation"
  | "friends-trip"
  | "returning"
  | "food-nightlife"
  | "culture-history"
  | "business-leisure";

/** The structured form output the UI sends to /api/planner/candidates. */
export interface PlannerParams {
  cities: string[];           // ['shanghai']
  date_start: string;         // 'YYYY-MM-DD'
  date_end: string;
  date_flex_days: number;     // 0 if fixed
  group: GroupType;
  kid_ages?: KidBand[];       // only when group is 'family' or 'multigen'
  has_mobility_issues?: boolean;
  purposes: Purpose[];        // can be 1-2
  budget_tier: PriceTier;     // user's chosen ceiling — anything ≤ this passes
  interests: InterestTag[];   // user picked 2-5
  diet: DietRestriction[];    // ['none'] if no restriction
  pace?: Pace;                // optional, inferred if absent
  freeform?: string;          // optional last "anything else"
}

/** A place from the catalog after hard filter + score. */
export interface Candidate {
  id: string;
  slug: string;
  city: string;
  category: Category;
  name_cn: string;
  name_en: string | null;
  neighborhood_cn: string | null;
  neighborhood_en: string | null;
  price_cny: number | null;
  price_tier: PriceTier | null;
  cuisine_type: string | null;
  cuisine_subtype: string | null;
  time_needed_min: number | null;
  /** AI-enriched fields */
  kid_suitability: KidBand[] | null;
  mobility: Mobility | null;
  indoor_outdoor: IndoorOutdoor | null;
  weather_resilience: Resilience | null;
  energy_intensity: Energy | null;
  foreigner_friction_score: number | null;
  best_time_of_day: TimeOfDay[] | null;
  dietary_flags: Record<string, unknown> | null;
  narrative_role: NarrativeRole | null;
  interest_tags: InterestTag[] | null;
  ai_summary: string | null;
  /** Score from tag-overlap + purpose weighting, 0-100 */
  score: number;
  /** One-line breakdown for debugging */
  score_breakdown?: string;
}

/** Trip skeleton — generated by Claude before detailed days. */
export interface Skeleton {
  cities: SkeletonCity[];
  total_nights: number;
  rationale: string; // 2-3 sentence "why this shape"
}

export interface SkeletonCity {
  city: string;
  nights: number;
  days: SkeletonDay[];
}

export interface SkeletonDay {
  day_index: number;          // 1-based across the trip
  date: string;               // ISO
  theme: string;              // 'Arrival + Bund evening', 'Yu Garden + Pudong'
  pace_estimate: Pace;
  notes?: string;
}

/** Detailed daily itinerary — from /api/planner/itinerary stream. */
export interface DayItem {
  slot: TimeOfDay;
  start_time: string;     // 'HH:MM'
  duration_min: number;
  place_id: string;
  place_name: string;
  category: Category;
  why: string;            // one-line explanation for the user
  cost_cny: number | null;
  /** Hero image URL injected by the route before streaming back. */
  image_url?: string;
  transit_to_next?: {
    minutes: number;
    mode: "transit" | "taxi" | "walk";
    note?: string;
  };
}

export interface Day {
  day_index: number;
  date: string;
  city: string;
  theme: string;
  items: DayItem[];
  total_walking_km?: number;
  total_cost_cny?: number;
}

export interface Itinerary {
  trip_id: string;
  params: PlannerParams;
  days: Day[];
  generated_at: string;
}

/** /api/planner/refine input. */
export type RefineRequest =
  | {
      mode: "swap";
      itinerary: Itinerary;
      day_index: number;
      slot: TimeOfDay;
      reason?: string; // optional user note
    }
  | {
      mode: "chat";
      itinerary: Itinerary;
      message: string;
    };

export interface SwapResult {
  alternatives: Candidate[];
}

export interface ChatRefineResult {
  itinerary: Itinerary;
  changed_days: number[];
  summary: string; // "Day 2 slowed down — removed Pearl Tower, added 90 min at Tianzifang"
}
