import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

const HZ = "/uploads/itinerary/hangzhou";

export function buildHangzhouConfig(): ItineraryConfig {
  return {
    cityName: "Hangzhou",
    title: "Hangzhou Discovery",
    location: "Zhejiang, China",
    duration: "2 Days",
    heroImage: `${HZ}/westlake2.jpg`,
    meiGreeting: "This is what a Hangzhou trip could look like. We handle tickets, restaurants, transport, and on-the-ground help — so you can just enjoy the trip.",
    departure: {
      time: "Morning",
      title: "Train / Airport Transfer",
      description: "We arrange a driver to take you to Hangzhou East Railway Station or Xiaoshan Airport. Hangzhou is also just 1 hour from Shanghai by bullet train — easy to continue your trip.",
    },
    departureNote: "This is just a sample — we'd tailor everything around your dates and what you want to do. Message us to get started.",
    days: [
      {
        label: "Day 1",
        subtitle: "West Lake · Leifeng Pagoda · Hefang Street",
        color: "#D0021B",
        items: [
          {
            id: "hz-d1-westlake",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "West Lake",
            subtitle: "Morning — Su Causeway & boat ride",
            description: "Walk the Su Causeway while the morning mist is still on the water — it's the most peaceful time before the crowds arrive. Then take a hand-rowed boat to Three Pools Mirroring the Moon island. This is a UNESCO World Heritage lake that poets and emperors have been writing about for a thousand years, and it genuinely lives up to the hype.",
            image: `${HZ}/westlake1.jpg`,
            tip: "Our tip: The hand-rowed boats (¥150/hr) are much better than the big electric ones — the rower takes you to quieter spots. We pre-book these as they fill up fast in the morning.",
            previewImages: [`${HZ}/westlake1.jpg`, `${HZ}/westlake2.jpg`, `${HZ}/westlake3.jpg`],
            previewLine: "UNESCO World Heritage lake — Su Causeway walk and hand-rowed boat ride.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk along the south shore to Leifeng Pagoda" },
          },
          {
            id: "hz-d1-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Lakeside restaurants",
            description: "Hangzhou has some of the best food in China. Try the famous Dongpo Pork and West Lake Vinegar Fish — both local specialties you won't find done properly anywhere else.",
            restaurants: [
              { name: "楼外楼", englishName: "Louwailou", cuisine: "Classic Hangzhou", note: "The most famous restaurant in Hangzhou — 170+ years old, right on the lake. West Lake Vinegar Fish is the signature. Touristy but the food is legit.", price: "¥100–150 pp", rating: 4.6 },
              { name: "知味观", englishName: "Zhiweiguan", cuisine: "Hangzhou dim sum", note: "A century-old chain known for their xiaolongbao and shrimp-filled wontons. Great for a lighter, quicker lunch.", price: "¥50–80 pp", rating: 4.7 },
              { name: "绿茶餐厅", englishName: "Green Tea Restaurant", cuisine: "Modern Hangzhou", note: "Trendy, affordable, and always packed with locals. Creative Hangzhou dishes in a beautiful setting. Worth the queue.", price: "¥60–90 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Leifeng Pagoda entrance" },
          },
          {
            id: "hz-d1-leifeng",
            time: "Afternoon · 2:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Leifeng Pagoda",
            subtitle: "Afternoon — Sunset views over West Lake",
            description: "A rebuilt pagoda from 975 AD on West Lake's south shore — central to the Legend of the White Snake, one of China's most famous love stories. Take the escalator up, then the elevator to the top floor for the best panoramic view of the entire lake. The original ruins are preserved under glass on the ground floor.",
            image: `${HZ}/leifeng1.jpg`,
            tip: "Our tip: Go in the late afternoon — the 'Leifeng Sunset Glow' is one of the Ten Scenes of West Lake. ¥40 ticket, needs to be booked on Chinese platforms. We handle it.",
            previewImages: [`${HZ}/leifeng1.jpg`, `${HZ}/leifeng2.jpg`, `${HZ}/leifeng3.jpg`],
            previewLine: "A thousand-year-old pagoda with the best panoramic view of West Lake.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to Hefang Street" },
          },
          {
            id: "hz-d1-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Near Hefang Street",
            description: "Eat before you explore — plenty of options right near the old street:",
            restaurants: [
              { name: "奎元馆", englishName: "Kuiyuan Noodles", cuisine: "Hangzhou noodles", note: "A 150-year-old noodle house famous for shrimp and eel noodles. An institution — locals swear by it.", price: "¥30–50 pp", rating: 4.7 },
              { name: "皇饭儿", englishName: "Huangfaner", cuisine: "Hangzhou home cooking", note: "Casual, lively, and excellent. Great Dongpo Pork and stir-fried greens. Right near Hefang Street.", price: "¥70–100 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "walk", duration: "3 min", note: "Walk into Hefang Street" },
          },
          {
            id: "hz-d1-hefang",
            time: "Evening · 7:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Hefang Street",
            subtitle: "Evening — Old Hangzhou by lantern light",
            description: "An 1,800-metre historic pedestrian street from the Southern Song Dynasty. The red lanterns come on at dusk and it transforms — century-old pharmacies, hand-pulled dragon beard candy, fan makers, and street food everywhere. Visit the Hu Qingyu Tang pharmacy (1874) which still operates as a traditional Chinese medicine shop.",
            image: `${HZ}/hefang3.jpg`,
            tip: "Our tip: Evening is the best time — the lanterns are lit, the crowds are lively but not crushing, and street food stalls are all open. Try the stinky tofu and fried dumplings.",
            previewImages: [`${HZ}/hefang1.jpg`, `${HZ}/hefang2.jpg`, `${HZ}/hefang3.jpg`],
            previewLine: "Red lanterns, century-old shops, and the best street food in Hangzhou.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "hz-d1-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in to Hotel",
            subtitle: "Rest up — temples and tea tomorrow",
            description: "Head back to your hotel for the night. Day 2 starts with the most important Buddhist temple in southern China.",
          },
        ],
      },
      {
        label: "Day 2",
        subtitle: "Lingyin Temple · Longjing Tea · Grand Canal",
        color: "#1A1A1A",
        items: [
          {
            id: "hz-d2-lingyin",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Lingyin Temple",
            subtitle: "Morning — 1,700-year-old Buddhist temple",
            description: "One of China's most important Buddhist temples, founded in 328 AD by an Indian monk. The compound is huge — start with the 340 ancient cliff carvings on Feilai Peak (including a famous laughing Buddha), then enter the main temple to see China's largest wooden seated Buddha at 24.8 metres tall. The Five Hundred Arhat Hall has 500 unique bronze statues.",
            image: `${HZ}/lingyin1.jpg`,
            tip: "Our tip: Arrive at opening (7:30 AM) to hear the monks chanting — by 10 AM the tour groups take over. Entry is free since December 2025, but you need to reserve in advance through a Chinese app. We handle this.",
            previewImages: [`${HZ}/lingyin1.jpg`, `${HZ}/lingyin2.jpg`, `${HZ}/lingyin3.jpg`],
            previewLine: "340 cliff carvings, China's largest wooden Buddha, and morning monks' chanting.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Longjing Village" },
          },
          {
            id: "hz-d2-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Tea village restaurants",
            description: "Eat among the tea fields — the restaurants up here use fresh local ingredients and are much more relaxed than the city:",
            restaurants: [
              { name: "梅家坞茶农家", englishName: "Meijiawu Farmhouse", cuisine: "Tea village home cooking", note: "Simple farmhouse food in the tea village — stir-fried tea shoots, free-range chicken, and fresh vegetables. Eat on a terrace overlooking the plantations.", price: "¥60–90 pp", rating: 4.7 },
              { name: "龙井草堂", englishName: "Longjing Caotang", cuisine: "Refined Hangzhou", note: "A more polished option with a beautiful garden setting among the tea fields. Known for tea-infused dishes.", price: "¥120–180 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk into the tea fields" },
          },
          {
            id: "hz-d2-tea",
            time: "Afternoon · 2:00",
            icon: Navigation,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Longjing Tea Plantation",
            subtitle: "Afternoon — Tea picking and farmhouse tasting",
            description: "Walk through 1,200 years of tea history — the birthplace of China's most celebrated green tea. Rows of manicured tea bushes cover the hillsides, farmers pick leaves by hand, and you can sit in a family home while they fry the tea in a red-hot wok in front of you, then taste it. The Eighteen Imperial Tea Trees — personally tended for the emperor — are still here.",
            image: `${HZ}/longjing1.webp`,
            tip: "Our tip: The tea tastings are free but you're expected to buy some tea. Prices vary wildly — we can tell you what's fair so you don't overpay. Spring harvest (March–April) is when it's most special.",
            previewImages: [`${HZ}/longjing1.webp`, `${HZ}/longjing2.jpg`, `${HZ}/longjing3.jpg`],
            previewLine: "Walk the tea fields, watch hand-frying, and taste in a farmer's home.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi to Grand Canal / Gongchen Bridge area" },
          },
          {
            id: "hz-d2-dinner",
            time: "Evening · 5:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Canal-side dining",
            description: "Eat along the canal before the evening boat ride:",
            restaurants: [
              { name: "胜利河美食街", englishName: "Shengli River Food Street", cuisine: "Street food & local", note: "A whole street of restaurants along the canal — pick whatever looks good. Lively atmosphere, great for groups.", price: "¥50–80 pp", rating: 4.6 },
              { name: "新白鹿", englishName: "New Bailu", cuisine: "Modern Hangzhou", note: "Hugely popular local chain — always packed, fast service, excellent Hangzhou home-style dishes at great prices.", price: "¥50–70 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the canal pier" },
          },
          {
            id: "hz-d2-canal",
            time: "Evening · 7:30",
            icon: Sunset,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Grand Canal Night Cruise",
            subtitle: "Evening — Illuminated canal boat ride",
            description: "End your Hangzhou trip on the water — a night cruise along the Grand Canal, the world's oldest and longest man-made canal (2,500 years, Beijing to Hangzhou). The historic bridges and canal-side buildings light up after dark, and you'll pass under the 400-year-old Gongchen Bridge. A UNESCO World Heritage waterway.",
            image: `${HZ}/canal3.jpg`,
            tip: "Our tip: The tourist boats are ¥100–150 but the public water bus is only ¥3–5 and runs the same route. We'll tell you exactly which pier and which direction to go.",
            previewImages: [`${HZ}/canal1.jpg`, `${HZ}/canal2.jpg`, `${HZ}/canal3.jpg`],
            previewLine: "A night cruise along a 2,500-year-old UNESCO World Heritage canal.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi back to hotel" },
          },
          {
            id: "hz-d2-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — onward tomorrow",
            description: "Get a good rest. Your transfer is arranged for the morning.",
          },
        ],
      },
    ],
    picks: [
      {
        id: "hz-pick-1",
        emoji: "🚣",
        type: "Nature",
        title: "Xixi Wetland Park",
        desc: "An 11 sq km maze of reed-lined waterways and ancient fishing villages just 6km from West Lake. Explored by boat — much wilder and quieter than the lake.",
        meiNote: "The electric boat combo ticket (¥140) is easiest. Morning is best for mist and birdlife.",
        image: `${HZ}/xixi1.jpg`,
        tag: "Half-day add-on",
        tagColor: "#059669",
      },
      {
        id: "hz-pick-2",
        emoji: "🍵",
        type: "Experience",
        title: "Tea Ceremony Workshop",
        desc: "A proper tea ceremony class in a traditional teahouse — learn gongfu cha technique, taste multiple teas, and understand the culture behind it.",
        meiNote: "We can arrange a private session with an English-speaking tea master. About 2 hours.",
        image: `${HZ}/longjing2.jpg`,
        tag: "We can arrange",
        tagColor: "#D0021B",
      },
      {
        id: "hz-pick-3",
        emoji: "🌙",
        type: "Nightlife",
        title: "Impression West Lake Show",
        desc: "An outdoor night show directed by Zhang Yimou (Beijing Olympics ceremony director) performed on the lake itself. Water, light, and hundreds of performers.",
        meiNote: "Seasonal — runs March to November. Tickets need to be booked on Chinese platforms. We handle it.",
        image: `${HZ}/westlake3.jpg`,
        tag: "Seasonal",
        tagColor: "#7C3AED",
      },
      {
        id: "hz-pick-4",
        emoji: "🏛️",
        type: "Culture",
        title: "China National Silk Museum",
        desc: "Free museum covering 5,000 years of Chinese silk history. Surprisingly excellent — live silkworm displays, ancient garments, and weaving demonstrations.",
        meiNote: "Free entry, just need ID. Right next to West Lake — easy to add to Day 1.",
        image: `${HZ}/hefang2.jpg`,
        tag: "Free",
        tagColor: "#059669",
      },
      {
        id: "hz-pick-5",
        emoji: "🚄",
        type: "Day Trip",
        title: "Shanghai Day Trip",
        desc: "Hangzhou to Shanghai is just 1 hour by bullet train. The Bund, French Concession, Yu Garden — we can plan a full day trip if you have time.",
        meiNote: "We book the train tickets (needs Chinese ID verification) and plan the route for you.",
        image: `${HZ}/canal1.jpg`,
        tag: "1hr by train",
        tagColor: "#B45309",
      },
    ],
  };
}
