import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints, TrainFront, Car, Bus, MapPin, Plane } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

/* ── Image path prefixes ── */
const CD = "/uploads/itinerary/chengdu";
const CQ = "/uploads/itinerary/chongqing";
const ZJJ = "https://d2xsxph8kpxj0f.cloudfront.net/310519663383502924/dCuiiEQEkteYUXqqZRtP5i";
const G = "/uploads/itinerary/giovanni";

/* ── ZJJ CDN image shortcuts ── */
const FOREST = `${ZJJ}/zjj-forest-park-Fk6sgYY4AzscGgsTAdGZLa.webp`;
const TIANZI = `${ZJJ}/zjj-tianzi-mountain-XX5qUieAEsabKUeYk3JHxK.webp`;
const GOLDEN = `${ZJJ}/zjj-golden-whip-8i6gvipo7fjNjnMVU35ZsX.webp`;
const BAILONG = `${ZJJ}/zjj-bailong-elevator-9wBE8Ew5MeTzffXtu96bUz.webp`;
const AVATAR = `${ZJJ}/zjj-avatar-pillars-JfnwwF7VRiJvmNKdnJuoV2.webp`;
const TIANZI_CLOUDS = `${ZJJ}/zjj-tianzi-clouds-9hojziDU5h4PbieGP8mtEX.webp`;
const STREAM_CLOSE = `${ZJJ}/zjj-stream-close-hBhQpt79q4p9cSqndUf8Ww.webp`;
const HUNAN_FOOD = `${ZJJ}/zjj-hunan-food-5uvTJyHoH4ttNhNFdYfrT2.webp`;
const SHOW_STAGE = `${ZJJ}/zjj-show-stage-5vsSH7YEVUrQP8TKivY3B2.webp`;

export function buildGiovanniConfig(): ItineraryConfig {
  return {
    cityName: "China",
    title: "China Adventure",
    location: "Chengdu · Chongqing · Zhangjiajie",
    duration: "12 Days · May 20–31",
    heroImage: AVATAR,
    meiGreeting: "Giovanni — here's your trip, day by day. Every ticket, train, restaurant, and transfer is laid out below. Review it, tell us what to adjust, and we'll start booking everything.",
    departure: {
      time: "May 31 · End of day",
      title: "Onward to Hanoi",
      description: "Day 12 covers the full travel out: high-speed train Zhangjiajie → Chengdu (via Chongqing, ~5 hrs), taxi to Chengdu Tianfu International, then your onward flight to Hanoi. We book the train and airport transfer linked to your passport and time it to your flight.",
    },
    departureNote: "Safe travels! Message us any time during the trip — we're on WhatsApp 24/7 while you're in China.",
    days: [
      /* ═══════════════════════════════════════════
         CHENGDU · May 20–22
         ═══════════════════════════════════════════ */
      {
        label: "Day 1",
        city: "Chengdu",
        subtitle: "May 20 (Wed) · Arrival · Panda Base · Leshan Giant Buddha",
        color: "#D0021B",
        items: [
          {
            id: "g-d1-arrival",
            time: "05:45",
            icon: Plane,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Arrive Chengdu Tianfu International",
            subtitle: "Air China CA · Brussels → Chengdu TFU · direct",
            description: "Air China direct flight from Brussels (BRU), departing 19 May 13:25, landing at Chengdu Tianfu International (TFU) at 05:45 on 20 May. TFU is the newer international hub, about 50 km south-east of the city centre. After landing, clear immigration and collect your checked bag — should be through the arrivals hall by around 06:30.",
            tip: "Our tip: Fill in your arrival card on the plane. Immigration queues can be 20–30 minutes early morning. Free airport WiFi works without a Chinese number — just use your passport to log in. Have our WhatsApp open so we can confirm your taxi pickup.",
            previewLine: "Direct · Air China · lands 05:45 at TFU",
            transportAfter: { mode: "taxi", duration: "1 hr 40 min", note: "Taxi: TFU → Hotel (bag drop) → Panda Base West Gate" },
          },
          {
            id: "g-d1-transfer",
            time: "06:45",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Taxi to Hotel, then Panda Base",
            subtitle: "TFU → Hotel (drop luggage) → Panda Base West Gate · ~1h 40min driving",
            description: "Rather than dragging your suitcase around all day, the taxi stops at your Chengdu hotel first so you can leave your bag with reception (they'll hold it until check-in tonight) before continuing straight to the Panda Base West Gate. Total driving time is about 1 hour 40 minutes — roughly 50 minutes airport to hotel, a quick bag drop, then another 30–40 minutes out to the Panda Base. Public transport is an option (~2h 20min) but adds hassle with luggage and we don't recommend it post-flight.",
            tip: "Our tip: We pre-arrange the driver so he's waiting with a ChinaPal sign at arrivals. Freshen up at the hotel during the bag drop — a splash of water helps before the pandas. Keep a day pack with your passport, phone, charger, and a layer.",
            previewLine: "~1h 40min taxi · quick bag drop at hotel en route",
            transportAfter: { mode: "taxi", duration: "1h 40min", note: "TFU → Hotel → Panda Base West Gate" },
          },
          {
            id: "g-d1-panda",
            time: "08:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Giant Panda Base",
            description: "The world's largest captive panda breeding facility — 244 giant pandas in naturalistic forest enclosures. You'll see adults lazily eating bamboo, red pandas climbing trees, and if you're lucky, the nursery with newborn cubs behind glass. The base is huge (200+ hectares) but the best enclosures are clustered together. Cost: ¥55 entry + ¥85 audio guide (we bundle both). Gates open at 7:30 AM.",
            image: `${CD}/panda1.jpg`,
            tip: "Our tip: Pandas are most active before 10 AM and crowds arrive by 9 — your post-flight timing still catches the best window. The audio guide (¥85) is worth it; tickets must be booked on Chinese apps days in advance. We handle both.",
            previewImages: [`${CD}/panda1.jpg`, `${CD}/panda2.jpg`, `${CD}/panda3.jpg`],
            previewLine: "244 giant pandas — adults, cubs, and red pandas in bamboo forest enclosures.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Panda Base → Chengdu East Station" },
          },
          {
            id: "g-d1-train-leshan",
            time: "12:13",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Leshan",
            subtitle: "Chengdu East → Leshan · 53 minutes",
            description: "High-speed train C6255 — Chengdu East to Leshan, departs 12:13 and arrives 13:06. Second class (二等座) is ¥51. The 160km journey takes 53 minutes through the Sichuan Basin. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Get off at Leshan Station (not Emei Station — that's for the mountain tomorrow). From Leshan Station it's a 15-minute taxi to the Giant Buddha boat pier.",
            previewLine: "53 min · ¥51 (2nd class) · C6255",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi: Leshan Station → Giant Buddha boat pier" },
          },
          {
            id: "g-d1-leshan",
            time: "13:30",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Leshan Giant Buddha",
            description: "A 71-metre Buddha carved into a cliff face where three rivers collide — the largest stone Buddha in the world, built over 90 years starting in 713 AD. From the top you look down at his head; from the river you see the full figure. The carving is so massive that 100 people can sit on each foot. The hidden drainage system (inside the hair curls and robes) has kept it standing for 1,300 years. Two ways to see it: Option 1 is the boat cruise (¥70, 40–60 minutes) — the easy choice, giving you the iconic full-body view plus the 'giant sleeping Buddha' formation and the Three Rivers confluence. Option 2 is the cliff path hike / 九曲栈道 (¥80, ~3 hours) — enter at the North Gate, walk past the Buddha's head, down the nine-bend cliff stairs to his feet, and out the East Gate. The hike gives amazing close-up views but requires good stamina and queues of up to 2 hours.",
            image: `${G}/leshan-buddha.webp`,
            tip: "Our tip: After the early Panda Base morning we recommend the boat (Option 1) — you'll be fresh rather than exhausted, and the tour-bus crowds have cleared by the time you arrive. If you're up for the climb, Option 2 is spectacular but plan for a 3-hour physical effort.",
            previewImages: [`${G}/leshan-buddha.webp`, `${G}/leshan-cliff-path.jpg`, `${G}/leshan-three-rivers.webp`],
            previewLine: "71 metres tall, 1,300 years old — the world's largest stone Buddha at three rivers.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: North visitor centre → Leshan Station" },
          },
          {
            id: "g-d1-train-back",
            time: "17:30",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train Back to Chengdu",
            subtitle: "Leshan → Chengdu East · ~1 hour",
            description: "Evening high-speed train from Leshan back to Chengdu East. Second class (二等座) is ¥54. The journey takes about an hour. We book the exact departure linked to your passport once we've locked the cruise timing — just scan at the gate and board.",
            tip: "Our tip: Be back at Leshan Station about 20 minutes before departure. Same passport-scan boarding you used this morning — no paper ticket needed.",
            previewLine: "~1 hr · ¥54 (2nd class) · Leshan → Chengdu East",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Chengdu East Station → your hotel" },
          },
          {
            id: "g-d1-hotel",
            time: "20:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back in Chengdu",
            subtitle: "Rest up — Golden Summit tomorrow",
            description: "You're sleeping in Chengdu tonight. Early start tomorrow — train out to Mount Emei Station for the Golden Summit.",
          },
        ],
      },

      {
        label: "Day 2",
        city: "Chengdu",
        subtitle: "May 21 (Thu) · Mount Emei — Golden Summit Full Day",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d2-depart",
            time: "07:00",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Taxi to Chengdu East Station",
            subtitle: "Hotel → Chengdu East · ~30 min",
            description: "Early taxi from your Chengdu hotel to Chengdu East Station for the high-speed train out to Mount Emei. Grab breakfast from your hotel or at the station. Wear layers — the Golden Summit sits at 3,077m and can be 15°C colder than the base. Sturdy shoes help on the stone paths.",
            previewLine: "~30 min · Taxi · Hotel → Chengdu East",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Hotel → Chengdu East Station" },
          },
          {
            id: "g-d2-train-out",
            time: "08:00",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Mount Emei",
            subtitle: "Chengdu East → Mount Emei Station · 1h 15min",
            description: "High-speed train from Chengdu East to Mount Emei Station. Second class (二等座) is ¥65. The journey takes 1 hour 15 minutes. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Get off at Mount Emei Station (峨眉山站). From the station it's a short ¥10 taxi to Baoguo Temple visitor centre, the main mountain entrance.",
            previewLine: "1h 15min · ¥65 (2nd class) · Chengdu East → Mount Emei",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Mount Emei Station → Baoguo Temple visitor centre (~¥10)" },
          },
          {
            id: "g-d2-emei",
            time: "09:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Mount Emei — Golden Summit",
            description: "One of China's Four Sacred Buddhist Mountains and a UNESCO World Heritage site. Mount Emei rises 3,077m and has 76 Buddhist monasteries scattered across its slopes. The journey to the Golden Summit is part of the experience: scenic bus from Baoguo Temple visitor centre up the winding mountain road to Leidongping (about 1.5–2 hours round trip), then the Jinding cable car to the summit (~3 minutes but a 600m vertical ride). At the top, the 48-metre gold Samantabhadra Buddha statue sits on the summit platform — on a clear day you're above the clouds looking across Sichuan. On misty days it feels like floating in heaven. Costs: ¥160 mountain entry + ¥90 scenic bus round trip + ¥120 cable car (¥65 up, ¥55 down) = ¥370 total per person, all booked by us.",
            image: `${G}/emei-golden-summit.webp`,
            tip: "Our tip: Weather is everything — if the forecast shows low cloud the summit view may be whited out. The cloud sea effect (云海) typically appears early morning or late afternoon. We check the forecast the day before and flag if conditions are poor. Bring a light jacket even in May — the summit sits above the tree line.",
            previewImages: [`${G}/emei-golden-summit.webp`, `${G}/emei-wannian-temple.webp`, `${G}/emei-monkeys.jpg`],
            previewLine: "3,077m sacred Buddhist mountain — scenic bus, cable car, and a 48m gold Buddha above the clouds.",
            transportAfter: { mode: "cable-car", duration: "3 min", note: "Jinding cable car down from the summit" },
          },
          {
            id: "g-d2-wannian",
            time: "15:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Wannian Temple & Monkey Zone (optional)",
            description: "If time allows after descending from the Golden Summit, stop at Wannian Temple (built 1601) — home to a massive bronze statue of Samantabhadra on a white elephant, one of the most important Buddhist artefacts in China. The walk down through the ecological monkey zone is where you'll meet Mount Emei's famous Tibetan macaques — bold, intelligent, and will snatch anything that looks like food.",
            image: `${G}/emei-wannian-temple.webp`,
            tip: "Our tip: This is optional — only do it if you're back from the summit with at least 2 hours to spare before your return train. The monkeys are real wildlife, not a zoo — keep snacks zipped away. If you're tired, skip this and enjoy tea near Baoguo Temple instead.",
            previewImages: [`${G}/emei-wannian-temple.webp`, `${G}/emei-monkeys.jpg`, `${G}/emei-golden-summit.webp`],
            previewLine: "1601 temple with the bronze Samantabhadra, plus Mount Emei's legendary macaques.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Baoguo → Emei Mountain Station" },
          },
          {
            id: "g-d2-train-back",
            time: "18:40",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chengdu",
            subtitle: "Emei Mountain → Chengdu East · 1h 6min",
            description: "High-speed train C6264 — Mount Emei to Chengdu East, departs 18:40 and arrives 19:46. Second class (二等座) is ¥65. The journey takes 1 hour 6 minutes. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Be back at Emei Mountain Station by 18:20 with tickets already loaded to your passport. The station is small but security checks can take a few minutes.",
            previewLine: "1h 6min · ¥65 (2nd class) · C6264",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Chengdu East Station → your hotel" },
          },
          {
            id: "g-d2-hotel",
            time: "21:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back in Chengdu",
            subtitle: "Rest up — Chongqing tomorrow",
            description: "Long day — get some rest. Tomorrow morning you'll explore Wuhou Temple and Du Fu's Thatched Cottage before your afternoon train to Chongqing.",
          },
        ],
      },

      {
        label: "Day 3",
        city: "Chengdu",
        subtitle: "May 22 (Fri) · Chengdu → Chongqing — Wuhou · Du Fu Cottage · Hongyadong",
        color: "#B45309",
        items: [
          {
            id: "g-d3-wuhou",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Wuhou Shrine",
            description: "China's only shrine where a king and his minister share the same temple — dedicated to Liu Bei and Zhuge Liang from the Three Kingdoms period (1,800 years ago). Even if you don't know the history, the red-walled bamboo corridor (Hong Qiang Zhu Ying) is one of the most photographed spots in Chengdu. The bonsai garden and ancient cypress trees are beautiful, and it's a quiet, contemplative morning activity.",
            image: `${CD}/wuhou1.jpg`,
            tip: "Our tip: ¥50 entry. The red wall bamboo path is at the back — most tourists miss it. The shrine is right next to Jinli Street if you want to quickly walk through on the way out.",
            previewImages: [`${CD}/wuhou1.jpg`, `${CD}/wuhou2.jpg`, `${CD}/wuhou3.jpg`],
            previewLine: "1,800-year-old Three Kingdoms shrine with the famous red-wall bamboo path.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Du Fu's Thatched Cottage" },
          },
          {
            id: "g-d3-dufu",
            time: "10:45",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Du Fu's Thatched Cottage",
            description: "A 300-acre garden museum on the site where Du Fu — China's greatest poet — wrote 240 of his masterpieces during four years of exile. The reconstructed thatched cottage is surrounded by bamboo groves, lotus ponds, and winding paths. It's a peaceful, contemplative space and one of the most beautiful gardens in Chengdu. The perfect quiet morning before a travel afternoon.",
            image: `${CD}/dufu1.jpg`,
            tip: "Our tip: ¥50 entry. The museum has good English explanations of Du Fu's poetry. The bamboo grove behind the main cottage is the most peaceful part. Budget about 1–1.5 hours.",
            previewImages: [`${CD}/dufu1.jpg`, `${CD}/dufu2.jpg`, `${CD}/dufu3.jpg`],
            previewLine: "Where China's greatest poet wrote 240 masterpieces — bamboo groves and lotus ponds.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Chengdu East Station" },
          },
          {
            id: "g-d3-train",
            time: "14:30",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chongqing",
            subtitle: "Chengdu East → Chongqing North · ~1.5 hours",
            description: "The Chengdu–Chongqing high-speed rail is one of the busiest in China. Second class is comfortable — wide seats, power outlets, and plenty of legroom. The 300km journey takes about 1.5 hours through the Sichuan Basin. We book the tickets linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Second class (二等座) is perfectly fine — no need to upgrade. ¥150–200 one way. We book the e-ticket linked to your passport number, so you just tap your passport at the gate. No paper ticket needed.",
            previewLine: "~1.5 hrs · ¥150–200 (2nd class) · Multiple departures",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi from Chongqing North to your hotel" },
          },
          {
            id: "g-d3-checkin",
            time: "17:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Near Jiefangbei",
            subtitle: "Drop bags, relax, freshen up",
            description: "Arrive in Chongqing and check in at your hotel near Jiefangbei — the city's main pedestrian square and the heart of the downtown core. You're walking distance from Hongyadong, the Yangtze Cableway, and most of the iconic Chongqing night spots. Relax for an hour before heading out for the evening.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk from Jiefangbei to Hongyadong" },
          },
          {
            id: "g-d3-hongyadong",
            time: "19:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Hongyadong at Night",
            description: "An 11-storey stilted building complex built into the riverside cliff face — enter from the top (street level) and descend through restaurants, shops, and walkways to the river at the bottom. After dark, the golden lights turn it into what the internet calls 'the real-life Spirited Away.' The view from across the river on Qianximen Bridge is the money shot.",
            image: `${CQ}/hongyadong1.jpg`,
            tip: "Our tip: Go after 8 PM when all the lights are on. Enter from level 11 (Cangbai Road) and walk down. For the best photo, cross to the opposite riverbank or shoot from the bridge.",
            previewImages: [`${CQ}/hongyadong1.jpg`, `${CQ}/hongyadong2.jpg`, `${CQ}/hongyadong3.jpg`],
            previewLine: "11-storey cliff building lit up gold — the real-life Spirited Away.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Grab street food nearby or walk back" },
          },
        ],
      },

      /* ═══════════════════════════════════════════
         CHONGQING · May 22–25
         ═══════════════════════════════════════════ */
      {
        label: "Day 4",
        city: "Chongqing",
        subtitle: "May 23 · Chongqing — Wulong Day Trip · Three Natural Bridges",
        color: "#D0021B",
        items: [
          {
            id: "g-d4-depart",
            time: "07:00",
            icon: Bus,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Shuttle Bus to Wulong",
            subtitle: "2.5-hour ride south-east to the karst region",
            description: "Tour shuttle bus from central Chongqing to Wulong Karst National Geology Park — about 170km, 2.5 hours on the expressway. This is a full day trip — you'll be back in the city by early evening. We pre-book your seat and the park combo ticket so you skip the queues at the entrance.",
            tip: "Our tip: Grab breakfast from your hotel before the early start. The ride is scenic once you leave the city — mountains and river gorges. Bring water and snacks for the journey.",
            previewLine: "2.5 hrs · Shuttle bus · ~170 km expressway",
            transportAfter: { mode: "shuttle", duration: "2.5 hrs", note: "Shuttle bus: Chongqing → Wulong Karst entrance" },
          },
          {
            id: "g-d4-bridges",
            time: "10:00",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Natural Bridges",
            description: "Three colossal natural limestone bridges spanning a deep gorge — Tianlong (Heaven Dragon), Qinglong (Azure Dragon), and Heilong (Black Dragon). The tallest is 235 metres high and 150 metres wide. You descend 400 steps into the gorge and walk through the canyon beneath all three bridges. Halfway through is the Tianfu Inn — a traditional building used as a filming location in Transformers: Age of Extinction. The scale is hard to describe until you're standing under millions of tonnes of rock arching above you.",
            image: `${G}/wulong-three-bridges.jpg`,
            tip: "Our tip: Take the glass-floor elevator down to the gorge floor (¥15) instead of the stairs — saves your knees for the 3km walk through the canyon. The whole route takes 2–3 hours. Bring water.",
            previewImages: [`${G}/wulong-three-bridges.jpg`, `${G}/wulong-tianfu-inn.jpg`, `${G}/wulong-longshui-gorge.webp`],
            previewLine: "Three colossal limestone bridges, a 400-step descent, and the Transformers 4 filming location.",
            transportAfter: { mode: "shuttle", duration: "15 min", note: "Park shuttle to Longshui Gorge" },
          },
          {
            id: "g-d4-gorge",
            time: "12:00",
            icon: Navigation,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Longshui Gorge Earth Crack",
            description: "A narrow 5km karst fissure carved by water over millions of years — you walk along a boardwalk inside the crack, with sheer rock walls rising 200+ metres on either side, sometimes narrowing to just a few metres apart. There are waterfalls, underground streams, and the lighting makes it atmospheric. It's included in the Wulong combo ticket and takes about 1–1.5 hours.",
            image: `${G}/wulong-longshui-gorge.webp`,
            tip: "Our tip: This is included in the combo ticket with Three Natural Bridges. It's cooler inside the gorge — bring a light layer. The boardwalk can be slippery, so wear grippy shoes.",
            previewImages: [`${G}/wulong-longshui-gorge.webp`, `${G}/wulong-longshui-02.jpg`, `${G}/wulong-longshui-03.jpg`],
            previewLine: "A 5km karst fissure — sheer 200m walls, waterfalls, and a boardwalk inside the crack.",
            transportAfter: { mode: "car", duration: "2 hrs", note: "Drive back to Chongqing city" },
          },
          {
            id: "g-d4-drone",
            time: "20:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Chongqing Drone Light Show",
            description: "Chongqing runs periodic drone light shows over the Yangtze/Jialing river junction — hundreds of drones forming shapes and patterns against the night skyline. Free to watch from various riverside viewpoints. The combination of the drone show with Chongqing's already-insane neon skyline is unique.",
            tip: "Our tip: We'll confirm the exact schedule closer to your dates — these shows run on specific nights and the schedule changes. Best viewing spots are Qianximen Bridge area or the Nanbin Road riverfront. If the drone show isn't running on the 23rd, the Chongqing night skyline from Nanshan is just as spectacular.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d4-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — city day tomorrow",
            description: "Long day — you've earned the rest. Tomorrow is Chongqing city highlights and the 1949 Banquet dinner.",
          },
        ],
      },

      {
        label: "Day 5",
        city: "Chongqing",
        subtitle: "May 24 · Chongqing — Ciqikou · Cableway · 1949 Banquet",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d5-ciqikou",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Ciqikou Ancient Town",
            description: "A thousand-year-old town built on a hillside along the Jialing River. Narrow stone-paved lanes wind between old wooden buildings — tea houses, Sichuan snack stalls, and shops selling handmade crafts. Try the famous Ciqikou mahua (twisted fried dough) and Chen Mahua which has been making it here for generations.",
            image: `${CQ}/ciqikou1.jpg`,
            tip: "Our tip: Go in the morning before 11 AM — the main street gets very crowded by noon. The side alleys are quieter and more interesting. Free entry.",
            previewImages: [`${CQ}/ciqikou1.jpg`, `${CQ}/ciqikou2.jpg`, `${CQ}/ciqikou3.jpg`],
            previewLine: "1,000-year-old hillside town — stone lanes, tea houses, and twisted fried dough.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi to Jiefangbei / city centre" },
          },
          {
            id: "g-d5-liziba",
            time: "14:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Liziba Monorail & Jiefangbei",
            description: "Watch Line 2 of the Chongqing monorail punch straight through an apartment building at Liziba station — the most viral transport video in China. Then walk to Jiefangbei, Chongqing's main pedestrian square, where the liberation monument is surrounded by skyscrapers and massive LED screens.",
            image: `${CQ}/liziba1.jpg`,
            tip: "Our tip: The best viewing spot for the monorail is from the street below the building. Free — just show up and wait for the next train. Jiefangbei is a 10-minute walk from there.",
            previewImages: [`${CQ}/liziba1.jpg`, `${CQ}/liziba2.jpg`, `${CQ}/jiefangbei1.jpg`],
            previewLine: "A monorail through an apartment building — Chongqing's most viral moment.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the Yangtze Cableway station" },
          },
          {
            id: "g-d5-cableway",
            time: "16:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Yangtze River Cableway",
            description: "The only urban passenger cableway still operating over the Yangtze River. A 5-minute ride in a retro cabin 300 metres above the water, with the entire Chongqing skyline and river spread out below you. It's been running since 1987 and was originally built as public transport — now it's the city's most iconic experience.",
            image: `${CQ}/cableway1.jpg`,
            tip: "Our tip: Take it from the Xinhua Road station (north side) for the best skyline views. ¥30 return. Queues can be 30-60 minutes — we can advise on timing to avoid the worst.",
            previewImages: [`${CQ}/cableway1.jpg`, `${CQ}/cableway2.jpg`, `${CQ}/cableway3.jpg`],
            previewLine: "Retro cable car 300m above the Yangtze — Chongqing's most iconic ride.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to 1949 Banquet" },
          },
          {
            id: "g-d5-1949",
            time: "19:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "activity",
            title: "1949 Banquet — Immersive Dinner Show",
            description: "An immersive dinner theatre set in 1949 Chongqing — the pivotal year when the city was the last Nationalist capital before the Communist revolution. You walk through elaborately recreated 1940s streetscapes (tea houses, newspaper offices, dance halls) while actors perform scenes around you. The multi-course banquet features traditional Chongqing dishes served in period settings. It's part dinner, part theatre, part time travel.",
            tip: "Our tip: This needs to be booked well in advance — it's one of Chongqing's most popular experiences. The show is about 2–3 hours including dinner. We handle the booking and can request English-friendly seating.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d5-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — Zhangjiajie tomorrow",
            description: "Your last night in Chongqing. Pack up — tomorrow you take the high-speed train to Zhangjiajie.",
          },
        ],
      },

      {
        label: "Day 6",
        city: "Chongqing",
        subtitle: "May 25 · Chongqing → Zhangjiajie — Travel Day",
        color: "#B45309",
        items: [
          {
            id: "g-d6-museum",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Gorges Museum & People's Great Hall",
            description: "A free, world-class museum covering the Three Gorges region, the Three Gorges Dam project, ancient Ba culture, and wartime Chongqing (the city was China's WWII capital after the Nationalists fled Nanjing). The WWII bombing exhibition is particularly powerful — Chongqing was bombed for 5 years straight by Japanese forces, the longest continuous bombing of any city in history. The museum sits across a grand square from the People's Great Hall, a Soviet-influenced auditorium modelled on Beijing's Temple of Heaven that's one of Chongqing's most photographed buildings.",
            image: `${G}/museum-three-gorges.jpg`,
            tip: "Our tip: Free entry with your passport — bring it. Budget 1.5 hours inside. The WWII section and the Three Gorges environmental exhibition are the highlights. Walk across the square afterwards for a photo of the People's Great Hall — you can't go inside but the exterior is the iconic shot.",
            previewImages: [`${G}/museum-three-gorges.jpg`, `${G}/museum-wartime.jpg`, `${G}/museum-ancient-ba.png`],
            previewLine: "Free museum — WWII history, Three Gorges Dam, and ancient Ba culture.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Kuixing Building" },
          },
          {
            id: "g-d6-kuixing",
            time: "11:00",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Kuixing Building",
            description: "Chongqing's most famous '8D city' moment. You walk into what looks like the ground floor of a building and realise you're actually on the 22nd floor above another tower built further down the hillside. A sky bridge suspended 22 storeys high connects the two — one end is at street level, the other is a skyscraper viewpoint. Named after Kuixing, the Taoist deity of literature and examinations, with a small traditional temple perched at the top. This is the spot that captures exactly why Chongqing is called the world's most vertical city — gravity feels optional here, every staircase leads to a different story, and the cyberpunk energy is real.",
            image: `${G}/kuixing-01.jpg`,
            tip: "Our tip: Free to visit, about 30–45 minutes is enough. Easy to miss — it looks like a normal office building from the street, so use the Gaode map pin we'll send you. The sky bridge is the money shot; walk across it both ways. Best before 11 AM or after 3 PM to avoid the social-media crowds.",
            previewImages: [`${G}/kuixing-01.jpg`, `${G}/kuixing-02.webp`, `${G}/kuixing-03.jpg`],
            previewLine: "Chongqing's most famous 8D-city moment — a sky bridge between two buildings where one end is the street and the other is 22 floors up.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Chongqing East Station" },
          },
          {
            id: "g-d6-train",
            time: "13:00",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Zhangjiajie",
            subtitle: "Chongqing East → Zhangjiajie West · ~2–3 hours",
            description: "The Chongqing–Zhangjiajie high-speed line opened in 2025 — what used to be a 5+ hour journey is now just 2–3 hours. The route cuts through dramatic karst landscapes in Hubei province. You'll arrive at Zhangjiajie West station, where your transfer is waiting.",
            tip: "Our tip: Second class is fine. ~¥200–250 one way. Same passport-scan boarding as the Chengdu train. The scenery through the window is worth staying awake for — tunnels and bridges through karst mountains.",
            previewLine: "~2–3 hrs · ¥200–250 (2nd class) · Opened 2025",
            transportAfter: { mode: "car", duration: "45 min", note: "Pre-arranged transfer to Wulingyuan" },
          },
          {
            id: "g-d6-arrive",
            time: "16:30",
            icon: MapPin,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Arrive Wulingyuan",
            description: "Your hotel is in the Wulingyuan area — the gateway town right next to Zhangjiajie National Forest Park. This is where you'll stay for 4 nights while you explore the park, Grand Canyon, and caves. The town has restaurants, shops, and the XiBu Street night market along the river.",
            tip: "Our tip: Tonight is free — walk XiBu Street along the river for a preview of the town. It's lit up at night with bars and food stalls. Mugwort cakes (艾草粑粑) are the local snack to try.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to hotel" },
          },
          {
            id: "g-d6-hotel",
            time: "17:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Wulingyuan",
            subtitle: "Rest up — Forest Park tomorrow",
            description: "Get settled and rest. Tomorrow is the big one — Zhangjiajie National Forest Park, the Bailong Elevator, and the Avatar mountains.",
          },
        ],
      },

      /* ═══════════════════════════════════════════
         ZHANGJIAJIE · May 25–31
         ═══════════════════════════════════════════ */
      {
        label: "Day 7",
        city: "Zhangjiajie",
        subtitle: "May 26 · Zhangjiajie — Forest Park · Bailong Elevator · Tianzi Mountain",
        color: "#D0021B",
        items: [
          {
            id: "g-d7-park",
            time: "08:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Zhangjiajie National Forest Park",
            description: "Thousands of tall sandstone pillars in a huge forested valley — this is the park that inspired the mountains in Avatar. You'll take the Bailong Elevator up the cliff (326m, the world's tallest outdoor lift), walk the Yuanjiajie ridge to the main viewpoints (Avatar Hallelujah Mountain, First Natural Bridge, Enchanting Terrace), then explore the platform trails.",
            image: FOREST,
            tip: "Our tip: Enter via the East Gate and head straight for the Bailong Elevator before the queues build. Peak season waits can hit 1-2 hours — we pre-book VIP fast-track passes to skip them.",
            previewImages: [FOREST, BAILONG, AVATAR],
            previewLine: "Towering sandstone pillars, the Bailong Elevator, and Avatar-inspiring views.",
            transportAfter: { mode: "cable-car", duration: "25 min", note: "Cable car up to Tianzi Mountain ridge" },
          },
          {
            id: "g-d7-tianzi",
            time: "14:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Tianzi Mountain",
            description: "The highest viewpoint in Wulingyuan (1,262m) — the ridge-top platform gives you an endless panorama of sandstone pillars stretching to the horizon. On misty mornings the tops poke through clouds like a sea of stone islands. You'll take the cable car up and walk the ridge trail between lookout points. The 'Imperial Writing Brush' formation — three thin pillars topped with trees — is one of China's most-photographed natural landmarks.",
            image: TIANZI,
            tip: "Our tip: Cable car queues can be brutal — aim to arrive by 2:30pm. If it's cloudy, the mist actually makes it better. We book the combo transport pass so you're not paying per ride.",
            previewImages: [TIANZI, TIANZI_CLOUDS, AVATAR],
            previewLine: "The highest peak in Wulingyuan — cable car up, sea of clouds below.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi down to your Wulingyuan hotel" },
          },
          {
            id: "g-d7-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — valley walk tomorrow",
            description: "Great first day in the park. Tomorrow is a more relaxed pace — a cultural workshop and the Golden Whip Stream valley walk.",
          },
        ],
      },

      {
        label: "Day 8",
        city: "Zhangjiajie",
        subtitle: "May 27 · Zhangjiajie — Golden Whip Stream · Evening Show",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d8-stream",
            time: "14:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Golden Whip Stream",
            description: "A 7.5km walking trail along a crystal-clear stream at the bottom of the sandstone canyon — towering pillars and cliffs on both sides, huge trees, waterfalls, and wild macaque monkeys. It's flat, shaded, and one of the most beautiful walks in China. The water is turquoise-green and you can hear it the entire way. The 'Golden Whip Rock' formation — a thin 380m-tall pillar — is the highlight.",
            image: GOLDEN,
            tip: "Our tip: The full walk takes about 2.5 hours. Keep snacks in a zipped bag — the monkeys here are aggressive food thieves. We'll make sure you know which exit to take for your pickup.",
            previewImages: [GOLDEN, STREAM_CLOSE, AVATAR],
            previewLine: "A 7.5km valley walk through turquoise water and towering cliffs — monkeys included.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi back to town for the Charming Xiangxi show" },
          },
          {
            id: "g-d8-show",
            time: "20:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Charming Xiangxi Show",
            description: "A massive outdoor live performance with 500+ performers — real waterfalls on stage, fire, traditional Tujia and Miao ethnic culture, and dramatic lighting against the mountains. It tells the story of western Hunan's history through music, dance, and theatre. One of the most impressive live shows in China.",
            image: "/uploads/itinerary/xiangxi_show.jpg",
            tip: "Our tip: Tickets sell out and need to be booked in advance through Chinese-only platforms. The show is about 90 minutes — bring a light jacket for the open-air theatre. We handle the booking.",
            previewImages: ["/uploads/itinerary/xiangxi_show.jpg", SHOW_STAGE, "/uploads/itinerary/tujia_silk3.jpeg"],
            previewLine: "500+ performers, real waterfalls on stage, fire, and Tujia & Miao culture.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi back to hotel" },
          },
          {
            id: "g-d8-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Grand Canyon tomorrow",
            description: "Great day. Tomorrow is the Zhangjiajie Grand Canyon and the famous Glass Bridge.",
          },
        ],
      },

      {
        label: "Day 9",
        city: "Zhangjiajie",
        subtitle: "May 28 · Zhangjiajie — Grand Canyon · Glass Bridge",
        color: "#B45309",
        items: [
          {
            id: "g-d9-canyon",
            time: "08:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Zhangjiajie Grand Canyon",
            description: "A dramatic gorge carved into the sandstone — you descend steep stairs through a series of waterfalls and cliff-hugging walkways, past caves and natural springs, down to the turquoise river at the bottom. The canyon is about 3.5km long and takes 2–3 hours to walk. The Yibu Nanqiao (One Step Hard Bridge) is a narrow natural stone bridge high above the canyon that makes for a heart-pounding photo.",
            image: `${G}/grand-canyon-hike.png`,
            tip: "Our tip: Start early (8 AM) to beat the crowds. The descent has a lot of stairs — good shoes are essential. The canyon is a one-way route so you can't turn back. We book the tickets in advance (¥128 + glass bridge combo).",
            previewImages: [`${G}/grand-canyon-hike.png`, `${G}/grand-canyon-01.jpg`, `${G}/grand-canyon-02.jpg`],
            previewLine: "Waterfalls, cliff walkways, and a turquoise river at the canyon floor.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Glass Bridge entrance" },
          },
          {
            id: "g-d9-glass",
            time: "10:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Zhangjiajie Glass Bridge",
            description: "The world's longest and highest glass-bottomed bridge — 430 metres long, suspended 300 metres above the Grand Canyon floor. You walk across transparent glass panels with the canyon yawning below your feet. It's engineered to hold 800 people but they limit numbers, so it never feels crowded. The views down through the glass and out across the canyon are vertigo-inducing.",
            image: `${G}/glass-bridge.webp`,
            tip: "Our tip: You're only allowed 30 minutes on the bridge. No bags, selfie sticks, or loose items allowed — there are free lockers at the entrance. Shoe covers provided. If you want to bungee jump off the bridge (the world's highest commercial bungee at 260m), we can book that too.",
            previewImages: [`${G}/glass-bridge.webp`, `${G}/grand-canyon-bungee.png`, `${G}/grand-canyon-02.jpg`],
            previewLine: "430m long, 300m high — the world's longest glass-bottomed bridge.",
            transportAfter: { mode: "shuttle", duration: "15 min", note: "Shuttle back to the visitor centre" },
          },
          {
            id: "g-d9-free",
            time: "15:00",
            icon: Footprints,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Free Afternoon",
            description: "You've had a big morning. Options: rest at the hotel, explore Wulingyuan town, or visit Baofeng Lake — a serene alpine lake inside a sandstone amphitheatre where you take a boat ride past waterfalls and towering cliffs. The boat ride is about 30 minutes and it's one of the quieter, more beautiful spots in the area.",
            tip: "Our tip: If you do Baofeng Lake, it's ¥96 entry including the boat. It's about 20 minutes from town by taxi. Best in the late afternoon light.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Back to hotel or town" },
          },
          {
            id: "g-d9-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest — caves and city transfer tomorrow",
            description: "Tomorrow morning is Yellow Dragon Cave, then you transfer to your new hotel in Zhangjiajie city for the final stretch of the trip.",
          },
        ],
      },

      {
        label: "Day 10",
        city: "Zhangjiajie",
        subtitle: "May 29 · Zhangjiajie — Yellow Dragon Cave · Transfer to City · 72 Tower",
        color: "#D0021B",
        items: [
          {
            id: "g-d10-cave",
            time: "08:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Yellow Dragon Cave",
            description: "One of China's most spectacular show caves — a vast underground karst system with a river running through it. You walk through massive chambers filled with stalactites, stalagmites, and flowstone formations lit with coloured lights. The highlight is the 'Dinghai Shenzhen' — a single 19.2-metre stalagmite that's been insured for ¥100 million. There's also an underground boat ride along the subterranean river.",
            image: `${G}/yellow-dragon-hall.png`,
            tip: "Our tip: The cave tour takes about 2 hours and includes the boat ride. It's a constant 16°C inside — bring a light jacket even in summer. ¥100 entry. We pre-book tickets.",
            previewImages: [`${G}/yellow-dragon-hall.png`, `${G}/yellow-dragon-stalagmite.webp`, `${G}/yellow-dragon-river.jpg`],
            previewLine: "Vast underground chambers, a 19m stalagmite insured for ¥100 million, and a river boat ride.",
            transportAfter: { mode: "car", duration: "45 min", note: "Transfer to your new Zhangjiajie city hotel" },
          },
          {
            id: "g-d10-checkin",
            time: "14:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Zhangjiajie City",
            subtitle: "New hotel for the final 2 nights",
            description: "You're now in Zhangjiajie city itself (about 45 minutes from Wulingyuan). This is the base for Tianmen Mountain and the 72 Qilou Tower — both are in or near the city centre.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to 72 Qilou" },
          },
          {
            id: "g-d10-72tower",
            time: "15:30",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "72 Qilou Tower",
            description: "A striking 12-storey tower complex built into the cliffside in traditional Tujia and Miao architectural style — it looks like something out of a fantasy film. The tower combines ethnic minority cultural exhibits, restaurants, shops, and observation decks with views over the city and surrounding mountains. The rooftop terrace gives panoramic views, especially at sunset.",
            image: `${G}/72-tower-01.png`,
            tip: "Our tip: Come in the late afternoon for the best light. The tower is especially photogenic from the outside — the stacked traditional architecture against the mountain backdrop. It's free to walk around the exterior; some interior sections have small entry fees.",
            previewImages: [`${G}/72-tower-01.png`, `${G}/72-tower-02.jpg`, `${G}/72-tower-03.jpg`],
            previewLine: "12-storey Tujia-style tower built into the cliffside — Zhangjiajie's architectural icon.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi back to your hotel" },
          },
          {
            id: "g-d10-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Tianmen Mountain tomorrow",
            description: "Get a good sleep — tomorrow is Tianmen Mountain, one of the most dramatic mountain experiences in China. Early start for the cable car.",
          },
        ],
      },

      {
        label: "Day 11",
        city: "Zhangjiajie",
        subtitle: "May 30 · Zhangjiajie — Tianmen Mountain · Glass Skywalks · 999 Steps",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d11-cable",
            time: "08:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Tianmen Mountain Cable Car",
            description: "The world's longest passenger cableway — 7,455 metres from the city centre straight up to the Tianmen Mountain summit at 1,518m. The 28-minute ride takes you from street level over the city, through the foothills, and into the clouds. The steepest section climbs at a 37-degree angle. On a clear day you can see the entire Zhangjiajie basin below.",
            image: "/uploads/itinerary/tianmen_cable1.jpg",
            tip: "Our tip: Book the earliest time slot (8:00 AM) to avoid queues and get the clearest weather. Sit on the right side going up for the best mountain views. Bring a warm jacket — the summit is 10-15°C colder than the city.",
            previewImages: ["/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "A 28-minute ride from city streets into the clouds — 7.5km of jaw-dropping scenery.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the east summit trail" },
          },
          {
            id: "g-d11-glass",
            time: "09:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Glass Skywalks",
            description: "A glass-floored walkway bolted to the sheer cliff face at 1,400m — you walk along transparent panels with a 300-metre drop below your feet and the mountain wall on one side. The east side walk is longer (60m) and more exposed than the west. Even if you're not scared of heights, looking straight down through glass at a 300m cliff is a different experience entirely.",
            tip: "Our tip: The east side glass walk is longer and more dramatic than the west. You need shoe covers (¥5, bought on-site). Even people without fear of heights find their knees going weak — it's genuinely thrilling.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the escalator entrance" },
          },
          {
            id: "g-d11-cave",
            time: "13:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Heaven's Gate (Tianmen Cave) & 999 Steps",
            description: "Tianmen Cave is a natural hole punched through the mountain — 131 metres high, 57 metres wide, visible from the city below. To reach it you descend the famous 999 steps (the 'Stairway to Heaven'), a near-vertical stone staircase clinging to the cliff face. The number 999 represents 'heaven' in Chinese numerology. Standing inside the cave with clouds drifting through and the valley visible far below is one of those moments you don't forget.",
            tip: "Our tip: Take it slow on the steep upper sections and use the railings — the steps are uneven. The cave itself is most dramatic when clouds drift through it, which happens most mornings.",
            previewImages: ["/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "131m-high natural cave, 999 steps, and the feeling of descending from heaven.",
            transportAfter: { mode: "shuttle", duration: "25 min", note: "Coach down the 99-bend road" },
          },
          {
            id: "g-d11-99bend",
            time: "15:00",
            icon: Camera,
            iconBg: "#E3F2FD",
            type: "activity",
            title: "99-Bend Road (Tongtian Avenue)",
            description: "The coach ride down Tongtian Avenue — nearly 11 kilometres of mountain road with 99 hairpin turns switchbacking from 1,300m to 200m. The bus drivers navigate blind 180-degree turns with centimetres of clearance. It's equal parts terrifying and impressive, and the aerial views from above are spectacular.",
            tip: "Our tip: Sit on the left side for the best cliff-drop views. The ride takes about 25 minutes. If you get motion sick easily, take medication beforehand.",
            previewImages: ["/uploads/itinerary/99bend1.webp", "/uploads/itinerary/99bend2.jpeg", "/uploads/itinerary/99bend3.webp"],
            previewLine: "99 hairpin turns, 1,300m descent — the most dramatic bus ride of your life.",
          },
          {
            id: "g-d11-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Last night in China — long travel day tomorrow",
            description: "Your last night. Pack everything up — tomorrow is a full travel day back to Chengdu and onward to Hanoi.",
          },
        ],
      },

      {
        label: "Day 12",
        city: "Zhangjiajie",
        subtitle: "May 31 (Sat) · Zhangjiajie → Chengdu → Hanoi",
        color: "#059669",
        items: [
          {
            id: "g-d12-train",
            time: "Early",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chongqing",
            subtitle: "Zhangjiajie West → Chongqing East · ~2–3 hours",
            description: "High-speed train from Zhangjiajie West to Chongqing East on the line that opened in 2025. Second class (二等座) is ¥244. The journey takes about 2–3 hours through dramatic karst landscapes. We book the ticket linked to your passport and time it to your onward connection.",
            tip: "Our tip: Same passport-scan boarding you've been using all trip. The scenery through the window is worth staying awake for — tunnels and bridges through karst mountains.",
            previewLine: "~2–3 hrs · ¥244 (2nd class) · Zhangjiajie → Chongqing",
            transportAfter: { mode: "taxi", duration: "50 min", note: "Taxi to Chengdu Tianfu International Airport" },
          },
          {
            id: "g-d12-flight",
            time: "Flight TBC",
            icon: Plane,
            iconBg: "#E8F5E9",
            type: "transport",
            title: "Flight to Hanoi",
            subtitle: "Chengdu Tianfu International → Hanoi",
            description: "Your onward flight from Chengdu Tianfu International Airport (CTU) to Hanoi. The flight itself is on your own booking — we handle everything up to the airport: the train, the transfer, and making sure you arrive with enough time to check in and clear international departure immigration.",
            tip: "Our tip: Chengdu has two airports — double-check your flight leaves from Tianfu (the newer international hub, ~60 km south-east of the city) rather than Shuangliu (the older domestic-focused airport closer to downtown). Arrive 2.5–3 hours before an international flight. Have your Vietnam visa / e-visa confirmation ready.",
            previewLine: "International departure · Arrive 2.5–3 hrs early · CTU Tianfu",
          },
        ],
      },
    ],

    picks: [
      {
        id: "g-pick-opera",
        emoji: "🎭",
        type: "Culture",
        title: "Sichuan Opera Face-Changing",
        desc: "A full Sichuan opera show in Chengdu with the famous 'face-changing' (bian lian) — performers swap painted masks in a fraction of a second. Nobody knows how.",
        meiNote: "Several theatres do this in Chengdu. We book the best one with good seats — tickets are Chinese-platform only. Could fit on the evening of Day 1 or Day 2.",
        image: `${CD}/jinli1.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "g-pick-cooking",
        emoji: "🌶️",
        type: "Food",
        title: "Sichuan Cooking Class",
        desc: "A hands-on class in Chengdu where you learn to cook mapo tofu, kung pao chicken, and dan dan noodles. Includes market visit to buy ingredients.",
        meiNote: "Half day, includes lunch — you eat everything you cook. Could replace the Day 1 afternoon if you're more into food than history.",
        image: `${CD}/wuhou1.jpg`,
        tag: "We can arrange",
        tagColor: "#059669",
      },
      {
        id: "g-pick-fenghuang",
        emoji: "🏘️",
        type: "Day Trip",
        title: "Fenghuang Ancient Town",
        desc: "A perfectly preserved riverside town with 300-year-old stilted houses, stone bridges, and lantern-lit streets — often called the most beautiful small town in China. About 3.5 hours from Zhangjiajie.",
        meiNote: "You have spare time in the Zhangjiajie stretch — we could swap one of the free afternoons for a Fenghuang day trip. It's a long day but worth it.",
        image: TIANZI,
        tag: "Day trip",
        tagColor: "#B45309",
      },
      {
        id: "g-pick-cruise",
        emoji: "🌃",
        type: "Nightlife",
        title: "Two Rivers Night Cruise — Chongqing",
        desc: "A 1-hour boat ride where the Yangtze and Jialing rivers meet — see the entire lit-up Chongqing skyline, Hongyadong, and bridges from the water.",
        meiNote: "Boats run 7-10 PM nightly in Chongqing. ¥100-200 depending on deck. Could fit on the evening of Day 3 or Day 5.",
        image: `${CQ}/hongyadong1.jpg`,
        tag: "We can book",
        tagColor: "#7C3AED",
      },
    ],
  };
}
