import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints, TrainFront, Car, Bus, MapPin, Plane } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

/* ── Image path prefixes ── */
const CD = "/uploads/itinerary/chengdu";
const CQ = "/uploads/itinerary/chongqing";
const ZJJ = "https://d2xsxph8kpxj0f.cloudfront.net/310519663383502924/dCuiiEQEkteYUXqqZRtP5i";
const G = "/uploads/itinerary/giovanni";
const ZJJI = "/uploads/itinerary/giovanni/zjj";

/* ── ZJJ CDN image shortcuts ── */
const FOREST = `${ZJJ}/zjj-forest-park-Fk6sgYY4AzscGgsTAdGZLa.webp`;
const TIANZI = `${ZJJ}/zjj-tianzi-mountain-XX5qUieAEsabKUeYk3JHxK.webp`;
const GOLDEN = `${ZJJ}/zjj-golden-whip-8i6gvipo7fjNjnMVU35ZsX.webp`;
const BAILONG = `${ZJJ}/zjj-bailong-elevator-9wBE8Ew5MeTzffXtu96bUz.webp`;
const AVATAR = `${ZJJ}/zjj-avatar-pillars-JfnwwF7VRiJvmNKdnJuoV2.webp`;
const TIANZI_CLOUDS = `${ZJJ}/zjj-tianzi-clouds-9hojziDU5h4PbieGP8mtEX.webp`;
const STREAM_CLOSE = `${ZJJ}/zjj-stream-close-hBhQpt79q4p9cSqndUf8Ww.webp`;
const HUNAN_FOOD = `${ZJJ}/zjj-hunan-food-5uvTJyHoH4ttNhNFdYfrT2.webp`;
const SHOW_STAGE = `${ZJJ}/zjj-show-stage-5vsSH7YEVUrQP8TKivY3B2.webp`;

export function buildGiovanniConfig(): ItineraryConfig {
  return {
    cityName: "China",
    title: "China Adventure",
    location: "Chengdu · Chongqing · Zhangjiajie",
    duration: "13 Days · May 19–31",
    heroImage: AVATAR,
    meiGreeting: "Giovanni — here's your trip, day by day. Every ticket, train, restaurant, and transfer is laid out below. Review it, tell us what to adjust, and we'll start booking everything.",
    departure: {
      time: "May 31 · End of day",
      title: "Onward to Hanoi",
      description: "Day 12 covers the full travel out: high-speed train Zhangjiajie → Chengdu (via Chongqing, ~5 hrs), taxi to Chengdu Tianfu International, then your onward flight to Hanoi. We book the train and airport transfer linked to your passport and time it to your flight.",
    },
    departureNote: "Safe travels! Message us any time during the trip — we're on WhatsApp 24/7 while you're in China.",
    days: [
      /* ═══════════════════════════════════════════
         CHENGDU · May 19–22
         ═══════════════════════════════════════════ */
      {
        label: "Day 0",
        city: "Chengdu",
        subtitle: "May 19 (Tue) · Landing Day · Arrival & Rest",
        color: "#7B6CD9",
        items: [
          {
            id: "g-d0-arrival",
            time: "15:00",
            icon: Plane,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Arrive Chengdu Tianfu International",
            subtitle: "Landing at TFU · 15:00",
            description: "You land at Chengdu Tianfu International (TFU) at 15:00. TFU is the newer international hub, about 50 km south-east of the city centre. After landing, clear immigration and collect your checked bag — you should be through arrivals by around 16:00.",
            tip: "Our tip: Fill in your arrival card on the plane. Free airport WiFi works without a Chinese number — just use your passport to log in. Have our WhatsApp open so we can confirm your taxi pickup — a driver will be waiting with a ChinaPal sign.",
            previewLine: "Lands 15:00 at TFU · ChinaPal driver at arrivals",
            transportAfter: { mode: "taxi", duration: "1 hr", note: "Taxi: TFU → Chengdu hotel" },
          },
          {
            id: "g-d0-checkin",
            time: "17:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Chengdu Hotel",
            subtitle: "Drop bags, freshen up",
            description: "Check in at your Chengdu hotel and settle in. Take the evening at your own pace — tomorrow is a full day with the Panda Base and Leshan Giant Buddha.",
          },
          {
            id: "g-d0-dinner",
            time: "19:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "activity",
            title: "Easy First Dinner",
            description: "A relaxed first meal nearby — we'll suggest 2–3 walkable options near your hotel depending on where you end up staying. Sichuan food is famous for the heat, but plenty of dishes are mild if your stomach is jet-lagged.",
            tip: "Our tip: Don't go too heavy on the spice tonight — save your Sichuan deep dive for tomorrow when you're rested. A simple bowl of dan dan noodles or wonton soup is the perfect first-night meal.",
            previewLine: "Relaxed first meal · 2–3 walkable options near hotel",
          },
          {
            id: "g-d0-hotel",
            time: "21:30",
            icon: Moon,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Early Night",
            subtitle: "Rest up — Panda Base early tomorrow",
            description: "Get a good sleep — tomorrow starts early for the Panda Base, then high-speed train to Leshan for the Giant Buddha.",
          },
        ],
      },

      {
        label: "Day 1",
        city: "Chengdu",
        subtitle: "May 20 (Wed) · Panda Base · Leshan Giant Buddha",
        color: "#D0021B",
        items: [
          {
            id: "g-d1-taxi",
            time: "07:45",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Taxi to Panda Base",
            subtitle: "Hotel → Panda Base West Gate · ~40 min",
            description: "Early taxi from your Chengdu hotel out to the Panda Base West Gate. Pandas are most active before 10 AM, so we want you there shortly after the gates open at 7:30. Grab breakfast from your hotel or pick something up en route.",
            tip: "Our tip: Keep a day pack with your passport, phone, charger, and a layer. We pre-arrange the driver so you can head straight out.",
            previewLine: "~40 min taxi · Hotel → Panda Base West Gate",
            transportAfter: { mode: "taxi", duration: "40 min", note: "Taxi: Hotel → Panda Base West Gate" },
          },
          {
            id: "g-d1-panda",
            time: "08:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Giant Panda Base",
            description: "The world's largest captive panda breeding facility — 244 giant pandas in naturalistic forest enclosures. You'll see adults lazily eating bamboo, red pandas climbing trees, and if you're lucky, the nursery with newborn cubs behind glass. The base is huge (200+ hectares) but the best enclosures are clustered together. Cost: ¥55 entry + ¥85 audio guide (we bundle both). Gates open at 7:30 AM.",
            image: `${CD}/panda1.jpg`,
            tip: "Our tip: Pandas are most active before 10 AM and crowds arrive by 9 — arriving right after opening catches the best window. The audio guide (¥85) is worth it; tickets must be booked on Chinese apps days in advance. We handle both.",
            previewImages: [`${CD}/panda1.jpg`, `${CD}/panda2.jpg`, `${CD}/panda3.jpg`],
            previewLine: "244 giant pandas — adults, cubs, and red pandas in bamboo forest enclosures.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Panda Base → Chengdu East Station" },
          },
          {
            id: "g-d1-train-leshan",
            time: "12:13",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Leshan",
            subtitle: "Chengdu East → Leshan · 53 minutes",
            description: "High-speed train C6255 — Chengdu East to Leshan, departs 12:13 and arrives 13:06. Second class (二等座) is ¥51. The 160km journey takes 53 minutes through the Sichuan Basin. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Get off at Leshan Station (not Emei Station — that's for the mountain tomorrow). From Leshan Station it's a 15-minute taxi to the Giant Buddha boat pier.",
            previewLine: "53 min · ¥51 (2nd class) · C6255",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi: Leshan Station → Giant Buddha boat pier" },
          },
          {
            id: "g-d1-leshan",
            time: "13:30",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Leshan Giant Buddha",
            description: "A 71-metre Buddha carved into a cliff face where three rivers collide — the largest stone Buddha in the world, built over 90 years starting in 713 AD. From the top you look down at his head; from the river you see the full figure. The carving is so massive that 100 people can sit on each foot. The hidden drainage system (inside the hair curls and robes) has kept it standing for 1,300 years. Two ways to see it: Option 1 is the boat cruise (¥70, 40–60 minutes) — the easy choice, giving you the iconic full-body view plus the 'giant sleeping Buddha' formation and the Three Rivers confluence. Option 2 is the cliff path hike / 九曲栈道 (¥80, ~3 hours) — enter at the North Gate, walk past the Buddha's head, down the nine-bend cliff stairs to his feet, and out the East Gate. The hike gives amazing close-up views but requires good stamina and queues of up to 2 hours.",
            image: `${G}/leshan-buddha.webp`,
            tip: "Our tip: After the early Panda Base morning we recommend the boat (Option 1) — you'll be fresh rather than exhausted, and the tour-bus crowds have cleared by the time you arrive. If you're up for the climb, Option 2 is spectacular but plan for a 3-hour physical effort.",
            previewImages: [`${G}/leshan-buddha.webp`, `${G}/leshan-cliff-path.jpg`, `${G}/leshan-three-rivers.webp`],
            previewLine: "71 metres tall, 1,300 years old — the world's largest stone Buddha at three rivers.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: North visitor centre → Leshan Station" },
          },
          {
            id: "g-d1-train-back",
            time: "17:30",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train Back to Chengdu",
            subtitle: "Leshan → Chengdu East · ~1 hour",
            description: "Evening high-speed train from Leshan back to Chengdu East. Second class (二等座) is ¥54. The journey takes about an hour. We book the exact departure linked to your passport once we've locked the cruise timing — just scan at the gate and board.",
            tip: "Our tip: Be back at Leshan Station about 20 minutes before departure. Same passport-scan boarding you used this morning — no paper ticket needed.",
            previewLine: "~1 hr · ¥54 (2nd class) · Leshan → Chengdu East",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Chengdu East Station → your hotel" },
          },
          {
            id: "g-d1-hotel",
            time: "20:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back in Chengdu",
            subtitle: "Rest up — Golden Summit tomorrow",
            description: "You're sleeping in Chengdu tonight. Early start tomorrow — train out to Mount Emei Station for the Golden Summit.",
          },
        ],
      },

      {
        label: "Day 2",
        city: "Chengdu",
        subtitle: "May 21 (Thu) · Mount Emei — Golden Summit Full Day",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d2-depart",
            time: "07:00",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Taxi to Chengdu East Station",
            subtitle: "Hotel → Chengdu East · ~30 min",
            description: "Early taxi from your Chengdu hotel to Chengdu East Station for the high-speed train out to Mount Emei. Grab breakfast from your hotel or at the station. Wear layers — the Golden Summit sits at 3,077m and can be 15°C colder than the base. Sturdy shoes help on the stone paths.",
            previewLine: "~30 min · Taxi · Hotel → Chengdu East",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi: Hotel → Chengdu East Station" },
          },
          {
            id: "g-d2-train-out",
            time: "08:00",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Mount Emei",
            subtitle: "Chengdu East → Mount Emei Station · 1h 15min",
            description: "High-speed train from Chengdu East to Mount Emei Station. Second class (二等座) is ¥65. The journey takes 1 hour 15 minutes. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Get off at Mount Emei Station (峨眉山站). From the station it's a short ¥10 taxi to Baoguo Temple visitor centre, the main mountain entrance.",
            previewLine: "1h 15min · ¥65 (2nd class) · Chengdu East → Mount Emei",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Mount Emei Station → Baoguo Temple visitor centre (~¥10)" },
          },
          {
            id: "g-d2-emei",
            time: "09:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Mount Emei — Golden Summit",
            description: "One of China's Four Sacred Buddhist Mountains and a UNESCO World Heritage site. Mount Emei rises 3,077m and has 76 Buddhist monasteries scattered across its slopes. The journey to the Golden Summit is part of the experience: scenic bus from Baoguo Temple visitor centre up the winding mountain road to Leidongping (about 1.5–2 hours round trip), then the Jinding cable car to the summit (~3 minutes but a 600m vertical ride). At the top, the 48-metre gold Samantabhadra Buddha statue sits on the summit platform — on a clear day you're above the clouds looking across Sichuan. On misty days it feels like floating in heaven. Costs: ¥160 mountain entry + ¥90 scenic bus round trip + ¥120 cable car (¥65 up, ¥55 down) = ¥370 total per person, all booked by us.",
            image: `${G}/emei-golden-summit.webp`,
            tip: "Our tip: Weather is everything — if the forecast shows low cloud the summit view may be whited out. The cloud sea effect (云海) typically appears early morning or late afternoon. We check the forecast the day before and flag if conditions are poor. Bring a light jacket even in May — the summit sits above the tree line.",
            previewImages: [`${G}/emei-golden-summit.webp`, `${G}/emei-wannian-temple.webp`, `${G}/emei-monkeys.jpg`],
            previewLine: "3,077m sacred Buddhist mountain — scenic bus, cable car, and a 48m gold Buddha above the clouds.",
            transportAfter: { mode: "cable-car", duration: "3 min", note: "Jinding cable car down from the summit" },
          },
          {
            id: "g-d2-wannian",
            time: "15:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Wannian Temple & Monkey Zone (optional)",
            description: "If time allows after descending from the Golden Summit, stop at Wannian Temple (built 1601) — home to a massive bronze statue of Samantabhadra on a white elephant, one of the most important Buddhist artefacts in China. The walk down through the ecological monkey zone is where you'll meet Mount Emei's famous Tibetan macaques — bold, intelligent, and will snatch anything that looks like food.",
            image: `${G}/emei-wannian-temple.webp`,
            tip: "Our tip: This is optional — only do it if you're back from the summit with at least 2 hours to spare before your return train. The monkeys are real wildlife, not a zoo — keep snacks zipped away. If you're tired, skip this and enjoy tea near Baoguo Temple instead.",
            previewImages: [`${G}/emei-wannian-temple.webp`, `${G}/emei-monkeys.jpg`, `${G}/emei-golden-summit.webp`],
            previewLine: "1601 temple with the bronze Samantabhadra, plus Mount Emei's legendary macaques.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Baoguo → Emei Mountain Station" },
          },
          {
            id: "g-d2-train-back",
            time: "18:40",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chengdu",
            subtitle: "Emei Mountain → Chengdu East · 1h 6min",
            description: "High-speed train C6264 — Mount Emei to Chengdu East, departs 18:40 and arrives 19:46. Second class (二等座) is ¥65. The journey takes 1 hour 6 minutes. We book the ticket linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Be back at Emei Mountain Station by 18:20 with tickets already loaded to your passport. The station is small but security checks can take a few minutes.",
            previewLine: "1h 6min · ¥65 (2nd class) · C6264",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi: Chengdu East Station → your hotel" },
          },
          {
            id: "g-d2-hotel",
            time: "21:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back in Chengdu",
            subtitle: "Rest up — Chongqing tomorrow",
            description: "Long day — get some rest. Tomorrow morning you'll explore Wuhou Temple and Du Fu's Thatched Cottage before your afternoon train to Chongqing.",
          },
        ],
      },

      {
        label: "Day 3",
        city: "Chengdu",
        subtitle: "May 22 (Fri) · Chengdu → Chongqing — Wuhou · Du Fu Cottage · Hongyadong",
        color: "#B45309",
        items: [
          {
            id: "g-d3-wuhou",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Wuhou Shrine",
            description: "China's only shrine where a king and his minister share the same temple — dedicated to Liu Bei and Zhuge Liang from the Three Kingdoms period (1,800 years ago). Even if you don't know the history, the red-walled bamboo corridor (Hong Qiang Zhu Ying) is one of the most photographed spots in Chengdu. The bonsai garden and ancient cypress trees are beautiful, and it's a quiet, contemplative morning activity.",
            image: `${CD}/wuhou1.jpg`,
            tip: "Our tip: ¥50 entry. The red wall bamboo path is at the back — most tourists miss it. The shrine is right next to Jinli Street if you want to quickly walk through on the way out.",
            previewImages: [`${CD}/wuhou1.jpg`, `${CD}/wuhou2.jpg`, `${CD}/wuhou3.jpg`],
            previewLine: "1,800-year-old Three Kingdoms shrine with the famous red-wall bamboo path.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Du Fu's Thatched Cottage" },
          },
          {
            id: "g-d3-dufu",
            time: "10:45",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Du Fu's Thatched Cottage",
            description: "A 300-acre garden museum on the site where Du Fu — China's greatest poet — wrote 240 of his masterpieces during four years of exile. The reconstructed thatched cottage is surrounded by bamboo groves, lotus ponds, and winding paths. It's a peaceful, contemplative space and one of the most beautiful gardens in Chengdu. The perfect quiet morning before a travel afternoon.",
            image: `${CD}/dufu1.jpg`,
            tip: "Our tip: ¥50 entry. The museum has good English explanations of Du Fu's poetry. The bamboo grove behind the main cottage is the most peaceful part. Budget about 1–1.5 hours.",
            previewImages: [`${CD}/dufu1.jpg`, `${CD}/dufu2.jpg`, `${CD}/dufu3.jpg`],
            previewLine: "Where China's greatest poet wrote 240 masterpieces — bamboo groves and lotus ponds.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Chengdu East Station" },
          },
          {
            id: "g-d3-train",
            time: "14:30",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chongqing",
            subtitle: "Chengdu East → Chongqing North · ~1.5 hours",
            description: "The Chengdu–Chongqing high-speed rail is one of the busiest in China. Second class is comfortable — wide seats, power outlets, and plenty of legroom. The 300km journey takes about 1.5 hours through the Sichuan Basin. We book the tickets linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Second class (二等座) is perfectly fine — no need to upgrade. ¥150–200 one way. We book the e-ticket linked to your passport number, so you just tap your passport at the gate. No paper ticket needed.",
            previewLine: "~1.5 hrs · ¥150–200 (2nd class) · Multiple departures",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi from Chongqing North to your hotel" },
          },
          {
            id: "g-d3-checkin",
            time: "17:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Near Jiefangbei",
            subtitle: "Drop bags, relax, freshen up",
            description: "Arrive in Chongqing and check in at your hotel near Jiefangbei — the city's main pedestrian square and the heart of the downtown core. You're walking distance from Hongyadong, the Yangtze Cableway, and most of the iconic Chongqing night spots. Relax for an hour before heading out for the evening.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk from Jiefangbei to Hongyadong" },
          },
          {
            id: "g-d3-hongyadong",
            time: "19:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Hongyadong at Night",
            description: "An 11-storey stilted building complex built into the riverside cliff face — enter from the top (street level) and descend through restaurants, shops, and walkways to the river at the bottom. After dark, the golden lights turn it into what the internet calls 'the real-life Spirited Away.' The view from across the river on Qianximen Bridge is the money shot.",
            image: `${CQ}/hongyadong1.jpg`,
            tip: "Our tip: Go after 8 PM when all the lights are on. Enter from level 11 (Cangbai Road) and walk down. For the best photo, cross to the opposite riverbank or shoot from the bridge.",
            previewImages: [`${CQ}/hongyadong1.jpg`, `${CQ}/hongyadong2.jpg`, `${CQ}/hongyadong3.jpg`],
            previewLine: "11-storey cliff building lit up gold — the real-life Spirited Away.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Grab street food nearby or walk back" },
          },
        ],
      },

      /* ═══════════════════════════════════════════
         CHONGQING · May 22–25
         ═══════════════════════════════════════════ */
      {
        label: "Day 4",
        city: "Chongqing",
        subtitle: "May 23 · Chongqing — Wulong Day Trip · Three Natural Bridges",
        color: "#D0021B",
        items: [
          {
            id: "g-d4-depart",
            time: "07:00",
            icon: Bus,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Shuttle Bus to Wulong",
            subtitle: "2.5-hour ride south-east to the karst region",
            description: "Tour shuttle bus from central Chongqing to Wulong Karst National Geology Park — about 170km, 2.5 hours on the expressway. This is a full day trip — you'll be back in the city by early evening. We pre-book your seat and the park combo ticket so you skip the queues at the entrance.",
            tip: "Our tip: Grab breakfast from your hotel before the early start. The ride is scenic once you leave the city — mountains and river gorges. Bring water and snacks for the journey.",
            previewLine: "2.5 hrs · Shuttle bus · ~170 km expressway",
            transportAfter: { mode: "shuttle", duration: "2.5 hrs", note: "Shuttle bus: Chongqing → Wulong Karst entrance" },
          },
          {
            id: "g-d4-bridges",
            time: "10:00",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Natural Bridges",
            description: "Three colossal natural limestone bridges spanning a deep gorge — Tianlong (Heaven Dragon), Qinglong (Azure Dragon), and Heilong (Black Dragon). The tallest is 235 metres high and 150 metres wide. You descend 400 steps into the gorge and walk through the canyon beneath all three bridges. Halfway through is the Tianfu Inn — a traditional building used as a filming location in Transformers: Age of Extinction. The scale is hard to describe until you're standing under millions of tonnes of rock arching above you.",
            image: `${G}/wulong-three-bridges.jpg`,
            tip: "Our tip: Take the glass-floor elevator down to the gorge floor (¥15) instead of the stairs — saves your knees for the 3km walk through the canyon. The whole route takes 2–3 hours. Bring water.",
            previewImages: [`${G}/wulong-three-bridges.jpg`, `${G}/wulong-tianfu-inn.jpg`, `${G}/wulong-longshui-gorge.webp`],
            previewLine: "Three colossal limestone bridges, a 400-step descent, and the Transformers 4 filming location.",
            transportAfter: { mode: "shuttle", duration: "15 min", note: "Park shuttle to Longshui Gorge" },
          },
          {
            id: "g-d4-gorge",
            time: "12:00",
            icon: Navigation,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Longshui Gorge Earth Crack",
            description: "A narrow 5km karst fissure carved by water over millions of years — you walk along a boardwalk inside the crack, with sheer rock walls rising 200+ metres on either side, sometimes narrowing to just a few metres apart. There are waterfalls, underground streams, and the lighting makes it atmospheric. It's included in the Wulong combo ticket and takes about 1–1.5 hours.",
            image: `${G}/wulong-longshui-gorge.webp`,
            tip: "Our tip: This is included in the combo ticket with Three Natural Bridges. It's cooler inside the gorge — bring a light layer. The boardwalk can be slippery, so wear grippy shoes.",
            previewImages: [`${G}/wulong-longshui-gorge.webp`, `${G}/wulong-longshui-02.jpg`, `${G}/wulong-longshui-03.jpg`],
            previewLine: "A 5km karst fissure — sheer 200m walls, waterfalls, and a boardwalk inside the crack.",
            transportAfter: { mode: "car", duration: "2 hrs", note: "Drive back to Chongqing city" },
          },
          {
            id: "g-d4-drone",
            time: "20:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Chongqing Drone Light Show",
            description: "Chongqing runs periodic drone light shows over the Yangtze/Jialing river junction — hundreds of drones forming shapes and patterns against the night skyline. Free to watch from various riverside viewpoints. The combination of the drone show with Chongqing's already-insane neon skyline is unique.",
            tip: "Our tip: We'll confirm the exact schedule closer to your dates — these shows run on specific nights and the schedule changes. Best viewing spots are Qianximen Bridge area or the Nanbin Road riverfront. If the drone show isn't running on the 23rd, the Chongqing night skyline from Nanshan is just as spectacular.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d4-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — city day tomorrow",
            description: "Long day — you've earned the rest. Tomorrow is Chongqing city highlights and the 《Chongqing 1949》 evening show.",
          },
        ],
      },

      {
        label: "Day 5",
        city: "Chongqing",
        subtitle: "May 24 · Chongqing — Ciqikou · Qingyu Yan Banquet · Cableway",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d5-ciqikou",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Ciqikou Ancient Town",
            description: "A thousand-year-old town built on a hillside along the Jialing River. Narrow stone-paved lanes wind between old wooden buildings — tea houses, Sichuan snack stalls, and shops selling handmade crafts. Try the famous Ciqikou mahua (twisted fried dough) and Chen Mahua which has been making it here for generations.",
            image: `${CQ}/ciqikou1.jpg`,
            tip: "Our tip: Go in the morning before 11 AM — the main street gets very crowded by noon. The side alleys are quieter and more interesting. Free entry.",
            previewImages: [`${CQ}/ciqikou1.jpg`, `${CQ}/ciqikou2.jpg`, `${CQ}/ciqikou3.jpg`],
            previewLine: "1,000-year-old hillside town — stone lanes, tea houses, and twisted fried dough.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi to the Qingyu Yan banquet hall" },
          },
          {
            id: "g-d5-qingyu",
            time: "12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "activity",
            title: "Qingyu Yan Banquet — Themed Lunch",
            description: "An immersive Chinese-style banquet where each course is plated as a tableau — painted porcelain, carved vegetables, lacquered serving boxes, and staff in traditional dress serving you in a private themed room. It's the same slow, theatrical eating culture that drives the 1949 dinner show, but at lunchtime and without the drama of a full show — just the food, the craft, and the setting. Expect 8–12 small courses spanning cold dishes, hot wok plates, soup, seasonal vegetables, and a final sweet. Good palate-cleanser between Ciqikou snacks and the evening's neon skyline.",
            image: `${CQ}/qingyu-yan-1.jpg`,
            tip: "Our tip: The banquet runs about 90 minutes — don't rush. Tell us in advance if you want mild spice, as the kitchen can dial down the Sichuan heat. We book a private room and handle the menu selection.",
            previewImages: [`${CQ}/qingyu-yan-1.jpg`, `${CQ}/qingyu-yan-2.jpg`, `${CQ}/qingyu-yan-3.jpg`],
            previewLine: "A multi-course Chinese banquet plated like artwork — 90 minutes in a private themed room.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Liziba monorail" },
          },
          {
            id: "g-d5-liziba",
            time: "14:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Liziba Monorail & Jiefangbei",
            description: "Watch Line 2 of the Chongqing monorail punch straight through an apartment building at Liziba station — the most viral transport video in China. Then walk to Jiefangbei, Chongqing's main pedestrian square, where the liberation monument is surrounded by skyscrapers and massive LED screens.",
            image: `${CQ}/liziba1.jpg`,
            tip: "Our tip: The best viewing spot for the monorail is from the street below the building. Free — just show up and wait for the next train. Jiefangbei is a 10-minute walk from there.",
            previewImages: [`${CQ}/liziba1.jpg`, `${CQ}/liziba2.jpg`, `${CQ}/jiefangbei1.jpg`],
            previewLine: "A monorail through an apartment building — Chongqing's most viral moment.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the Yangtze Cableway station" },
          },
          {
            id: "g-d5-cableway",
            time: "16:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Yangtze River Cableway",
            description: "The only urban passenger cableway still operating over the Yangtze River. A 5-minute ride in a retro cabin 300 metres above the water, with the entire Chongqing skyline and river spread out below you. It's been running since 1987 and was originally built as public transport — now it's the city's most iconic experience.",
            image: `${CQ}/cableway1.jpg`,
            tip: "Our tip: Take it from the Xinhua Road station (north side) for the best skyline views. ¥30 return. Queues can be 30-60 minutes — we can advise on timing to avoid the worst.",
            previewImages: [`${CQ}/cableway1.jpg`, `${CQ}/cableway2.jpg`, `${CQ}/cableway3.jpg`],
            previewLine: "Retro cable car 300m above the Yangtze — Chongqing's most iconic ride.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Dinner near Shapingba, then taxi to the 《Chongqing 1949》 show venue" },
          },
          {
            id: "g-d5-1949",
            time: "19:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "《Chongqing 1949》 Live Show",
            subtitle: "75-minute immersive performance · No. 7 night attraction in Chongqing",
            description: "A purpose-built immersive theatre on Jinbizheng Street where the audience walks through elaborately recreated 1940s streetscapes (tea houses, newspaper offices, dance halls) while actors stage scenes from the pivotal year when Chongqing was the last Nationalist capital before the Communist revolution. Rotating platforms, projection walls, and pyrotechnics turn the whole venue into the set. Set times: 14:00, 16:00, or 19:30 — each show runs 75 minutes, no dinner included.",
            image: `${CQ}/cq1949-01.png`,
            tip: "Our tip: Eat dinner *before* the show — there's no food inside. Plenty of local restaurants around Shapingba, or a quick Chongqing hotpot before the 19:30 slot works well. We handle the booking and can request English-friendly seating; tickets sell out fast.",
            previewImages: [`${CQ}/cq1949-01.png`, `${CQ}/cq1949-02.png`, `${CQ}/cq1949-03.jpg`],
            previewLine: "4.7/5 from 3,335 reviews · 75-minute immersive performance on Jinbizheng Street.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d5-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — Zhangjiajie tomorrow",
            description: "Your last night in Chongqing. Pack up — tomorrow you take the high-speed train to Zhangjiajie.",
          },
        ],
      },

      {
        label: "Day 6",
        city: "Chongqing",
        subtitle: "May 25 · Chongqing → Zhangjiajie — Travel Day",
        color: "#B45309",
        items: [
          {
            id: "g-d6-museum",
            time: "09:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Gorges Museum & People's Great Hall",
            description: "A free, world-class museum covering the Three Gorges region, the Three Gorges Dam project, ancient Ba culture, and wartime Chongqing (the city was China's WWII capital after the Nationalists fled Nanjing). The WWII bombing exhibition is particularly powerful — Chongqing was bombed for 5 years straight by Japanese forces, the longest continuous bombing of any city in history. The museum sits across a grand square from the People's Great Hall, a Soviet-influenced auditorium modelled on Beijing's Temple of Heaven that's one of Chongqing's most photographed buildings.",
            image: `${G}/museum-three-gorges.jpg`,
            tip: "Our tip: Free entry with your passport — bring it. Budget 1.5 hours inside. The WWII section and the Three Gorges environmental exhibition are the highlights. Walk across the square afterwards for a photo of the People's Great Hall — you can't go inside but the exterior is the iconic shot.",
            previewImages: [`${G}/museum-three-gorges.jpg`, `${G}/museum-wartime.jpg`, `${G}/museum-ancient-ba.png`],
            previewLine: "Free museum — WWII history, Three Gorges Dam, and ancient Ba culture.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Kuixing Building" },
          },
          {
            id: "g-d6-kuixing",
            time: "11:00",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Kuixing Building",
            description: "Chongqing's most famous '8D city' moment. You walk into what looks like the ground floor of a building and realise you're actually on the 22nd floor above another tower built further down the hillside. A sky bridge suspended 22 storeys high connects the two — one end is at street level, the other is a skyscraper viewpoint. Named after Kuixing, the Taoist deity of literature and examinations, with a small traditional temple perched at the top. This is the spot that captures exactly why Chongqing is called the world's most vertical city — gravity feels optional here, every staircase leads to a different story, and the cyberpunk energy is real.",
            image: `${G}/kuixing-01.jpg`,
            tip: "Our tip: Free to visit, about 30–45 minutes is enough. Easy to miss — it looks like a normal office building from the street, so use the Gaode map pin we'll send you. The sky bridge is the money shot; walk across it both ways. Best before 11 AM or after 3 PM to avoid the social-media crowds.",
            previewImages: [`${G}/kuixing-01.jpg`, `${G}/kuixing-02.webp`, `${G}/kuixing-03.jpg`],
            previewLine: "Chongqing's most famous 8D-city moment — a sky bridge between two buildings where one end is the street and the other is 22 floors up.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Chongqing East Station" },
          },
          {
            id: "g-d6-train",
            time: "13:00",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Zhangjiajie",
            subtitle: "Chongqing East → Zhangjiajie West · ~2–3 hours",
            description: "The Chongqing–Zhangjiajie high-speed line opened in 2025 — what used to be a 5+ hour journey is now just 2–3 hours. The route cuts through dramatic karst landscapes in Hubei province. You'll arrive at Zhangjiajie West station, where your transfer is waiting.",
            tip: "Our tip: Second class is fine. ~¥200–250 one way. Same passport-scan boarding as the Chengdu train. The scenery through the window is worth staying awake for — tunnels and bridges through karst mountains.",
            previewLine: "~2–3 hrs · ¥200–250 (2nd class) · Opened 2025",
            transportAfter: { mode: "car", duration: "45 min", note: "Pre-arranged transfer to Wulingyuan" },
          },
          {
            id: "g-d6-arrive",
            time: "16:30",
            icon: MapPin,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Arrive Wulingyuan",
            description: "Your hotel is in the Wulingyuan area — the gateway town right next to Zhangjiajie National Forest Park. This is where you'll stay for 4 nights while you explore the park, Grand Canyon, and caves. The town has restaurants, shops, and the XiBu Street night market along the river.",
            tip: "Our tip: Tonight is free — walk XiBu Street along the river for a preview of the town. It's lit up at night with bars and food stalls. Mugwort cakes (艾草粑粑) are the local snack to try.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to hotel" },
          },
          {
            id: "g-d6-hotel",
            time: "17:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Wulingyuan",
            subtitle: "Rest up — Forest Park tomorrow",
            description: "Get settled and rest. Tomorrow is the big one — Zhangjiajie National Forest Park, the Bailong Elevator, and the Avatar mountains.",
          },
        ],
      },

      /* ═══════════════════════════════════════════
         ZHANGJIAJIE · May 25–31
         ═══════════════════════════════════════════ */
      {
        label: "Day 7",
        city: "Zhangjiajie",
        subtitle: "May 26 · Forest Park Mountain Core — Yuanjiajie · Yangjiajie · Tianzishan",
        color: "#D0021B",
        items: [
          {
            id: "g-d7-bailong",
            time: "07:30",
            icon: Navigation,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "East Gate → Bailong Sky Elevator",
            subtitle: "Enter Zhangjiajie National Forest Park · 1 ticket covers 2 days",
            description: "Walk from your Wulingyuan hotel to the East Gate (Biaozhimen) for an early entry before the tour groups. Your Zhangjiajie National Forest Park ticket is a single multi-entry pass (~¥228, valid 4 days) that covers every section you'll visit across today and tomorrow — Yuanjiajie, Yangjiajie, Tianzishan, Jinbian Stream, and Huangshizhai all included. Take the free official park shuttle to the base of the Bailong Elevator, then ride 326m up the cliff face in glass capsules — the tallest outdoor lift in the world, ~2 minutes to the top. Only use the official park shuttles inside the park; never take unlicensed cars.",
            tip: "Our tip: One ticket, two days, all inside the same park — so today's Yuanjiajie/Yangjiajie/Tianzishan and tomorrow's Jinbian Stream/Huangshizhai are all covered. The Bailong Elevator and cable cars are *separate* paid rides; we bundle everything into one combo pass so you're not queueing at each node. Entering by 08:00 is the difference between a 5-minute elevator queue and a 45-minute one.",
            image: `${ZJJI}/bailong-elevator.webp`,
            previewImages: [`${ZJJI}/bailong-elevator.webp`],
            previewLine: "Early entry · free park shuttle · 326m vertical in ~2 min",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk from Bailong top station to Yuanjiajie ridge" },
          },
          {
            id: "g-d7-yuanjiajie",
            time: "09:00",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Zhangjiajie National Forest Park",
            description: "The ridge that inspired the floating mountains in Avatar. Walk between the main viewpoints — Mihun Terrace (the classic wide shot), Avatar Hallelujah Mountain (the iconic pillar), and First Bridge Under Heaven (a natural stone arch 357m above the valley). Hidden spot: Houhuayuan (Back Garden) — quiet, misty, just a short detour from the main loop and missed by most tour groups. Great for photos without a crowd.",
            image: `${ZJJI}/yuanjiajie-hallelujah.jpg`,
            tip: "Our tip: The core loop here takes about 2.5 hours including Houhuayuan. Staff won't push you towards the hidden spots — we mark them on the offline map we send you.",
            previewImages: [`${ZJJI}/yuanjiajie-hallelujah.jpg`, `${ZJJI}/yuanjiajie-first-bridge.jpg`, `${ZJJI}/yuanjiajie-mihun-terrace.jpg`],
            previewLine: "Hallelujah Mountain, First Bridge Under Heaven, and the quiet Houhuayuan hidden spot.",
            transportAfter: { mode: "shuttle", duration: "30 min", note: "Free park shuttle: Yuanjiajie → Yangjiajie" },
          },
          {
            id: "g-d7-yangjiajie",
            time: "12:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Yangjiajie — Natural Great Wall",
            description: "The section of the park most tour groups skip — and the reason to come. A series of knife-edge peak walls that look like a ruined stone fortress, with walkways along the ridge. Fewer people, wilder feel, and some of the best panoramic shots in the whole park. About 1.5 hours for the main loop.",
            image: `${ZJJI}/yangjiajie.jpg`,
            tip: "Our tip: Bring a proper snack — there are few food options on this ridge. The wind picks up at the Natural Great Wall viewpoint, so a light layer helps.",
            previewImages: [`${ZJJI}/yangjiajie.jpg`, `${ZJJI}/yangjiajie-02.jpg`, `${ZJJI}/yangjiajie-03.jpg`],
            previewLine: "A stone-fortress ridge walk — the park's quietest panoramas.",
            transportAfter: { mode: "shuttle", duration: "30 min", note: "Free park shuttle: Yangjiajie → Tianzishan" },
          },
          {
            id: "g-d7-tianzi",
            time: "14:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Tianzishan — Yubi Peak & Goddess Scattering Flowers",
            description: "The highest viewpoint area in Wulingyuan. Walk between Yubi Peak (the 'Imperial Writing Brush' — three thin pillars topped with trees, one of China's most-photographed natural landmarks) and Goddess Scattering Flowers for the horizon-filling panorama of pillars. Hidden spots: Shentang Bay and Dianjiangtai — both signed, both almost empty, and arguably the best viewpoints on the entire ridge.",
            image: `${ZJJI}/tianzi-mountain.png`,
            tip: "Our tip: Save 2.5 hours for this section — Shentang Bay alone is worth 30 minutes. The Tianzi Cable Car down is safer than hiking down at the end of a long day.",
            previewImages: [`${ZJJI}/tianzi-mountain.png`, `${ZJJI}/tianzi-02.jpg`, `${ZJJI}/tianzi-03.jpg`],
            previewLine: "Imperial Writing Brush, Goddess Scattering Flowers, and the quiet Shentang Bay & Dianjiangtai.",
            transportAfter: { mode: "cable-car", duration: "10 min", note: "Tianzi Cable Car down, then shuttle to East Gate" },
          },
          {
            id: "g-d7-hotel",
            time: "18:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — valley day tomorrow",
            description: "Back in Wulingyuan before dark. Tomorrow is a gentler pace — the valley loop (Jinbian Stream + Huangshizhai) and the Charming Xiangxi show in the evening.",
          },
        ],
      },

      {
        label: "Day 8",
        city: "Zhangjiajie",
        subtitle: "May 27 · Forest Park Valley Loop — Jinbian Stream · Huangshizhai · Evening Show",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d8-jinbian",
            time: "08:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Jinbian (Golden Whip) Stream Hike",
            description: "Enter the East Gate and take the shuttle to Water Around Four Gates (Shuirao Simen), the trailhead for the Jinbian Stream valley walk. A flat, shaded 5.5km route along turquoise water at the bottom of the sandstone canyon — towering pillars on both sides, waterfalls, and wild macaques. Key stops: Water Around Four Gates → Qianli Xianghui → Big Oxygen Bar Square. Hidden section: the quieter upstream trail past the main crowds has clearer water and fewer monkeys.",
            image: `${ZJJI}/jinbian-rock.jpg`,
            tip: "Our tip: Keep snacks in a zipped bag — the monkeys here are aggressive food thieves. Don't hold plastic bags or make eye contact. We'll flag which exit to use for the Huangshizhai transfer.",
            previewImages: [`${ZJJI}/jinbian-rock.jpg`, `${ZJJI}/jinbian-monkey.webp`, `${ZJJI}/jinbian-journey-west.png`],
            previewLine: "Turquoise stream, towering cliffs, and a quieter upstream hidden trail.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Rest at Big Oxygen Bar Square, then cable car up to Huangshizhai" },
          },
          {
            id: "g-d8-huangshi",
            time: "12:00",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Huangshizhai Round Trail",
            description: "A sky-island plateau 1,200m up, reached by cable car, with the single widest panorama in the whole park. The main loop takes 2–2.5 hours and circles past six major viewing platforms. Hidden spot: Qianhuayuan (Front Garden) — a less-crowded viewpoint with the same wide views as the main platforms but without the queues. Locals say you 'haven't really seen Zhangjiajie' until you've been up here.",
            image: `${ZJJI}/huangshizhai-01.jpg`,
            tip: "Our tip: Take the cable car up (¥65) to save your legs after the morning hike. The loop is one-way — follow the signed direction and don't backtrack.",
            previewImages: [`${ZJJI}/huangshizhai-01.jpg`, `${ZJJI}/huangshizhai-02.jpg`, `${ZJJI}/huangshizhai-03.jpg`],
            previewLine: "Sky-island plateau with the park's widest panorama — plus the quiet Qianhuayuan hidden spot.",
            transportAfter: { mode: "shuttle", duration: "30 min", note: "Cable car down, then park shuttle back to East Gate" },
          },
          {
            id: "g-d8-show",
            time: "20:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Charming Xiangxi Show",
            description: "A massive outdoor live performance with 500+ performers — real waterfalls on stage, fire, traditional Tujia and Miao ethnic culture, and dramatic lighting against the mountains. It tells the story of western Hunan's history through music, dance, and theatre. One of the most impressive live shows in China.",
            image: "/uploads/itinerary/xiangxi_show.jpg",
            tip: "Our tip: Tickets sell out and need to be booked in advance through Chinese-only platforms. The show is about 90 minutes — bring a light jacket for the open-air theatre. We handle the booking.",
            previewImages: ["/uploads/itinerary/xiangxi_show.jpg", SHOW_STAGE, "/uploads/itinerary/tujia_silk3.jpeg"],
            previewLine: "500+ performers, real waterfalls on stage, fire, and Tujia & Miao culture.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi back to hotel" },
          },
          {
            id: "g-d8-hotel",
            time: "22:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Grand Canyon tomorrow",
            description: "Great day. Tomorrow is the Zhangjiajie Grand Canyon and the famous Glass Bridge.",
          },
        ],
      },

      {
        label: "Day 9",
        city: "Zhangjiajie",
        subtitle: "May 28 · Grand Canyon B-Line — Glass Bridge · Canyon · Shenquan Lake Boat",
        color: "#B45309",
        items: [
          {
            id: "g-d9-transfer",
            time: "07:30",
            icon: Bus,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Shuttle to Grand Canyon — East Gate",
            subtitle: "Wulingyuan Bus Station → Canyon East Gate · ~40 min",
            description: "Shuttle bus from Wulingyuan Bus Station down to the Grand Canyon. We enter via the East Gate — most tour groups use the West Gate, so the East side stays quieter all morning and puts you at the Glass Bridge first.",
            tip: "Our tip: Arriving before 08:30 gets you on an almost-empty Glass Bridge — prime photo window.",
            previewLine: "~40 min shuttle · East Gate entry avoids the tour bus crowds",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the Yunduan Glass Bridge entrance" },
          },
          {
            id: "g-d9-glass",
            time: "08:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Yunduan Glass Bridge",
            description: "The world's longest and highest glass-bottomed bridge — 430 metres long, suspended 300 metres above the canyon floor. Walking it first thing means you'll catch the heart-shaped platform with almost no one on it. Shoe covers provided; no bags, selfie sticks, or loose items — free lockers at the entrance.",
            image: `${ZJJI}/glass-bridge-yuntian.webp`,
            tip: "Our tip: The heart-shaped photo platform on the bridge is clearest before 09:00. If you want to bungee off the bridge (the world's highest commercial bungee at 260m), we can book it — let us know in advance.",
            previewImages: [`${ZJJI}/glass-bridge-yuntian.webp`, `${ZJJI}/canyon-bungee.png`, `${ZJJI}/canyon-glass-01.jpg`],
            previewLine: "430m long, 300m high — first in before the crowds arrive.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the canyon descent trailhead" },
          },
          {
            id: "g-d9-descent",
            time: "09:40",
            icon: Footprints,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Canyon Descent",
            description: "Stairs down into the gorge from the Glass Bridge level to the canyon floor. At roughly the halfway mark the Treasure Hunting Elevator (寻宝电梯, ¥30) lets you skip the steepest staircase — worth it to save your legs for the afternoon. Takes about 1h 50min from bridge to canyon floor.",
            image: `${ZJJI}/canyon-hike.png`,
            tip: "Our tip: Take the Treasure Hunting Elevator. The walking alternative adds 40 minutes on punishing stairs and you'll feel it in your knees by Tianmen Mountain.",
            previewImages: [`${ZJJI}/canyon-hike.png`, `${ZJJI}/canyon-02.jpg`, `${ZJJI}/canyon-03.jpg`],
            previewLine: "Stair descent to the canyon floor · ¥30 elevator saves your legs.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the canyon-floor food square" },
          },
          {
            id: "g-d9-lunch",
            time: "11:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "activity",
            title: "Lunch at the Canyon Square",
            description: "A casual lunch break at the canyon-floor food square. Simple noodle shops and Hunan rice bowls — nothing fancy, but fuelling. Packed snacks from town are also a valid option if you want to save money and time.",
            tip: "Our tip: Prices at the canyon square are ~1.5× town prices. A quick bowl of beef noodles is fine; skip the tourist set menus.",
            previewLine: "Quick fuel stop · noodles or your own snacks",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the Middle Canyon trail" },
          },
          {
            id: "g-d9-middle",
            time: "12:30",
            icon: Footprints,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Middle Canyon Hike — First-Line Sky",
            description: "The canyon-floor section: walk through First-Line Sky (一线天, a narrow slot in the cliff where only a thin strip of sky is visible overhead) and along quiet valley paths with the river beside you. Mostly downhill and shaded — the easiest stretch of the day. Optional paid thrill: the Sky Ladder slide or a zipline at First-Line Sky (30–90kg weight limit) if you want a jolt.",
            image: `${ZJJI}/canyon-04.jpg`,
            previewImages: [`${ZJJI}/canyon-04.jpg`],
            previewLine: "First-Line Sky slot canyon and quiet valley walks — mostly downhill.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Rainbow Waterfall" },
          },
          {
            id: "g-d9-rainbow",
            time: "14:00",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Rainbow Waterfall & Hidden Waterfalls",
            description: "Peak rainbow window: 14:00–16:00 is when the sun angle through the spray creates the rainbow arc at Rainbow Waterfall. Continuing along the path you pass Magic Curtain Waterfall and God Turtle Pool — both quiet spots most day-trippers miss.",
            image: `${ZJJI}/waterfall.jpg`,
            tip: "Our tip: Wear bright or light colours — you'll photograph much better against the waterfall spray. Non-slip shoes essential: the path gets misty.",
            previewImages: [`${ZJJI}/waterfall.jpg`],
            previewLine: "Rainbow window 14:00–16:00 · Magic Curtain & God Turtle Pool hidden stops.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to Shenquan Lake boat dock" },
          },
          {
            id: "g-d9-boat",
            time: "15:30",
            icon: Navigation,
            iconBg: "#E3F2FD",
            type: "activity",
            title: "Shenquan Lake Boardwalk & Boat Ride",
            description: "Walk the quiet lakeside boardwalk to the boat dock, then take the included Shenquan Lake cruise — a calm finale after the descent. Front-row seats get the best cliff views. The boat lands at the exit shuttle stop, so there's no backtrack.",
            image: `${ZJJI}/lake-boat.jpg`,
            tip: "Our tip: Grab a front-row seat on the boat — the best cliff reflections are off the bow. The boat ticket is included in your B-Line combo.",
            previewImages: [`${ZJJI}/lake-boat.jpg`],
            previewLine: "Lakeside boardwalk + boat cruise · front row for the cliff reflections.",
            transportAfter: { mode: "shuttle", duration: "30 min", note: "Shuttle from boat dock → exit, then bus back to Wulingyuan" },
          },
          {
            id: "g-d9-hotel",
            time: "18:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest — caves and city transfer tomorrow",
            description: "Back in Wulingyuan by early evening. Tomorrow morning is Yellow Dragon Cave, then you transfer to your new hotel in Zhangjiajie city for the final stretch of the trip.",
          },
        ],
      },

      {
        label: "Day 10",
        city: "Zhangjiajie",
        subtitle: "May 29 · Zhangjiajie — Yellow Dragon Cave · Transfer to City · 72 Tower",
        color: "#D0021B",
        items: [
          {
            id: "g-d10-cave",
            time: "08:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Yellow Dragon Cave",
            description: "One of China's most spectacular show caves — a vast underground karst system with a river running through it. You walk through massive chambers filled with stalactites, stalagmites, and flowstone formations lit with coloured lights. The highlight is the 'Dinghai Shenzhen' — a single 19.2-metre stalagmite that's been insured for ¥100 million. There's also an underground boat ride along the subterranean river.",
            image: `${ZJJI}/cave-dragon-hall.png`,
            tip: "Our tip: The cave tour takes about 2 hours and includes the boat ride. It's a constant 16°C inside — bring a light jacket even in summer. ¥100 entry. We pre-book tickets.",
            previewImages: [`${ZJJI}/cave-dragon-hall.png`, `${ZJJI}/cave-stalagmite.webp`, `${ZJJI}/cave-river.jpg`],
            previewLine: "Vast underground chambers, a 19m stalagmite insured for ¥100 million, and a river boat ride.",
            transportAfter: { mode: "car", duration: "45 min", note: "Transfer to your new Zhangjiajie city hotel" },
          },
          {
            id: "g-d10-checkin",
            time: "14:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Zhangjiajie City",
            subtitle: "New hotel for the final 2 nights",
            description: "You're now in Zhangjiajie city itself (about 45 minutes from Wulingyuan). This is the base for Tianmen Mountain and the 72 Qilou Tower — both are in or near the city centre. Take the afternoon to rest, grab lunch, and explore the area on your own before the evening visit to 72 Qilou.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to 72 Qilou (evening)" },
          },
          {
            id: "g-d10-72tower",
            time: "19:00",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "72 Qilou Tower",
            description: "A striking 12-storey tower complex built into the cliffside in traditional Tujia and Miao architectural style — it looks like something out of a fantasy film. The tower combines ethnic minority cultural exhibits, restaurants, shops, and observation decks with views over the city and surrounding mountains. The rooftop terrace gives panoramic views, especially at sunset.",
            image: `${G}/72-tower-01.png`,
            tip: "Our tip: Come in the late afternoon for the best light. The tower is especially photogenic from the outside — the stacked traditional architecture against the mountain backdrop. It's free to walk around the exterior; some interior sections have small entry fees.",
            previewImages: [`${G}/72-tower-01.png`, `${G}/72-tower-02.jpg`, `${G}/72-tower-03.jpg`],
            previewLine: "12-storey Tujia-style tower built into the cliffside — Zhangjiajie's architectural icon.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi back to your hotel" },
          },
          {
            id: "g-d10-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Tianmen Mountain tomorrow",
            description: "Get a good sleep — tomorrow is Tianmen Mountain, one of the most dramatic mountain experiences in China. Early start for the cable car.",
          },
        ],
      },

      {
        label: "Day 11",
        city: "Zhangjiajie",
        subtitle: "May 30 · Zhangjiajie — Tianmen Mountain · Glass Skywalks · 999 Steps",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d11-cable",
            time: "08:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Tianmen Mountain Cable Car",
            description: "The world's longest passenger cableway — 7,455 metres from the city centre straight up to the Tianmen Mountain summit at 1,518m. The 28-minute ride takes you from street level over the city, through the foothills, and into the clouds. The steepest section climbs at a 37-degree angle. On a clear day you can see the entire Zhangjiajie basin below.",
            image: "/uploads/itinerary/tianmen_cable1.jpg",
            tip: "Our tip: Book the earliest time slot (8:00 AM) to avoid queues and get the clearest weather. Sit on the right side going up for the best mountain views. Bring a warm jacket — the summit is 10-15°C colder than the city.",
            previewImages: ["/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "A 28-minute ride from city streets into the clouds — 7.5km of jaw-dropping scenery.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the east summit trail" },
          },
          {
            id: "g-d11-glass",
            time: "09:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Glass Skywalks",
            description: "A glass-floored walkway bolted to the sheer cliff face at 1,400m — you walk along transparent panels with a 300-metre drop below your feet and the mountain wall on one side. The east side walk is longer (60m) and more exposed than the west. Even if you're not scared of heights, looking straight down through glass at a 300m cliff is a different experience entirely.",
            tip: "Our tip: The east side glass walk is longer and more dramatic than the west. You need shoe covers (¥5, bought on-site). Even people without fear of heights find their knees going weak — it's genuinely thrilling.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the escalator entrance" },
          },
          {
            id: "g-d11-cave",
            time: "13:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Heaven's Gate (Tianmen Cave) & 999 Steps",
            description: "Tianmen Cave is a natural hole punched through the mountain — 131 metres high, 57 metres wide, visible from the city below. To reach it you descend the famous 999 steps (the 'Stairway to Heaven'), a near-vertical stone staircase clinging to the cliff face. The number 999 represents 'heaven' in Chinese numerology. Standing inside the cave with clouds drifting through and the valley visible far below is one of those moments you don't forget.",
            tip: "Our tip: Take it slow on the steep upper sections and use the railings — the steps are uneven. The cave itself is most dramatic when clouds drift through it, which happens most mornings.",
            previewImages: ["/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "131m-high natural cave, 999 steps, and the feeling of descending from heaven.",
            transportAfter: { mode: "shuttle", duration: "25 min", note: "Coach down the 99-bend road" },
          },
          {
            id: "g-d11-99bend",
            time: "15:00",
            icon: Camera,
            iconBg: "#E3F2FD",
            type: "activity",
            title: "99-Bend Road (Tongtian Avenue)",
            description: "The coach ride down Tongtian Avenue — nearly 11 kilometres of mountain road with 99 hairpin turns switchbacking from 1,300m to 200m. The bus drivers navigate blind 180-degree turns with centimetres of clearance. It's equal parts terrifying and impressive, and the aerial views from above are spectacular.",
            tip: "Our tip: Sit on the left side for the best cliff-drop views. The ride takes about 25 minutes. If you get motion sick easily, take medication beforehand.",
            previewImages: ["/uploads/itinerary/99bend1.webp", "/uploads/itinerary/99bend2.jpeg", "/uploads/itinerary/99bend3.webp"],
            previewLine: "99 hairpin turns, 1,300m descent — the most dramatic bus ride of your life.",
          },
          {
            id: "g-d11-hotel",
            time: "21:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Last night in China — long travel day tomorrow",
            description: "Your last night. Pack everything up — tomorrow is a full travel day back to Chengdu and onward to Hanoi.",
          },
        ],
      },

      {
        label: "Day 12",
        city: "Zhangjiajie",
        subtitle: "May 31 (Sat) · Zhangjiajie → Chengdu → Hanoi",
        color: "#059669",
        items: [
          {
            id: "g-d12-train",
            time: "Early",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chongqing",
            subtitle: "Zhangjiajie West → Chongqing East · ~2–3 hours",
            description: "High-speed train from Zhangjiajie West to Chongqing East on the line that opened in 2025. Second class (二等座) is ¥244. The journey takes about 2–3 hours through dramatic karst landscapes. We book the ticket linked to your passport and time it to your onward connection.",
            tip: "Our tip: Same passport-scan boarding you've been using all trip. The scenery through the window is worth staying awake for — tunnels and bridges through karst mountains.",
            previewLine: "~2–3 hrs · ¥244 (2nd class) · Zhangjiajie → Chongqing",
            transportAfter: { mode: "taxi", duration: "50 min", note: "Taxi to Chengdu Tianfu International Airport" },
          },
          {
            id: "g-d12-flight",
            time: "Flight TBC",
            icon: Plane,
            iconBg: "#E8F5E9",
            type: "transport",
            title: "Flight to Hanoi",
            subtitle: "Chengdu Tianfu International → Hanoi",
            description: "Your onward flight from Chengdu Tianfu International Airport (CTU) to Hanoi. The flight itself is on your own booking — we handle everything up to the airport: the train, the transfer, and making sure you arrive with enough time to check in and clear international departure immigration.",
            tip: "Our tip: Chengdu has two airports — double-check your flight leaves from Tianfu (the newer international hub, ~60 km south-east of the city) rather than Shuangliu (the older domestic-focused airport closer to downtown). Arrive 2.5–3 hours before an international flight. Have your Vietnam visa / e-visa confirmation ready.",
            previewLine: "International departure · Arrive 2.5–3 hrs early · CTU Tianfu",
          },
        ],
      },
    ],

    picks: [
      {
        id: "g-pick-opera",
        emoji: "🎭",
        type: "Culture",
        title: "Sichuan Opera Face-Changing",
        desc: "A full Sichuan opera show in Chengdu with the famous 'face-changing' (bian lian) — performers swap painted masks in a fraction of a second. Nobody knows how.",
        meiNote: "Several theatres do this in Chengdu. We book the best one with good seats — tickets are Chinese-platform only. Could fit on the evening of Day 1 or Day 2.",
        image: `${CD}/jinli1.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "g-pick-cooking",
        emoji: "🌶️",
        type: "Food",
        title: "Sichuan Cooking Class",
        desc: "A hands-on class in Chengdu where you learn to cook mapo tofu, kung pao chicken, and dan dan noodles. Includes market visit to buy ingredients.",
        meiNote: "Half day, includes lunch — you eat everything you cook. Could replace the Day 1 afternoon if you're more into food than history.",
        image: `${CD}/wuhou1.jpg`,
        tag: "We can arrange",
        tagColor: "#059669",
      },
      {
        id: "g-pick-fenghuang",
        emoji: "🏘️",
        type: "Day Trip",
        title: "Fenghuang Ancient Town",
        desc: "A perfectly preserved riverside town with 300-year-old stilted houses, stone bridges, and lantern-lit streets — often called the most beautiful small town in China. About 3.5 hours from Zhangjiajie.",
        meiNote: "You have spare time in the Zhangjiajie stretch — we could swap one of the free afternoons for a Fenghuang day trip. It's a long day but worth it.",
        image: TIANZI,
        tag: "Day trip",
        tagColor: "#B45309",
      },
      {
        id: "g-pick-cruise",
        emoji: "🌃",
        type: "Nightlife",
        title: "Two Rivers Night Cruise — Chongqing",
        desc: "A 1-hour boat ride where the Yangtze and Jialing rivers meet — see the entire lit-up Chongqing skyline, Hongyadong, and bridges from the water.",
        meiNote: "Boats run 7-10 PM nightly in Chongqing. ¥100-200 depending on deck. Could fit on the evening of Day 3 or Day 5.",
        image: `${CQ}/hongyadong1.jpg`,
        tag: "We can book",
        tagColor: "#7C3AED",
      },
    ],
  };
}
