import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints, TrainFront, Car, MapPin } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

/* ── Image path prefixes ── */
const CD = "/uploads/itinerary/chengdu";
const CQ = "/uploads/itinerary/chongqing";
const ZJJ = "https://d2xsxph8kpxj0f.cloudfront.net/310519663383502924/dCuiiEQEkteYUXqqZRtP5i";
const G = "/uploads/itinerary/giovanni";

/* ── ZJJ CDN image shortcuts ── */
const FOREST = `${ZJJ}/zjj-forest-park-Fk6sgYY4AzscGgsTAdGZLa.webp`;
const TIANZI = `${ZJJ}/zjj-tianzi-mountain-XX5qUieAEsabKUeYk3JHxK.webp`;
const GOLDEN = `${ZJJ}/zjj-golden-whip-8i6gvipo7fjNjnMVU35ZsX.webp`;
const BAILONG = `${ZJJ}/zjj-bailong-elevator-9wBE8Ew5MeTzffXtu96bUz.webp`;
const AVATAR = `${ZJJ}/zjj-avatar-pillars-JfnwwF7VRiJvmNKdnJuoV2.webp`;
const TIANZI_CLOUDS = `${ZJJ}/zjj-tianzi-clouds-9hojziDU5h4PbieGP8mtEX.webp`;
const STREAM_CLOSE = `${ZJJ}/zjj-stream-close-hBhQpt79q4p9cSqndUf8Ww.webp`;
const HUNAN_FOOD = `${ZJJ}/zjj-hunan-food-5uvTJyHoH4ttNhNFdYfrT2.webp`;
const SHOW_STAGE = `${ZJJ}/zjj-show-stage-5vsSH7YEVUrQP8TKivY3B2.webp`;

export function buildGiovanniConfig(): ItineraryConfig {
  return {
    cityName: "China",
    title: "China Adventure",
    location: "Chengdu · Chongqing · Zhangjiajie",
    duration: "12 Days · May 20–31",
    heroImage: AVATAR,
    meiGreeting: "Giovanni — here's your trip, day by day. Every ticket, train, restaurant, and transfer is laid out below. Review it, tell us what to adjust, and we'll start booking everything.",
    departure: {
      time: "May 31 · Morning",
      title: "Zhangjiajie Airport Transfer",
      description: "We arrange a private driver from your hotel to Zhangjiajie Hehua International Airport — about 40 minutes. If you're flying out of Changsha instead, we can book the train + airport transfer too.",
    },
    departureNote: "This is your personalised itinerary — we'll refine it together. Message us to adjust anything, add activities, or start booking.",
    days: [
      /* ═══════════════════════════════════════════
         CHENGDU · May 20–22
         ═══════════════════════════════════════════ */
      {
        label: "Day 1",
        subtitle: "May 20 · Chengdu — Panda Base · Wuhou Shrine · Jinli Street",
        color: "#D0021B",
        items: [
          {
            id: "g-d1-panda",
            time: "Morning · 7:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Giant Panda Base",
            subtitle: "Morning — 244 pandas in bamboo forest",
            description: "The world's largest captive panda breeding facility — 244 giant pandas in naturalistic forest enclosures. You'll see adults lazily eating bamboo, red pandas climbing trees, and if you're lucky, the nursery with newborn cubs behind glass. The base is huge (200+ hectares) but the best enclosures are clustered together.",
            image: `${CD}/panda1.jpg`,
            tip: "Our tip: Be at the gate when it opens at 7:30 AM — pandas are most active before 10 AM and the crowds arrive by 9. Tickets (¥55) must be booked on Chinese apps days in advance. We handle it.",
            previewImages: [`${CD}/panda1.jpg`, `${CD}/panda2.jpg`, `${CD}/panda3.jpg`],
            previewLine: "244 giant pandas — adults, cubs, and red pandas in bamboo forest enclosures.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi back to the city centre" },
          },
          {
            id: "g-d1-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Sichuan food — the real deal",
            description: "Chengdu is a UNESCO City of Gastronomy. This is where you eat the best Sichuan food in the world:",
            restaurants: [
              { name: "陈麻婆豆腐", englishName: "Chen Mapo Tofu", cuisine: "Sichuan classic", note: "The original mapo tofu — founded 1862. The numbing-spicy (mala) flavour hits different at the source. A must.", price: "¥40–60 pp", rating: 4.7 },
              { name: "小龙坎火锅", englishName: "Xiaolongkan Hotpot", cuisine: "Sichuan hotpot", note: "One of Chengdu's most famous hotpot chains. Get the half-and-half pot if you can't handle full spice. The beef and tripe are excellent.", price: "¥80–120 pp", rating: 4.8 },
              { name: "严太婆锅盔", englishName: "Yan Taipo Guokui", cuisine: "Street snack", note: "Crispy stuffed flatbread — the most addictive street food in Chengdu. Spicy pork filling. ¥8 each.", price: "¥8–15 pp", rating: 4.9 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to Wuhou Shrine" },
          },
          {
            id: "g-d1-wuhou",
            time: "Afternoon · 2:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Wuhou Shrine",
            subtitle: "Afternoon — Three Kingdoms history",
            description: "China's only shrine where a king and his minister share the same temple — dedicated to Liu Bei and Zhuge Liang from the Three Kingdoms period (1,800 years ago). Even if you don't know the history, the red-walled bamboo corridor (Hong Qiang Zhu Ying) is one of the most photographed spots in Chengdu. The bonsai garden and ancient cypress trees are beautiful.",
            image: `${CD}/wuhou1.jpg`,
            tip: "Our tip: ¥50 entry. The red wall bamboo path is at the back — most tourists miss it. It connects directly to Jinli Street through the back exit, so do them together.",
            previewImages: [`${CD}/wuhou1.jpg`, `${CD}/wuhou2.jpg`, `${CD}/wuhou3.jpg`],
            previewLine: "1,800-year-old Three Kingdoms shrine with the famous red-wall bamboo path.",
            transportAfter: { mode: "walk", duration: "2 min", note: "Walk through the back gate to Jinli Street" },
          },
          {
            id: "g-d1-dinner",
            time: "Evening · 5:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Jinli Street area",
            description: "Graze through the street food on Jinli, or sit down nearby:",
            restaurants: [
              { name: "Jinli Street Food Stalls", englishName: "Jinli Street Food", cuisine: "Street snacks", note: "San da pao (sweet rice balls), bo bo ji (cold skewers), dan dan noodles, rabbit heads — just point and eat your way down the street.", price: "¥30–60 pp", rating: 4.6 },
              { name: "大妙火锅", englishName: "Da Miao Hotpot", cuisine: "Premium hotpot", note: "A more upscale hotpot with a beautiful traditional courtyard setting. The beef tallow base is intensely flavourful.", price: "¥120–160 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "1 min", note: "You're already on Jinli Street" },
          },
          {
            id: "g-d1-jinli",
            time: "Evening · 7:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Jinli Ancient Street",
            subtitle: "Evening — Lanterns and street food",
            description: "A 550-metre lantern-lit pedestrian street that CNN named one of the world's 21 most beautiful streets. Red lanterns, traditional architecture, face-changing opera performances on the outdoor stage, and Sichuan street food everywhere. It's touristy but genuinely atmospheric at night — the lanterns reflecting off the old buildings is the quintessential Chengdu photo.",
            image: `${CD}/jinli1.jpg`,
            tip: "Our tip: Come after dark when the lanterns are lit — it's completely different from daytime. The outdoor face-changing opera performances are free and happen every 30 minutes.",
            previewImages: [`${CD}/jinli1.jpg`, `${CD}/jinli2.jpg`, `${CD}/jinli3.jpg`],
            previewLine: "Red lanterns, face-changing opera, and CNN's pick for world's most beautiful streets.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d1-hotel",
            time: "Night · 9:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — big day trip tomorrow",
            description: "Get a good sleep. Day 2 is a full day trip to Leshan Giant Buddha and Mount Emei — early start.",
          },
        ],
      },

      {
        label: "Day 2",
        subtitle: "May 21 · Chengdu — Leshan Giant Buddha · Mount Emei",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d2-depart",
            time: "Early Morning · 6:30",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Private Car to Leshan",
            subtitle: "2-hour drive south from Chengdu",
            description: "Your driver picks you up from the hotel at 6:30 AM for the 130km drive to Leshan. It's about 2 hours on the expressway. We use a private car rather than the train for this day trip because it gives you the flexibility to do both Leshan and Mount Emei without being tied to train schedules.",
            tip: "Our tip: Grab breakfast from your hotel to eat in the car — you want to be at Leshan early before the crowds.",
            transportAfter: { mode: "car", duration: "2 hrs", note: "Expressway to Leshan" },
          },
          {
            id: "g-d2-leshan",
            time: "Morning · 8:30",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Leshan Giant Buddha",
            subtitle: "Morning — The world's largest stone Buddha",
            description: "A 71-metre Buddha carved into a cliff face where three rivers collide — the largest stone Buddha in the world, built over 90 years starting in 713 AD. From the top you look down at his head; from the river you see the full figure. The carving is so massive that 100 people can sit on each foot. The engineering behind the hidden drainage system (inside the hair curls and robes) has kept it standing for 1,300 years.",
            image: `${CD}/leshan1.jpg`,
            tip: "Our tip: We book the river boat cruise first (¥70, 20 min) — you get the iconic full-body view without the 2+ hour queue to walk down the cliff stairs. Then you can walk the cliff path from the top for the close-up head view.",
            previewImages: [`${CD}/leshan1.jpg`, `${G}/leshan2.jpg`, `${G}/leshan3.jpg`],
            previewLine: "71 metres tall, 1,300 years old — the world's largest stone Buddha at three rivers.",
            transportAfter: { mode: "car", duration: "40 min", note: "Drive to Mount Emei" },
          },
          {
            id: "g-d2-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near Leshan / on the way to Emei",
            description: "Eat near Leshan before heading to Mount Emei:",
            restaurants: [
              { name: "叶婆婆钵钵鸡", englishName: "Ye Popo Bo Bo Ji", cuisine: "Leshan cold skewers", note: "Leshan's signature dish — cold chicken and vegetable skewers in a fragrant, slightly spicy sesame oil sauce. Locals eat this for lunch. Pick your skewers, they count the sticks.", price: "¥30–50 pp", rating: 4.8 },
              { name: "跷脚牛肉", englishName: "Qiaojiao Beef", cuisine: "Leshan beef soup", note: "Leshan's other famous dish — a herbal beef bone broth with tender beef slices and offal. Simple, warming, and the perfect fuel before Mount Emei.", price: "¥25–40 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "car", duration: "40 min", note: "Drive to Mount Emei Scenic Area" },
          },
          {
            id: "g-d2-emei",
            time: "Afternoon · 2:00",
            icon: Sun,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Mount Emei — Baoguo Temple Area",
            subtitle: "Afternoon — Sacred Buddhist mountain",
            description: "One of China's Four Sacred Buddhist Mountains and a UNESCO World Heritage site. The mountain rises 3,099m and has 76 Buddhist monasteries. Since you're doing a half-day visit, you'll explore the Baoguo Temple area at the base — the main monastery complex with 16th-century halls, the lush botanical garden, and the surrounding trails through old-growth forest. The temple's bronze bell (cast in 1564) weighs 12.5 tonnes.",
            tip: "Our tip: The Baoguo area is the most accessible and still gives you the feel of Mount Emei — ancient temples in misty forest. The full summit trek to the Golden Summit takes a separate full day or overnight stay. If you want to add that, let us know and we can adjust the schedule.",
            transportAfter: { mode: "car", duration: "2.5 hrs", note: "Drive back to Chengdu" },
          },
          {
            id: "g-d2-dinner",
            time: "Evening · 7:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Back in Chengdu",
            description: "Back in the city — you've earned a proper Chengdu dinner:",
            restaurants: [
              { name: "蜀九香火锅", englishName: "Shu Jiu Xiang Hotpot", cuisine: "Traditional hotpot", note: "Locals' favourite — no-frills, packed every night, the most authentic hotpot experience in Chengdu. Get the old-style butter base.", price: "¥80–120 pp", rating: 4.9 },
              { name: "马旺子", englishName: "Ma Wang Zi", cuisine: "Sichuan home cooking", note: "Traditional Sichuan dishes done perfectly — kung pao chicken, twice-cooked pork, fish-fragrant aubergine. Great if you want a break from hotpot.", price: "¥70–100 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d2-hotel",
            time: "Night · 9:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Chongqing tomorrow",
            description: "Long day — get some rest. Tomorrow morning you'll explore Chengdu's old alleys before your afternoon train to Chongqing.",
          },
        ],
      },

      {
        label: "Day 3",
        subtitle: "May 22 · Chengdu → Chongqing — Wide & Narrow Alleys · Hongyadong",
        color: "#B45309",
        items: [
          {
            id: "g-d3-kuanzhai",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Wide & Narrow Alleys",
            subtitle: "Morning — 300-year-old Qing Dynasty lanes",
            description: "Three parallel alleys from the Qing Dynasty garrison — Wide Alley, Narrow Alley, and Well Alley. Each has a different character: Wide Alley is traditional teahouses and courtyard restaurants, Narrow Alley is boutiques and craft shops, Well Alley is street food and bars. Watch an ear-cleaning master at work, get your face painted for Sichuan opera, and try the famous rabbit-head snack.",
            image: `${CD}/kuanzhai1.jpg`,
            tip: "Our tip: Go in the morning (before 11 AM) when it's quieter. Wide Alley has the most character. The ear-cleaning is a genuine Chengdu tradition — sounds terrifying but it's incredibly relaxing.",
            previewImages: [`${CD}/kuanzhai1.jpg`, `${CD}/kuanzhai2.jpg`, `${CD}/kuanzhai3.jpg`],
            previewLine: "Three 300-year-old alleys — teahouses, ear-cleaning, street food, and Sichuan opera.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk to People's Park" },
          },
          {
            id: "g-d3-park",
            time: "Morning · 11:00",
            icon: Footprints,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "People's Park & Heming Teahouse",
            subtitle: "Morning — Tea, matchmaking, and tai chi",
            description: "This is where you understand Chengdu. The century-old Heming Teahouse is packed with locals drinking tea from lidded bowls, getting their ears cleaned, and playing mahjong. On weekends there's a matchmaking corner where parents post their children's dating profiles on umbrellas. It's free, it's real, and it's the most Chengdu thing you can do.",
            image: `${CD}/peoples_park1.jpg`,
            tip: "Our tip: Order a bowl of jasmine tea (¥15–30), sit in a bamboo chair, and just watch. This is the pace of Chengdu life. No ticket needed.",
            previewImages: [`${CD}/peoples_park1.jpg`, `${CD}/peoples_park2.jpg`, `${CD}/peoples_park3.jpg`],
            previewLine: "Century-old teahouse, bamboo chairs, ear-cleaning, and matchmaking parents.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to lunch, then station" },
          },
          {
            id: "g-d3-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Farewell Chengdu Lunch",
            subtitle: "Last Sichuan flavours",
            description: "One more round of Chengdu food before you leave:",
            restaurants: [
              { name: "钢管厂五区小郡肝串串", englishName: "Steel Pipe Factory Skewers", cuisine: "Chuan chuan (skewer hotpot)", note: "Grab skewers, dip in bubbling broth. A Chengdu institution — named after the old factory district. Cheap, fun, and packed with locals.", price: "¥40–60 pp", rating: 4.8 },
              { name: "甘食记", englishName: "Gan Shi Ji", cuisine: "Sichuan noodles", note: "Famous for their sweet water noodles (tian shui mian) — a cold noodle dish unique to Chengdu. Also excellent dan dan noodles.", price: "¥25–40 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Chengdu East Station" },
          },
          {
            id: "g-d3-train",
            time: "Afternoon · 2:30",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Chongqing",
            subtitle: "Chengdu East → Chongqing North · ~1.5 hours",
            description: "The Chengdu–Chongqing high-speed rail is one of the busiest in China. Second class is comfortable — wide seats, power outlets, and plenty of legroom. The 300km journey takes about 1.5 hours through the Sichuan Basin. We book the tickets linked to your passport — just scan at the gate and board.",
            tip: "Our tip: Second class (二等座) is perfectly fine — no need to upgrade. ¥150–200 one way. We book the e-ticket linked to your passport number, so you just tap your passport at the gate. No paper ticket needed.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi from Chongqing North to your hotel" },
          },
          {
            id: "g-d3-checkin",
            time: "Afternoon · 5:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Chongqing",
            subtitle: "Drop bags, freshen up",
            description: "Arrive in Chongqing, check in, and get ready for the evening. Chongqing's cityscape is best at night — the hills, neon, and river reflections are something else.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Hongyadong" },
          },
          {
            id: "g-d3-hongyadong",
            time: "Evening · 7:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Hongyadong at Night",
            subtitle: "Evening — The real-life Spirited Away",
            description: "An 11-storey stilted building complex built into the riverside cliff face — enter from the top (street level) and descend through restaurants, shops, and walkways to the river at the bottom. After dark, the golden lights turn it into what the internet calls 'the real-life Spirited Away.' The view from across the river on Qianximen Bridge is the money shot.",
            image: `${CQ}/hongyadong1.jpg`,
            tip: "Our tip: Go after 8 PM when all the lights are on. Enter from level 11 (Cangbai Road) and walk down. For the best photo, cross to the opposite riverbank or shoot from the bridge.",
            previewImages: [`${CQ}/hongyadong1.jpg`, `${CQ}/hongyadong2.jpg`, `${CQ}/hongyadong3.jpg`],
            previewLine: "11-storey cliff building lit up gold — the real-life Spirited Away.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Grab street food nearby or walk back" },
          },
          {
            id: "g-d3-dinner",
            time: "Evening · 9:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Late Dinner",
            subtitle: "Chongqing street food",
            description: "Welcome to Chongqing — eat late, eat spicy:",
            restaurants: [
              { name: "好又来酸辣粉", englishName: "Hao You Lai", cuisine: "Street noodles", note: "The most famous sour-spicy sweet potato noodles in Chongqing. ¥12 a bowl, queue out the door. Near Jiefangbei.", price: "¥12–20 pp", rating: 4.7 },
              { name: "八一好吃街", englishName: "Bayi Food Street", cuisine: "Street food", note: "A whole alley of street food stalls near Jiefangbei. Grilled skewers, liangfen (mung bean jelly), and chao shou (wontons). Cheap and fun.", price: "¥30–60 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
        ],
      },

      /* ═══════════════════════════════════════════
         CHONGQING · May 22–25
         ═══════════════════════════════════════════ */
      {
        label: "Day 4",
        subtitle: "May 23 · Chongqing — Wulong Day Trip · Three Natural Bridges",
        color: "#D0021B",
        items: [
          {
            id: "g-d4-depart",
            time: "Early Morning · 7:00",
            icon: Car,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "Private Car to Wulong",
            subtitle: "2-hour drive south-east to the karst region",
            description: "Your driver picks you up at 7 AM for the 170km drive to Wulong Karst National Geology Park. The drive takes about 2 hours on the expressway. This is a full day trip — you'll be back in the city by early evening.",
            tip: "Our tip: Grab breakfast from your hotel. The drive is scenic once you leave the city — mountains and river gorges. We provide a driver who knows the park well.",
            transportAfter: { mode: "car", duration: "2 hrs", note: "Expressway to Wulong" },
          },
          {
            id: "g-d4-bridges",
            time: "Morning · 9:30",
            icon: Camera,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Natural Bridges",
            subtitle: "Morning — UNESCO karst wonder",
            description: "Three colossal natural limestone bridges spanning a deep gorge — Tianlong (Heaven Dragon), Qinglong (Azure Dragon), and Heilong (Black Dragon). The tallest is 235 metres high and 150 metres wide. You descend 400 steps into the gorge and walk through the canyon beneath all three bridges. Halfway through is the Tianfu Inn — a traditional building used as a filming location in Transformers: Age of Extinction. The scale is hard to describe until you're standing under millions of tonnes of rock arching above you.",
            tip: "Our tip: Take the glass-floor elevator down to the gorge floor (¥15) instead of the stairs — saves your knees for the 3km walk through the canyon. The whole route takes 2–3 hours. Bring water.",
            transportAfter: { mode: "shuttle", duration: "15 min", note: "Park shuttle to Longshui Gorge" },
          },
          {
            id: "g-d4-gorge",
            time: "Midday · 12:00",
            icon: Navigation,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Longshui Gorge Earth Crack",
            subtitle: "Midday — Underground fissure walk",
            description: "A narrow 5km karst fissure carved by water over millions of years — you walk along a boardwalk inside the crack, with sheer rock walls rising 200+ metres on either side, sometimes narrowing to just a few metres apart. There are waterfalls, underground streams, and the lighting makes it atmospheric. It's included in the Wulong combo ticket and takes about 1–1.5 hours.",
            tip: "Our tip: This is included in the combo ticket with Three Natural Bridges. It's cooler inside the gorge — bring a light layer. The boardwalk can be slippery, so wear grippy shoes.",
            transportAfter: { mode: "car", duration: "20 min", note: "Drive to lunch" },
          },
          {
            id: "g-d4-lunch",
            time: "Afternoon · 1:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Wulong town",
            description: "Eat in Wulong town before heading back:",
            restaurants: [
              { name: "武隆碗碗羊肉", englishName: "Wulong Bowl Lamb", cuisine: "Local lamb stew", note: "Wulong's signature dish — tender lamb slow-cooked in a clay bowl with chillies and herbs. A hearty refuel after the morning hike.", price: "¥40–60 pp", rating: 4.6 },
              { name: "仙女镇农家乐", englishName: "Fairy Town Farmhouse", cuisine: "Farmhouse cooking", note: "Simple, honest countryside food near the park — stir-fried local vegetables, smoked meats, and rice. No frills, good value.", price: "¥30–50 pp", rating: 4.5 },
            ],
            transportAfter: { mode: "car", duration: "2 hrs", note: "Drive back to Chongqing city" },
          },
          {
            id: "g-d4-drone",
            time: "Evening · 8:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Chongqing Drone Light Show",
            subtitle: "Evening — Free drone spectacle over the river",
            description: "Chongqing runs periodic drone light shows over the Yangtze/Jialing river junction — hundreds of drones forming shapes and patterns against the night skyline. Free to watch from various riverside viewpoints. The combination of the drone show with Chongqing's already-insane neon skyline is unique.",
            tip: "Our tip: We'll confirm the exact schedule closer to your dates — these shows run on specific nights and the schedule changes. Best viewing spots are Qianximen Bridge area or the Nanbin Road riverfront. If the drone show isn't running on the 23rd, the Chongqing night skyline from Nanshan is just as spectacular.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d4-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — city day tomorrow",
            description: "Long day — you've earned the rest. Tomorrow is Chongqing city highlights and the 1949 Banquet dinner.",
          },
        ],
      },

      {
        label: "Day 5",
        subtitle: "May 24 · Chongqing — Ciqikou · Cableway · 1949 Banquet",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d5-ciqikou",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Ciqikou Ancient Town",
            subtitle: "Morning — 1,000-year-old porcelain port",
            description: "A thousand-year-old town built on a hillside along the Jialing River. Narrow stone-paved lanes wind between old wooden buildings — tea houses, Sichuan snack stalls, and shops selling handmade crafts. Try the famous Ciqikou mahua (twisted fried dough) and Chen Mahua which has been making it here for generations.",
            image: `${CQ}/ciqikou1.jpg`,
            tip: "Our tip: Go in the morning before 11 AM — the main street gets very crowded by noon. The side alleys are quieter and more interesting. Free entry.",
            previewImages: [`${CQ}/ciqikou1.jpg`, `${CQ}/ciqikou2.jpg`, `${CQ}/ciqikou3.jpg`],
            previewLine: "1,000-year-old hillside town — stone lanes, tea houses, and twisted fried dough.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi to Jiefangbei / city centre" },
          },
          {
            id: "g-d5-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Chongqing hotpot capital",
            description: "You can't leave Chongqing without proper hotpot:",
            restaurants: [
              { name: "洞亭火锅", englishName: "Dongting Hotpot", cuisine: "Cave hotpot", note: "Hotpot inside a literal cave — Chongqing's most unique dining experience. The atmosphere alone is worth it, and the broth is legit.", price: "¥80–120 pp", rating: 4.8 },
              { name: "周师兄大刀腰片", englishName: "Zhou Shixiong", cuisine: "Chongqing hotpot", note: "Famous for their knife-cut kidney slices and fresh duck intestine. Always packed — locals say it's the best hotpot in the city right now.", price: "¥90–130 pp", rating: 4.9 },
            ],
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Jiefangbei and Liziba area" },
          },
          {
            id: "g-d5-liziba",
            time: "Afternoon · 2:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Liziba Monorail & Jiefangbei",
            subtitle: "Afternoon — The train through a building",
            description: "Watch Line 2 of the Chongqing monorail punch straight through an apartment building at Liziba station — the most viral transport video in China. Then walk to Jiefangbei, Chongqing's main pedestrian square, where the liberation monument is surrounded by skyscrapers and massive LED screens.",
            image: `${CQ}/liziba1.jpg`,
            tip: "Our tip: The best viewing spot for the monorail is from the street below the building. Free — just show up and wait for the next train. Jiefangbei is a 10-minute walk from there.",
            previewImages: [`${CQ}/liziba1.jpg`, `${CQ}/liziba2.jpg`, `${CQ}/jiefangbei1.jpg`],
            previewLine: "A monorail through an apartment building — Chongqing's most viral moment.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the Yangtze Cableway station" },
          },
          {
            id: "g-d5-cableway",
            time: "Afternoon · 4:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Yangtze River Cableway",
            subtitle: "Afternoon — Cable car over the Yangtze",
            description: "The only urban passenger cableway still operating over the Yangtze River. A 5-minute ride in a retro cabin 300 metres above the water, with the entire Chongqing skyline and river spread out below you. It's been running since 1987 and was originally built as public transport — now it's the city's most iconic experience.",
            image: `${CQ}/cableway1.jpg`,
            tip: "Our tip: Take it from the Xinhua Road station (north side) for the best skyline views. ¥30 return. Queues can be 30-60 minutes — we can advise on timing to avoid the worst.",
            previewImages: [`${CQ}/cableway1.jpg`, `${CQ}/cableway2.jpg`, `${CQ}/cableway3.jpg`],
            previewLine: "Retro cable car 300m above the Yangtze — Chongqing's most iconic ride.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to 1949 Banquet" },
          },
          {
            id: "g-d5-1949",
            time: "Evening · 7:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "activity",
            title: "1949 Banquet — Immersive Dinner Show",
            subtitle: "Evening — Theatre meets dining",
            description: "An immersive dinner theatre set in 1949 Chongqing — the pivotal year when the city was the last Nationalist capital before the Communist revolution. You walk through elaborately recreated 1940s streetscapes (tea houses, newspaper offices, dance halls) while actors perform scenes around you. The multi-course banquet features traditional Chongqing dishes served in period settings. It's part dinner, part theatre, part time travel.",
            tip: "Our tip: This needs to be booked well in advance — it's one of Chongqing's most popular experiences. The show is about 2–3 hours including dinner. We handle the booking and can request English-friendly seating.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d5-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — Zhangjiajie tomorrow",
            description: "Your last night in Chongqing. Pack up — tomorrow you take the high-speed train to Zhangjiajie.",
          },
        ],
      },

      {
        label: "Day 6",
        subtitle: "May 25 · Chongqing → Zhangjiajie — Travel Day",
        color: "#B45309",
        items: [
          {
            id: "g-d6-museum",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Gorges Museum & People's Great Hall",
            subtitle: "Morning — Chongqing's best museum",
            description: "A free, world-class museum covering the Three Gorges region, the Three Gorges Dam project, ancient Ba culture, and wartime Chongqing (the city was China's WWII capital after the Nationalists fled Nanjing). The WWII bombing exhibition is particularly powerful — Chongqing was bombed for 5 years straight by Japanese forces, the longest continuous bombing of any city in history. The museum sits across a grand square from the People's Great Hall, a Soviet-influenced auditorium modelled on Beijing's Temple of Heaven that's one of Chongqing's most photographed buildings.",
            tip: "Our tip: Free entry with your passport — bring it. Budget 1.5 hours inside. The WWII section and the Three Gorges environmental exhibition are the highlights. Walk across the square afterwards for a photo of the People's Great Hall — you can't go inside but the exterior is the iconic shot.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to lunch then station" },
          },
          {
            id: "g-d6-lunch",
            time: "Midday · 11:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Early Lunch",
            subtitle: "Near the station",
            description: "Grab lunch before your train:",
            restaurants: [
              { name: "花市豌杂面", englishName: "Huashi Wandza Noodles", cuisine: "Chongqing noodles", note: "Chongqing's signature noodle: pea paste + minced meat + alkaline noodles. Simple, cheap, addictive. Perfect quick lunch before the train.", price: "¥15–25 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to Chongqing East Station" },
          },
          {
            id: "g-d6-train",
            time: "Afternoon · 1:00",
            icon: TrainFront,
            iconBg: "#E3F2FD",
            type: "transport",
            title: "High-Speed Train to Zhangjiajie",
            subtitle: "Chongqing East → Zhangjiajie West · ~2–3 hours",
            description: "The Chongqing–Zhangjiajie high-speed line opened in 2025 — what used to be a 5+ hour journey is now just 2–3 hours. The route cuts through dramatic karst landscapes in Hubei province. You'll arrive at Zhangjiajie West station, where your transfer is waiting.",
            tip: "Our tip: Second class is fine. ~¥200–250 one way. Same passport-scan boarding as the Chengdu train. The scenery through the window is worth staying awake for — tunnels and bridges through karst mountains.",
            transportAfter: { mode: "car", duration: "45 min", note: "Pre-arranged transfer to Wulingyuan" },
          },
          {
            id: "g-d6-arrive",
            time: "Afternoon · 4:30",
            icon: MapPin,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Arrive Wulingyuan",
            subtitle: "Settle in near the national park",
            description: "Your hotel is in the Wulingyuan area — the gateway town right next to Zhangjiajie National Forest Park. This is where you'll stay for 4 nights while you explore the park, Grand Canyon, and caves. The town has restaurants, shops, and the XiBu Street night market along the river.",
            tip: "Our tip: Tonight is free — walk XiBu Street along the river for a preview of the town. It's lit up at night with bars and food stalls. Mugwort cakes (艾草粑粑) are the local snack to try.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to hotel" },
          },
          {
            id: "g-d6-hotel",
            time: "Evening · 5:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Wulingyuan",
            subtitle: "Rest up — Forest Park tomorrow",
            description: "Get settled and rest. Tomorrow is the big one — Zhangjiajie National Forest Park, the Bailong Elevator, and the Avatar mountains.",
          },
        ],
      },

      /* ═══════════════════════════════════════════
         ZHANGJIAJIE · May 25–31
         ═══════════════════════════════════════════ */
      {
        label: "Day 7",
        subtitle: "May 26 · Zhangjiajie — Forest Park · Bailong Elevator · Tianzi Mountain",
        color: "#D0021B",
        items: [
          {
            id: "g-d7-park",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Zhangjiajie National Forest Park",
            subtitle: "Morning — Bailong Elevator + Yuanjiajie",
            description: "Thousands of tall sandstone pillars in a huge forested valley — this is the park that inspired the mountains in Avatar. You'll take the Bailong Elevator up the cliff (326m, the world's tallest outdoor lift), walk the Yuanjiajie ridge to the main viewpoints (Avatar Hallelujah Mountain, First Natural Bridge, Enchanting Terrace), then explore the platform trails.",
            image: FOREST,
            tip: "Our tip: Enter via the East Gate and head straight for the Bailong Elevator before the queues build. Peak season waits can hit 1-2 hours — we pre-book VIP fast-track passes to skip them.",
            previewImages: [FOREST, BAILONG, AVATAR],
            previewLine: "Towering sandstone pillars, the Bailong Elevator, and Avatar-inspiring views.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi from park gate to restaurant" },
          },
          {
            id: "g-d7-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near the park",
            description: "Refuel before the afternoon:",
            restaurants: [
              { name: "印象老灶台", englishName: "Old Stove Kitchen", cuisine: "Rustic Xiangxi", note: "A proper old-stove style restaurant with clay-pot chicken, baskets of local produce, and a smoky farmhouse atmosphere. Great after a morning hike.", price: "¥60–90 pp", rating: 4.8 },
              { name: "索溪山寨", englishName: "Suoxi Mountain Lodge", cuisine: "Xiangxi specialties", note: "A lively regional dining room with red lanterns and folk decor. Good broad intro to Xiangxi dishes.", price: "¥70–110 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "cable-car", duration: "25 min", note: "Cable car up to Tianzi Mountain ridge" },
          },
          {
            id: "g-d7-tianzi",
            time: "Afternoon · 2:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Tianzi Mountain",
            subtitle: "Afternoon — Sea of sandstone peaks",
            description: "The highest viewpoint in Wulingyuan (1,262m) — the ridge-top platform gives you an endless panorama of sandstone pillars stretching to the horizon. On misty mornings the tops poke through clouds like a sea of stone islands. You'll take the cable car up and walk the ridge trail between lookout points. The 'Imperial Writing Brush' formation — three thin pillars topped with trees — is one of China's most-photographed natural landmarks.",
            image: TIANZI,
            tip: "Our tip: Cable car queues can be brutal — aim to arrive by 2:30pm. If it's cloudy, the mist actually makes it better. We book the combo transport pass so you're not paying per ride.",
            previewImages: [TIANZI, TIANZI_CLOUDS, AVATAR],
            previewLine: "The highest peak in Wulingyuan — cable car up, sea of clouds below.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi down to Wulingyuan town for dinner" },
          },
          {
            id: "g-d7-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Wulingyuan town",
            description: "Back in town for dinner:",
            restaurants: [
              { name: "一村院子餐厅", englishName: "Village Courtyard", cuisine: "Courtyard fine dining", note: "Beautiful timber courtyard with pond-side tables. The best spot for a nice dinner after a big day in the park.", price: "¥120–180 pp", rating: 4.8 },
              { name: "大队老渔村", englishName: "Old Fishing Village", cuisine: "Farmhouse Xiangxi", note: "Rustic, ingredient-led spot with jars of pickles, fresh chillies, and preserved meats. Great for hearty fish dishes.", price: "¥80–120 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d7-hotel",
            time: "Night · 9:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — valley walk tomorrow",
            description: "Great first day in the park. Tomorrow is a more relaxed pace — a cultural workshop and the Golden Whip Stream valley walk.",
          },
        ],
      },

      {
        label: "Day 8",
        subtitle: "May 27 · Zhangjiajie — Golden Whip Stream · Evening Show",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d8-tujia",
            time: "Morning · 8:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Tujia Brocade Workshop",
            subtitle: "Morning — Cultural immersion",
            description: "Start the day with something genuinely unique — a visit to a traditional Tujia brocade weaving workshop. The Tujia people have been weaving their intricate 'xilankapu' cloth for over 2,000 years, and here you can watch master weavers at work and try the loom yourself. The patterns tell stories of mountains, rivers, and daily life.",
            image: "/uploads/itinerary/tujia_silk1.jpeg",
            tip: "Our tip: This is a quieter, more personal experience — perfect for the morning before the busier afternoon. You can buy authentic brocade pieces directly from the weavers.",
            previewImages: ["/uploads/itinerary/tujia_silk1.jpeg", "/uploads/itinerary/tujia_silk2.jpg", "/uploads/itinerary/tujia_silk3.jpeg"],
            previewLine: "Watch master weavers at work and try the loom yourself — 2,000 years of craft.",
            transportAfter: { mode: "walk", duration: "12 min", note: "Walk to lunch in Wulingyuan town" },
          },
          {
            id: "g-d8-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Wulingyuan town",
            description: "Easy lunch before the valley walk:",
            restaurants: [
              { name: "喜棠家饭", englishName: "Xitang Home Kitchen", cuisine: "Comfort food", note: "Warm, family-style place with straightforward local dishes — nothing fancy, just good honest food. A solid easy lunch.", price: "¥55–85 pp", rating: 4.6 },
              { name: "印象老灶台", englishName: "Old Stove Kitchen", cuisine: "Rustic Xiangxi", note: "If you want something more characterful: clay pots, local ingredients, and a proper old-kitchen feel.", price: "¥60–90 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the Golden Whip Stream entrance" },
          },
          {
            id: "g-d8-stream",
            time: "Afternoon · 2:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Golden Whip Stream",
            subtitle: "Afternoon — Valley walk along turquoise water",
            description: "A 7.5km walking trail along a crystal-clear stream at the bottom of the sandstone canyon — towering pillars and cliffs on both sides, huge trees, waterfalls, and wild macaque monkeys. It's flat, shaded, and one of the most beautiful walks in China. The water is turquoise-green and you can hear it the entire way. The 'Golden Whip Rock' formation — a thin 380m-tall pillar — is the highlight.",
            image: GOLDEN,
            tip: "Our tip: The full walk takes about 2.5 hours. Keep snacks in a zipped bag — the monkeys here are aggressive food thieves. We'll make sure you know which exit to take for your pickup.",
            previewImages: [GOLDEN, STREAM_CLOSE, AVATAR],
            previewLine: "A 7.5km valley walk through turquoise water and towering cliffs — monkeys included.",
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi back to town for dinner" },
          },
          {
            id: "g-d8-dinner",
            time: "Evening · 6:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "XiBu Street area",
            description: "Back in town for the evening:",
            restaurants: [
              { name: "溪布街小吃", englishName: "XiBu Street Snacks", cuisine: "Street food", note: "Lively XiBu Street evening: cold noodles, mugwort cakes, and snack-hopping around the lit-up riverside area.", price: "¥25–50 pp", rating: 4.7 },
              { name: "香花烧烤", englishName: "Xianghua BBQ", cuisine: "BBQ", note: "Fun, casual grill with skewers over charcoal and punchy garlicky plates for sharing.", price: "¥50–80 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to the show" },
          },
          {
            id: "g-d8-show",
            time: "Evening · 8:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Charming Xiangxi Show",
            subtitle: "Evening — Outdoor spectacular",
            description: "A massive outdoor live performance with 500+ performers — real waterfalls on stage, fire, traditional Tujia and Miao ethnic culture, and dramatic lighting against the mountains. It tells the story of western Hunan's history through music, dance, and theatre. One of the most impressive live shows in China.",
            image: "/uploads/itinerary/xiangxi_show.jpg",
            tip: "Our tip: Tickets sell out and need to be booked in advance through Chinese-only platforms. The show is about 90 minutes — bring a light jacket for the open-air theatre. We handle the booking.",
            previewImages: ["/uploads/itinerary/xiangxi_show.jpg", SHOW_STAGE, "/uploads/itinerary/tujia_silk3.jpeg"],
            previewLine: "500+ performers, real waterfalls on stage, fire, and Tujia & Miao culture.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi back to hotel" },
          },
          {
            id: "g-d8-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Grand Canyon tomorrow",
            description: "Great day. Tomorrow is the Zhangjiajie Grand Canyon and the famous Glass Bridge.",
          },
        ],
      },

      {
        label: "Day 9",
        subtitle: "May 28 · Zhangjiajie — Grand Canyon · Glass Bridge",
        color: "#B45309",
        items: [
          {
            id: "g-d9-canyon",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Zhangjiajie Grand Canyon",
            subtitle: "Morning — Cliffs, waterfalls, and river gorge",
            description: "A dramatic gorge carved into the sandstone — you descend steep stairs through a series of waterfalls and cliff-hugging walkways, past caves and natural springs, down to the turquoise river at the bottom. The canyon is about 3.5km long and takes 2–3 hours to walk. The Yibu Nanqiao (One Step Hard Bridge) is a narrow natural stone bridge high above the canyon that makes for a heart-pounding photo.",
            tip: "Our tip: Start early (8 AM) to beat the crowds. The descent has a lot of stairs — good shoes are essential. The canyon is a one-way route so you can't turn back. We book the tickets in advance (¥128 + glass bridge combo).",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Glass Bridge entrance" },
          },
          {
            id: "g-d9-glass",
            time: "Morning · 10:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Zhangjiajie Glass Bridge",
            subtitle: "Morning — Walk 300m above the canyon",
            description: "The world's longest and highest glass-bottomed bridge — 430 metres long, suspended 300 metres above the Grand Canyon floor. You walk across transparent glass panels with the canyon yawning below your feet. It's engineered to hold 800 people but they limit numbers, so it never feels crowded. The views down through the glass and out across the canyon are vertigo-inducing.",
            tip: "Our tip: You're only allowed 30 minutes on the bridge. No bags, selfie sticks, or loose items allowed — there are free lockers at the entrance. Shoe covers provided. If you want to bungee jump off the bridge (the world's highest commercial bungee at 260m), we can book that too.",
            transportAfter: { mode: "shuttle", duration: "15 min", note: "Shuttle back to the visitor centre" },
          },
          {
            id: "g-d9-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near the Grand Canyon",
            description: "Eat near the canyon area before heading back:",
            restaurants: [
              { name: "Grand Canyon Visitor Centre Restaurant", cuisine: "Chinese basics", note: "Simple but decent — noodles, rice dishes, and stir-fries at the park restaurant. Convenient and affordable.", price: "¥30–50 pp", rating: 4.0 },
              { name: "索溪山寨", englishName: "Suoxi Mountain Lodge", cuisine: "Xiangxi specialties", note: "Back in Wulingyuan — the lively dining room with red lanterns if you want a proper sit-down lunch.", price: "¥70–110 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "20 min", note: "Back to Wulingyuan" },
          },
          {
            id: "g-d9-free",
            time: "Afternoon · 3:00",
            icon: Footprints,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Free Afternoon",
            subtitle: "Rest or explore Baofeng Lake",
            description: "You've had a big morning. Options: rest at the hotel, explore Wulingyuan town, or visit Baofeng Lake — a serene alpine lake inside a sandstone amphitheatre where you take a boat ride past waterfalls and towering cliffs. The boat ride is about 30 minutes and it's one of the quieter, more beautiful spots in the area.",
            tip: "Our tip: If you do Baofeng Lake, it's ¥96 entry including the boat. It's about 20 minutes from town by taxi. Best in the late afternoon light.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Back to hotel or town" },
          },
          {
            id: "g-d9-dinner",
            time: "Evening · 6:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Wulingyuan",
            description: "Relaxed dinner in town:",
            restaurants: [
              { name: "一村院子餐厅", englishName: "Village Courtyard", cuisine: "Courtyard fine dining", note: "The beautiful timber courtyard again — pond-side tables, polished setting. Great if you feel like a nicer dinner tonight.", price: "¥120–180 pp", rating: 4.8 },
              { name: "香花烧烤", englishName: "Xianghua BBQ", cuisine: "BBQ", note: "Keep it casual — charcoal skewers and cold beer.", price: "¥50–80 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "taxi", duration: "5 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d9-hotel",
            time: "Night · 9:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest — caves and city transfer tomorrow",
            description: "Tomorrow morning is Yellow Dragon Cave, then you transfer to your new hotel in Zhangjiajie city for the final stretch of the trip.",
          },
        ],
      },

      {
        label: "Day 10",
        subtitle: "May 29 · Zhangjiajie — Yellow Dragon Cave · Transfer to City · 72 Tower",
        color: "#D0021B",
        items: [
          {
            id: "g-d10-cave",
            time: "Morning · 8:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Yellow Dragon Cave",
            subtitle: "Morning — Underground karst wonderland",
            description: "One of China's most spectacular show caves — a vast underground karst system with a river running through it. You walk through massive chambers filled with stalactites, stalagmites, and flowstone formations lit with coloured lights. The highlight is the 'Dinghai Shenzhen' — a single 19.2-metre stalagmite that's been insured for ¥100 million. There's also an underground boat ride along the subterranean river.",
            tip: "Our tip: The cave tour takes about 2 hours and includes the boat ride. It's a constant 16°C inside — bring a light jacket even in summer. ¥100 entry. We pre-book tickets.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi back to Wulingyuan for lunch" },
          },
          {
            id: "g-d10-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Last meal in Wulingyuan",
            description: "Final lunch in the Wulingyuan area before transferring to Zhangjiajie city:",
            restaurants: [
              { name: "喜棠家饭", englishName: "Xitang Home Kitchen", cuisine: "Comfort food", note: "Straightforward local dishes, family-style. A solid farewell lunch.", price: "¥55–85 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "car", duration: "45 min", note: "Transfer to Zhangjiajie city hotel" },
          },
          {
            id: "g-d10-checkin",
            time: "Afternoon · 2:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in — Zhangjiajie City",
            subtitle: "New hotel for the final 2 nights",
            description: "You're now in Zhangjiajie city itself (about 45 minutes from Wulingyuan). This is the base for Tianmen Mountain and the 72 Qilou Tower — both are in or near the city centre.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to 72 Qilou" },
          },
          {
            id: "g-d10-72tower",
            time: "Afternoon · 3:30",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "72 Qilou Tower",
            subtitle: "Afternoon — Zhangjiajie's architectural icon",
            description: "A striking 12-storey tower complex built into the cliffside in traditional Tujia and Miao architectural style — it looks like something out of a fantasy film. The tower combines ethnic minority cultural exhibits, restaurants, shops, and observation decks with views over the city and surrounding mountains. The rooftop terrace gives panoramic views, especially at sunset.",
            tip: "Our tip: Come in the late afternoon for the best light. The tower is especially photogenic from the outside — the stacked traditional architecture against the mountain backdrop. It's free to walk around the exterior; some interior sections have small entry fees.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to dinner" },
          },
          {
            id: "g-d10-dinner",
            time: "Evening · 6:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Zhangjiajie city",
            description: "Your first dinner in the city centre:",
            restaurants: [
              { name: "火宫殿", englishName: "Huogongdian", cuisine: "Hunan classics", note: "A famous Hunan chain — stinky tofu, Changsha-style rice noodles, Chairman Mao's red-braised pork. Loud, bustling, and very Hunan.", price: "¥50–80 pp", rating: 4.6 },
              { name: "湘里人家", englishName: "Xiangli Renjia", cuisine: "Hunan home cooking", note: "Homestyle Hunan dishes — smoked meats, chilli-fried pork, and steamed fish head with chopped chillies. Proper local food.", price: "¥60–90 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d10-hotel",
            time: "Night · 9:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Rest up — Tianmen Mountain tomorrow",
            description: "Get a good sleep — tomorrow is Tianmen Mountain, one of the most dramatic mountain experiences in China. Early start for the cable car.",
          },
        ],
      },

      {
        label: "Day 11",
        subtitle: "May 30 · Zhangjiajie — Tianmen Mountain · Glass Skywalks · 999 Steps",
        color: "#1A1A1A",
        items: [
          {
            id: "g-d11-cable",
            time: "Morning · 8:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Tianmen Mountain Cable Car",
            subtitle: "Morning — 7.5km ride into the clouds",
            description: "The world's longest passenger cableway — 7,455 metres from the city centre straight up to the Tianmen Mountain summit at 1,518m. The 28-minute ride takes you from street level over the city, through the foothills, and into the clouds. The steepest section climbs at a 37-degree angle. On a clear day you can see the entire Zhangjiajie basin below.",
            image: "/uploads/itinerary/tianmen_cable1.jpg",
            tip: "Our tip: Book the earliest time slot (8:00 AM) to avoid queues and get the clearest weather. Sit on the right side going up for the best mountain views. Bring a warm jacket — the summit is 10-15°C colder than the city.",
            previewImages: ["/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "A 28-minute ride from city streets into the clouds — 7.5km of jaw-dropping scenery.",
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to the east summit trail" },
          },
          {
            id: "g-d11-glass",
            time: "Morning · 9:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Glass Skywalks",
            subtitle: "Morning — Cliff-edge glass floor",
            description: "A glass-floored walkway bolted to the sheer cliff face at 1,400m — you walk along transparent panels with a 300-metre drop below your feet and the mountain wall on one side. The east side walk is longer (60m) and more exposed than the west. Even if you're not scared of heights, looking straight down through glass at a 300m cliff is a different experience entirely.",
            tip: "Our tip: The east side glass walk is longer and more dramatic than the west. You need shoe covers (¥5, bought on-site). Even people without fear of heights find their knees going weak — it's genuinely thrilling.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the escalator entrance" },
          },
          {
            id: "g-d11-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Summit Lunch",
            subtitle: "On top of the mountain",
            description: "Eat on the mountain before heading down:",
            restaurants: [
              { name: "Tianmen Summit Cafe", cuisine: "Quick bites", note: "Basic but convenient — instant noodles, snacks, and hot drinks. Overpriced but you're on top of a mountain.", price: "¥30–50 pp", rating: 3.8 },
              { name: "Pack your own lunch", cuisine: "Packed meal", note: "The smart move — grab breakfast extras from your hotel and bring them up. Water, fruit, sandwiches.", price: "Free", rating: 5.0 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to escalator for Tianmen Cave" },
          },
          {
            id: "g-d11-cave",
            time: "Afternoon · 1:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Heaven's Gate (Tianmen Cave) & 999 Steps",
            subtitle: "Afternoon — The stairway to heaven",
            description: "Tianmen Cave is a natural hole punched through the mountain — 131 metres high, 57 metres wide, visible from the city below. To reach it you descend the famous 999 steps (the 'Stairway to Heaven'), a near-vertical stone staircase clinging to the cliff face. The number 999 represents 'heaven' in Chinese numerology. Standing inside the cave with clouds drifting through and the valley visible far below is one of those moments you don't forget.",
            tip: "Our tip: Take it slow on the steep upper sections and use the railings — the steps are uneven. The cave itself is most dramatic when clouds drift through it, which happens most mornings.",
            previewImages: ["/uploads/itinerary/tianmen_cable2.jpg", "/uploads/itinerary/tianmen_cable1.jpg", "/uploads/itinerary/tianmen_cable3.jpg"],
            previewLine: "131m-high natural cave, 999 steps, and the feeling of descending from heaven.",
            transportAfter: { mode: "shuttle", duration: "25 min", note: "Coach down the 99-bend road" },
          },
          {
            id: "g-d11-99bend",
            time: "Afternoon · 3:00",
            icon: Camera,
            iconBg: "#E3F2FD",
            type: "activity",
            title: "99-Bend Road (Tongtian Avenue)",
            subtitle: "Afternoon — The most dramatic bus ride",
            description: "The coach ride down Tongtian Avenue — nearly 11 kilometres of mountain road with 99 hairpin turns switchbacking from 1,300m to 200m. The bus drivers navigate blind 180-degree turns with centimetres of clearance. It's equal parts terrifying and impressive, and the aerial views from above are spectacular.",
            tip: "Our tip: Sit on the left side for the best cliff-drop views. The ride takes about 25 minutes. If you get motion sick easily, take medication beforehand.",
            previewImages: ["/uploads/itinerary/99bend1.webp", "/uploads/itinerary/99bend2.jpeg", "/uploads/itinerary/99bend3.webp"],
            previewLine: "99 hairpin turns, 1,300m descent — the most dramatic bus ride of your life.",
          },
          {
            id: "g-d11-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Farewell Dinner",
            subtitle: "Last night in Zhangjiajie",
            description: "Your last dinner in China — make it a good one:",
            restaurants: [
              { name: "湘里人家", englishName: "Xiangli Renjia", cuisine: "Hunan home cooking", note: "Go back for your favourites — the smoked meats and chilli-fried pork are hard to beat.", price: "¥60–90 pp", rating: 4.7 },
              { name: "一村院子餐厅", englishName: "Village Courtyard", cuisine: "Courtyard fine dining", note: "If you want a proper final-night dinner: the timber courtyard, pond-side tables, and polished setting make it feel like a proper farewell.", price: "¥120–180 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "g-d11-hotel",
            time: "Night · 9:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Last night — departure tomorrow",
            description: "Your last night. Pack up and get some rest — your airport transfer is arranged for the morning.",
          },
        ],
      },
    ],

    picks: [
      {
        id: "g-pick-vpn",
        emoji: "📱",
        type: "Essential",
        title: "VPN & eSIM Setup",
        desc: "Google, WhatsApp, Instagram, and most Western apps are blocked in China. You need a VPN installed before you arrive, plus a China eSIM for data.",
        meiNote: "We send you a step-by-step setup guide with our recommended VPN and eSIM provider before your trip. Takes 10 minutes to set up.",
        image: AVATAR,
        tag: "We'll set up",
        tagColor: "#D0021B",
      },
      {
        id: "g-pick-opera",
        emoji: "🎭",
        type: "Culture",
        title: "Sichuan Opera Face-Changing",
        desc: "A full Sichuan opera show in Chengdu with the famous 'face-changing' (bian lian) — performers swap painted masks in a fraction of a second. Nobody knows how.",
        meiNote: "Several theatres do this in Chengdu. We book the best one with good seats — tickets are Chinese-platform only. Could fit on the evening of Day 1 or Day 2.",
        image: `${CD}/jinli1.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "g-pick-cooking",
        emoji: "🌶️",
        type: "Food",
        title: "Sichuan Cooking Class",
        desc: "A hands-on class in Chengdu where you learn to cook mapo tofu, kung pao chicken, and dan dan noodles. Includes market visit to buy ingredients.",
        meiNote: "Half day, includes lunch — you eat everything you cook. Could replace the Day 1 afternoon if you're more into food than history.",
        image: `${CD}/wuhou1.jpg`,
        tag: "We can arrange",
        tagColor: "#059669",
      },
      {
        id: "g-pick-fenghuang",
        emoji: "🏘️",
        type: "Day Trip",
        title: "Fenghuang Ancient Town",
        desc: "A perfectly preserved riverside town with 300-year-old stilted houses, stone bridges, and lantern-lit streets — often called the most beautiful small town in China. About 3.5 hours from Zhangjiajie.",
        meiNote: "You have spare time in the Zhangjiajie stretch — we could swap one of the free afternoons for a Fenghuang day trip. It's a long day but worth it.",
        image: TIANZI,
        tag: "Day trip",
        tagColor: "#B45309",
      },
      {
        id: "g-pick-cruise",
        emoji: "🌃",
        type: "Nightlife",
        title: "Two Rivers Night Cruise — Chongqing",
        desc: "A 1-hour boat ride where the Yangtze and Jialing rivers meet — see the entire lit-up Chongqing skyline, Hongyadong, and bridges from the water.",
        meiNote: "Boats run 7-10 PM nightly in Chongqing. ¥100-200 depending on deck. Could fit on the evening of Day 3 or Day 5.",
        image: `${CQ}/hongyadong1.jpg`,
        tag: "We can book",
        tagColor: "#7C3AED",
      },
    ],
  };
}
