import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

const CQ = "/uploads/itinerary/chongqing";

export function buildChongqingConfig(): ItineraryConfig {
  return {
    cityName: "Chongqing",
    title: "Chongqing Discovery",
    location: "Chongqing, China",
    duration: "2 Days",
    heroImage: `${CQ}/hongyadong1.jpg`,
    meiGreeting: "This is what a Chongqing trip could look like. We handle tickets, restaurants, transport, and on-the-ground help — so you can just enjoy the trip.",
    departure: {
      time: "Morning",
      title: "Airport / Train Transfer",
      description: "We arrange a driver to Chongqing Jiangbei Airport or Chongqing North Railway Station. Chongqing is also the starting point for Yangtze River cruises to the Three Gorges.",
    },
    departureNote: "This is just a sample — we'd tailor everything around your dates and what you want to do. Message us to get started.",
    days: [
      {
        label: "Day 1",
        subtitle: "Ciqikou · Yangtze Cableway · Hongyadong",
        color: "#D0021B",
        items: [
          {
            id: "cq-d1-ciqikou",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Ciqikou Ancient Town",
            subtitle: "Morning — 1,000-year-old porcelain port",
            description: "A thousand-year-old town built on a hillside along the Jialing River. Narrow stone-paved lanes wind between old wooden buildings — tea houses, Sichuan snack stalls, and shops selling handmade crafts. Try the famous Ciqikou mahua (twisted fried dough) and Chen Mahua which has been making it here for generations.",
            image: `${CQ}/ciqikou1.jpg`,
            tip: "Our tip: Go in the morning before 11 AM — the main street gets very crowded by noon. The side alleys are quieter and more interesting. Free entry.",
            previewImages: [`${CQ}/ciqikou1.jpg`, `${CQ}/ciqikou2.jpg`, `${CQ}/ciqikou3.jpg`],
            previewLine: "1,000-year-old hillside town — stone lanes, tea houses, and twisted fried dough.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi to Jiefangbei / city centre" },
          },
          {
            id: "cq-d1-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Chongqing hotpot capital",
            description: "Chongqing is the birthplace of Chinese hotpot. The city takes it seriously — mala (numbing-spicy) broth, beef tallow base, and offal that you'll learn to love:",
            restaurants: [
              { name: "洞亭火锅", englishName: "Dongting Hotpot", cuisine: "Cave hotpot", note: "Hotpot inside a literal cave — Chongqing's most unique dining experience. The atmosphere alone is worth it, and the broth is legit.", price: "¥80–120 pp", rating: 4.8 },
              { name: "周师兄大刀腰片", englishName: "Zhou Shixiong", cuisine: "Chongqing hotpot", note: "Famous for their knife-cut kidney slices and fresh duck intestine. Always packed — locals say it's the best hotpot in the city right now.", price: "¥90–130 pp", rating: 4.9 },
              { name: "好又来酸辣粉", englishName: "Hao You Lai", cuisine: "Street noodles", note: "The most famous sour-spicy sweet potato noodles in Chongqing. ¥12 a bowl, queue out the door. Near Jiefangbei.", price: "¥12–20 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to Jiefangbei and Yangtze Cableway" },
          },
          {
            id: "cq-d1-liziba",
            time: "Afternoon · 2:30",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Liziba Monorail & Jiefangbei",
            subtitle: "Afternoon — The train through a building",
            description: "Watch Line 2 of the Chongqing monorail punch straight through an apartment building at Liziba station — the most viral transport video in China. Then walk to Jiefangbei, Chongqing's main pedestrian square, where the liberation monument is surrounded by skyscrapers and massive LED screens.",
            image: `${CQ}/liziba1.jpg`,
            tip: "Our tip: The best viewing spot for the monorail is from the street below the building. Free — just show up and wait for the next train. Jiefangbei is a 10-minute walk from there.",
            previewImages: [`${CQ}/liziba1.jpg`, `${CQ}/liziba2.jpg`, `${CQ}/jiefangbei1.jpg`],
            previewLine: "A monorail through an apartment building — Chongqing's most viral moment.",
            transportAfter: { mode: "walk", duration: "10 min", note: "Walk to the Yangtze Cableway station" },
          },
          {
            id: "cq-d1-cableway",
            time: "Afternoon · 4:00",
            icon: Navigation,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Yangtze River Cableway",
            subtitle: "Afternoon — Cable car over the Yangtze",
            description: "The only urban passenger cableway still operating over the Yangtze River. A 5-minute ride in a retro cabin 300 metres above the water, with the entire Chongqing skyline and river spread out below you. It's been running since 1987 and was originally built as public transport — now it's the city's most iconic experience.",
            image: `${CQ}/cableway1.jpg`,
            tip: "Our tip: Take it from the Xinhua Road station (north side) for the best skyline views. ¥30 return. Queues can be 30-60 minutes — we can advise on timing to avoid the worst.",
            previewImages: [`${CQ}/cableway1.jpg`, `${CQ}/cableway2.jpg`, `${CQ}/cableway3.jpg`],
            previewLine: "Retro cable car 300m above the Yangtze — Chongqing's most iconic ride.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk along the riverfront to Hongyadong" },
          },
          {
            id: "cq-d1-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Near Hongyadong",
            description: "Eat before the lights come on:",
            restaurants: [
              { name: "纸盐河码头火锅", englishName: "Paper Salt River Wharf Hotpot", cuisine: "Riverside hotpot", note: "A cave-style hotpot restaurant built into the cliff near Hongyadong. River views from the terrace, traditional beef tallow broth.", price: "¥100–140 pp", rating: 4.7 },
              { name: "花市豌杂面", englishName: "Huashi Wandza Noodles", cuisine: "Chongqing noodles", note: "Chongqing's signature breakfast-turned-anytime noodle: pea paste + minced meat + alkaline noodles. Simple, cheap, addictive.", price: "¥15–25 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to Hongyadong" },
          },
          {
            id: "cq-d1-hongyadong",
            time: "Evening · 7:30",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Hongyadong at Night",
            subtitle: "Evening — The real-life Spirited Away",
            description: "An 11-storey stilted building complex built into the riverside cliff face — enter from the top (street level) and descend through restaurants, shops, and walkways to the river at the bottom. After dark, the golden lights turn it into what the internet calls 'the real-life Spirited Away.' The view from across the river on Qianximen Bridge is the money shot.",
            image: `${CQ}/hongyadong1.jpg`,
            tip: "Our tip: Go after 8 PM when all the lights are on. Enter from level 11 (Cangbai Road) and walk down. For the best photo, cross to the opposite riverbank or shoot from the bridge.",
            previewImages: [`${CQ}/hongyadong1.jpg`, `${CQ}/hongyadong2.jpg`, `${CQ}/hongyadong3.jpg`],
            previewLine: "11-storey cliff building lit up gold — the real-life Spirited Away.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "cq-d1-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in to Hotel",
            subtitle: "Rest up — skyline views tomorrow",
            description: "Get some rest. Day 2 has the best panoramic views of Chongqing and a deeper dive into the city's culture.",
          },
        ],
      },
      {
        label: "Day 2",
        subtitle: "Three Gorges Museum · Nanshan Viewpoint · Night Skyline",
        color: "#1A1A1A",
        items: [
          {
            id: "cq-d2-museum",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Three Gorges Museum",
            subtitle: "Morning — Chongqing's best museum",
            description: "A free museum covering the history of the Three Gorges region, wartime Chongqing (the city was China's WWII capital), and the controversial Three Gorges Dam project. The WWII bombing exhibition is particularly powerful. Right next to the People's Great Hall — a Soviet-style auditorium you can photograph from outside.",
            image: `${CQ}/museum1.jpg`,
            tip: "Our tip: Free entry with passport. The Three Gorges environmental exhibition and the WWII section are the highlights. Budget 1.5-2 hours. The People's Great Hall is right across the square — quick photo stop.",
            previewImages: [`${CQ}/museum1.jpg`, `${CQ}/museum2.jpg`, `${CQ}/museum3.jpg`],
            previewLine: "Free museum — WWII history, Three Gorges Dam, and wartime Chongqing.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to lunch" },
          },
          {
            id: "cq-d2-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "More Chongqing flavours",
            description: "Try something different from hotpot:",
            restaurants: [
              { name: "受气牛肉", englishName: "Shouqi Beef", cuisine: "Chongqing beef", note: "Famous for their spicy boiled beef (shui zhu niu rou). Fiery red chilli oil, tender beef, and a hit of Sichuan pepper. Intense.", price: "¥50–80 pp", rating: 4.8 },
              { name: "李子坝梁山鸡", englishName: "Liziba Liangshan Chicken", cuisine: "Jianghu chicken", note: "A Chongqing classic — chicken braised in a massive pot of chillies and peppercorns. You finish with noodles or rice in the leftover sauce.", price: "¥60–90 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "20 min", note: "Taxi to Nanshan" },
          },
          {
            id: "cq-d2-nanshan",
            time: "Afternoon · 4:30",
            icon: Sunset,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Nanshan One Tree Viewpoint",
            subtitle: "Late afternoon — The best skyline view",
            description: "The definitive panoramic viewpoint of Chongqing — from Nanshan hill on the south bank, you see the entire peninsula where the Yangtze and Jialing rivers meet, lit up with skyscrapers. Come before sunset, watch the city transition from golden hour to night lights. This is the photo you came to Chongqing for.",
            image: `${CQ}/nanshan1.jpg`,
            tip: "Our tip: Arrive by 5 PM to get a good spot before sunset. ¥30 entry. The viewing platform gets crowded at peak sunset — the terrace one level below is just as good with fewer people.",
            previewImages: [`${CQ}/nanshan1.jpg`, `${CQ}/nanshan2.jpg`, `${CQ}/nanshan3.jpg`],
            previewLine: "Two rivers, a lit-up peninsula, and the best city skyline view in China.",
            transportAfter: { mode: "taxi", duration: "25 min", note: "Taxi back to city for dinner" },
          },
          {
            id: "cq-d2-dinner",
            time: "Evening · 7:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Farewell Dinner",
            subtitle: "Your last Chongqing meal",
            description: "One more round:",
            restaurants: [
              { name: "珮姐老火锅", englishName: "Peijie Old Hotpot", cuisine: "Traditional hotpot", note: "One of Chongqing's most awarded hotpot spots. Old-school atmosphere, serious mala broth, and their nine-grid pot is the traditional Chongqing way.", price: "¥90–130 pp", rating: 4.9 },
              { name: "八一好吃街", englishName: "Bayi Food Street", cuisine: "Street food", note: "A whole alley of street food stalls near Jiefangbei. Grilled skewers, liangfen (mung bean jelly), and chao shou (wontons). Cheap and fun for a last night.", price: "¥30–60 pp", rating: 4.6 },
            ],
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "cq-d2-hotel",
            time: "Night · 10:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — onward tomorrow",
            description: "Get a good rest. Your transfer is arranged for the morning.",
          },
        ],
      },
    ],
    picks: [
      {
        id: "cq-pick-1",
        emoji: "🏔️",
        type: "Day Trip",
        title: "Wulong Karst National Park",
        desc: "Massive natural limestone bridges, a giant sinkhole, and the filming location for Transformers 4. About 3 hours from Chongqing city.",
        meiNote: "Full day trip. We arrange private transport and tickets — the park booking system is Chinese-only.",
        image: `${CQ}/wulong1.jpg`,
        tag: "Day trip",
        tagColor: "#B45309",
      },
      {
        id: "cq-pick-2",
        emoji: "🚢",
        type: "Cruise",
        title: "Yangtze River Cruise",
        desc: "A 3-4 day cruise through the Three Gorges from Chongqing to Yichang — dramatic cliffs, the world's largest dam, and lesser gorges by small boat.",
        meiNote: "Multiple cruise lines and cabin types. We find the right one for your budget and dates.",
        image: `${CQ}/cableway3.jpg`,
        tag: "Multi-day",
        tagColor: "#7C3AED",
      },
      {
        id: "cq-pick-3",
        emoji: "🌶️",
        type: "Food",
        title: "Hotpot Cooking Class",
        desc: "Learn to make Chongqing hotpot from scratch — prepare the mala broth base, slice the meats, and understand why this city is obsessed.",
        meiNote: "We arrange this with a local cooking school. Half day, you eat everything you make.",
        image: `${CQ}/ciqikou3.jpg`,
        tag: "We can arrange",
        tagColor: "#D0021B",
      },
      {
        id: "cq-pick-4",
        emoji: "🌃",
        type: "Nightlife",
        title: "Two Rivers Night Cruise",
        desc: "A 1-hour boat ride where the Yangtze and Jialing rivers meet — see the entire lit-up skyline, Hongyadong, and bridges from the water.",
        meiNote: "Boats run 7-10 PM nightly. ¥100-200 depending on deck. We book the best seats.",
        image: `${CQ}/hongyadong3.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "cq-pick-5",
        emoji: "🚄",
        type: "Day Trip",
        title: "Chengdu Day Trip",
        desc: "Chongqing to Chengdu is just 1.5 hours by bullet train. Pandas, Wide & Narrow Alleys, and the best Sichuan food in the world.",
        meiNote: "We book the train and can plan a full Chengdu day. Check our Chengdu itinerary too.",
        image: `${CQ}/jiefangbei1.jpg`,
        tag: "1.5hr by train",
        tagColor: "#059669",
      },
    ],
  };
}
