import { Sun, Camera, Utensils, Moon, Hotel, Navigation, Sunset, Footprints } from "lucide-react";
import type { ItineraryConfig } from "../ItineraryPage";

const CD = "/uploads/itinerary/chengdu";

export function buildChengduConfig(): ItineraryConfig {
  return {
    cityName: "Chengdu",
    title: "Chengdu Discovery",
    location: "Sichuan, China",
    duration: "2 Days",
    heroImage: `${CD}/panda1.jpg`,
    meiGreeting: "This is what a Chengdu trip could look like. We handle tickets, restaurants, transport, and on-the-ground help — so you can just enjoy the trip.",
    departure: {
      time: "Morning",
      title: "Airport / Train Transfer",
      description: "We arrange a driver to Chengdu Tianfu Airport or Chengdu East Railway Station. Chengdu is also a great base for day trips to Leshan, Dujiangyan, and Mount Qingcheng.",
    },
    departureNote: "This is just a sample — we'd tailor everything around your dates and what you want to do. Message us to get started.",
    days: [
      {
        label: "Day 1",
        subtitle: "Panda Base · Wuhou Shrine · Jinli Street",
        color: "#D0021B",
        items: [
          {
            id: "cd-d1-panda",
            time: "Morning · 7:30",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Giant Panda Base",
            subtitle: "Morning — 244 pandas in bamboo forest",
            description: "The world's largest captive panda breeding facility — 244 giant pandas in naturalistic forest enclosures. You'll see adults lazily eating bamboo, red pandas climbing trees, and if you're lucky, the nursery with newborn cubs behind glass. The base is huge (200+ hectares) but the best enclosures are clustered together.",
            image: `${CD}/panda1.jpg`,
            tip: "Our tip: Be at the gate when it opens at 7:30 AM — pandas are most active before 10 AM and the crowds arrive by 9. Tickets (¥55) must be booked on Chinese apps days in advance. We handle it.",
            previewImages: [`${CD}/panda1.jpg`, `${CD}/panda2.jpg`, `${CD}/panda3.jpg`],
            previewLine: "244 giant pandas — adults, cubs, and red pandas in bamboo forest enclosures.",
            transportAfter: { mode: "taxi", duration: "30 min", note: "Taxi back to the city centre" },
          },
          {
            id: "cd-d1-lunch",
            time: "Midday · 12:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Sichuan food — the real deal",
            description: "Chengdu is a UNESCO City of Gastronomy. This is where you eat the best Sichuan food in the world:",
            restaurants: [
              { name: "陈麻婆豆腐", englishName: "Chen Mapo Tofu", cuisine: "Sichuan classic", note: "The original mapo tofu — founded 1862. The numbing-spicy (mala) flavour hits different at the source. A must.", price: "¥40–60 pp", rating: 4.7 },
              { name: "小龙坎火锅", englishName: "Xiaolongkan Hotpot", cuisine: "Sichuan hotpot", note: "One of Chengdu's most famous hotpot chains. Get the half-and-half pot if you can't handle full spice. The beef and tripe are excellent.", price: "¥80–120 pp", rating: 4.8 },
              { name: "严太婆锅盔", englishName: "Yan Taipo Guokui", cuisine: "Street snack", note: "Crispy stuffed flatbread — the most addictive street food in Chengdu. Spicy pork filling. ¥8 each.", price: "¥8–15 pp", rating: 4.9 },
            ],
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to Wuhou Shrine" },
          },
          {
            id: "cd-d1-wuhou",
            time: "Afternoon · 2:00",
            icon: Camera,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "Wuhou Shrine",
            subtitle: "Afternoon — Three Kingdoms history",
            description: "China's only shrine where a king and his minister share the same temple — dedicated to Liu Bei and Zhuge Liang from the Three Kingdoms period (1,800 years ago). Even if you don't know the history, the red-walled bamboo corridor (Hong Qiang Zhu Ying) is one of the most photographed spots in Chengdu. The bonsai garden and ancient cypress trees are beautiful.",
            image: `${CD}/wuhou1.jpg`,
            tip: "Our tip: ¥50 entry. The red wall bamboo path is at the back — most tourists miss it. It connects directly to Jinli Street through the back exit, so do them together.",
            previewImages: [`${CD}/wuhou1.jpg`, `${CD}/wuhou2.jpg`, `${CD}/wuhou3.jpg`],
            previewLine: "1,800-year-old Three Kingdoms shrine with the famous red-wall bamboo path.",
            transportAfter: { mode: "walk", duration: "2 min", note: "Walk through the back gate to Jinli Street" },
          },
          {
            id: "cd-d1-dinner",
            time: "Evening · 5:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Dinner",
            subtitle: "Jinli Street area",
            description: "Graze through the street food on Jinli, or sit down nearby:",
            restaurants: [
              { name: "Jinli Street Food Stalls", englishName: "Jinli Street Food", cuisine: "Street snacks", note: "San da pao (sweet rice balls), bo bo ji (cold skewers), dan dan noodles, rabbit heads — just point and eat your way down the street.", price: "¥30–60 pp", rating: 4.6 },
              { name: "大妙火锅", englishName: "Da Miao Hotpot", cuisine: "Premium hotpot", note: "A more upscale hotpot with a beautiful traditional courtyard setting. The beef tallow base is intensely flavourful.", price: "¥120–160 pp", rating: 4.8 },
            ],
            transportAfter: { mode: "walk", duration: "1 min", note: "You're already on Jinli Street" },
          },
          {
            id: "cd-d1-jinli",
            time: "Evening · 7:00",
            icon: Moon,
            iconBg: "#EDE7F6",
            type: "activity",
            title: "Jinli Ancient Street",
            subtitle: "Evening — Lanterns and street food",
            description: "A 550-metre lantern-lit pedestrian street that CNN named one of the world's 21 most beautiful streets. Red lanterns, traditional architecture, face-changing opera performances on the outdoor stage, and Sichuan street food everywhere. It's touristy but genuinely atmospheric at night — the lanterns reflecting off the old buildings is the quintessential Chengdu photo.",
            image: `${CD}/jinli1.jpg`,
            tip: "Our tip: Come after dark when the lanterns are lit — it's completely different from daytime. The outdoor face-changing opera performances are free and happen every 30 minutes.",
            previewImages: [`${CD}/jinli1.jpg`, `${CD}/jinli2.jpg`, `${CD}/jinli3.jpg`],
            previewLine: "Red lanterns, face-changing opera, and CNN's pick for world's most beautiful streets.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to hotel" },
          },
          {
            id: "cd-d1-hotel",
            time: "Night · 9:30",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Check in to Hotel",
            subtitle: "Rest up — alleys and poetry tomorrow",
            description: "Get a good sleep. Day 2 is a more relaxed pace — Chengdu's old alleys, a tea house, and a poet's garden.",
          },
        ],
      },
      {
        label: "Day 2",
        subtitle: "Wide & Narrow Alleys · Du Fu Cottage · People's Park",
        color: "#1A1A1A",
        items: [
          {
            id: "cd-d2-kuanzhai",
            time: "Morning · 9:00",
            icon: Sun,
            iconBg: "#FFF3E0",
            type: "activity",
            title: "Wide & Narrow Alleys",
            subtitle: "Morning — 300-year-old Qing Dynasty lanes",
            description: "Three parallel alleys from the Qing Dynasty garrison — Wide Alley, Narrow Alley, and Well Alley. Each has a different character: Wide Alley is traditional teahouses and courtyard restaurants, Narrow Alley is boutiques and craft shops, Well Alley is street food and bars. Watch an ear-cleaning master at work, get your face painted for Sichuan opera, and try the famous rabbit-head snack.",
            image: `${CD}/kuanzhai1.jpg`,
            tip: "Our tip: Go in the morning (before 11 AM) when it's quieter. Wide Alley has the most character. The ear-cleaning is a genuine Chengdu tradition — sounds terrifying but it's incredibly relaxing.",
            previewImages: [`${CD}/kuanzhai1.jpg`, `${CD}/kuanzhai2.jpg`, `${CD}/kuanzhai3.jpg`],
            previewLine: "Three 300-year-old alleys — teahouses, ear-cleaning, street food, and Sichuan opera.",
            transportAfter: { mode: "walk", duration: "15 min", note: "Walk to People's Park" },
          },
          {
            id: "cd-d2-park",
            time: "Morning · 11:00",
            icon: Footprints,
            iconBg: "#E8F5E9",
            type: "activity",
            title: "People's Park & Heming Teahouse",
            subtitle: "Morning — Tea, matchmaking, and tai chi",
            description: "This is where you understand Chengdu. The century-old Heming Teahouse is packed with locals drinking tea from lidded bowls, getting their ears cleaned, and playing mahjong. On weekends there's a matchmaking corner where parents post their children's dating profiles on umbrellas. It's free, it's real, and it's the most Chengdu thing you can do.",
            image: `${CD}/peoples_park1.jpg`,
            tip: "Our tip: Order a bowl of jasmine tea (¥15–30), sit in a bamboo chair, and just watch. This is the pace of Chengdu life. No ticket needed.",
            previewImages: [`${CD}/peoples_park1.jpg`, `${CD}/peoples_park2.jpg`, `${CD}/peoples_park3.jpg`],
            previewLine: "Century-old teahouse, bamboo chairs, ear-cleaning, and matchmaking parents.",
            transportAfter: { mode: "taxi", duration: "10 min", note: "Taxi to Du Fu's Cottage" },
          },
          {
            id: "cd-d2-lunch",
            time: "Midday · 12:30",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Lunch",
            subtitle: "Near Du Fu Cottage",
            description: "More Sichuan flavours to try:",
            restaurants: [
              { name: "钢管厂五区小郡肝串串", englishName: "Steel Pipe Factory Skewers", cuisine: "Chuan chuan (skewer hotpot)", note: "Grab skewers, dip in bubbling broth. A Chengdu institution — named after the old factory district. Cheap, fun, and packed with locals.", price: "¥40–60 pp", rating: 4.8 },
              { name: "甘食记", englishName: "Gan Shi Ji", cuisine: "Sichuan noodles", note: "Famous for their sweet water noodles (tian shui mian) — a cold noodle dish unique to Chengdu. Also excellent dan dan noodles.", price: "¥25–40 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "walk", duration: "5 min", note: "Walk to Du Fu's Thatched Cottage" },
          },
          {
            id: "cd-d2-dufu",
            time: "Afternoon · 2:00",
            icon: Camera,
            iconBg: "#FFF8E1",
            type: "activity",
            title: "Du Fu's Thatched Cottage",
            subtitle: "Afternoon — A poet's garden",
            description: "A 300-acre garden museum on the site where Du Fu — China's greatest poet — wrote 240 of his masterpieces during four years of exile. The reconstructed thatched cottage is surrounded by bamboo groves, lotus ponds, and winding paths. It's a peaceful, contemplative space and one of the most beautiful gardens in Chengdu.",
            image: `${CD}/dufu1.jpg`,
            tip: "Our tip: ¥50 entry. Much quieter in the afternoon. The museum has good English explanations of Du Fu's poetry. The bamboo grove behind the main cottage is the most peaceful part.",
            previewImages: [`${CD}/dufu1.jpg`, `${CD}/dufu2.jpg`, `${CD}/dufu3.jpg`],
            previewLine: "Where China's greatest poet wrote 240 masterpieces — bamboo groves and lotus ponds.",
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to dinner" },
          },
          {
            id: "cd-d2-dinner",
            time: "Evening · 6:00",
            icon: Utensils,
            iconBg: "#FFF0EE",
            type: "meal",
            title: "Farewell Dinner",
            subtitle: "Your last Chengdu meal",
            description: "End your Chengdu trip with the city's best:",
            restaurants: [
              { name: "蜀九香火锅", englishName: "Shu Jiu Xiang Hotpot", cuisine: "Traditional hotpot", note: "Locals' favourite — no-frills, packed every night, the most authentic hotpot experience in Chengdu. Get the old-style butter base.", price: "¥80–120 pp", rating: 4.9 },
              { name: "马旺子", englishName: "Ma Wang Zi", cuisine: "Sichuan home cooking", note: "Traditional Sichuan dishes done perfectly — kung pao chicken, twice-cooked pork, fish-fragrant aubergine. A proper farewell dinner.", price: "¥70–100 pp", rating: 4.7 },
            ],
            transportAfter: { mode: "taxi", duration: "15 min", note: "Taxi to hotel" },
          },
          {
            id: "cd-d2-hotel",
            time: "Night · 9:00",
            icon: Hotel,
            iconBg: "#E3F2FD",
            type: "hotel",
            title: "Back to Hotel",
            subtitle: "Pack up — onward tomorrow",
            description: "Get a good rest. Your transfer is arranged for the morning.",
          },
        ],
      },
    ],
    picks: [
      {
        id: "cd-pick-1",
        emoji: "🗿",
        type: "Day Trip",
        title: "Leshan Giant Buddha",
        desc: "The world's largest stone Buddha — 71 metres tall, carved into a cliff where three rivers collide. About 2 hours from Chengdu by bus or train.",
        meiNote: "We book the tickets and arrange transport. The boat view is better than climbing down the stairs (2+ hour queue).",
        image: `${CD}/leshan1.jpg`,
        tag: "Day trip",
        tagColor: "#B45309",
      },
      {
        id: "cd-pick-2",
        emoji: "⛰️",
        type: "Nature",
        title: "Mount Qingcheng",
        desc: "The birthplace of Taoism — a UNESCO World Heritage mountain with 2,000-year-old temples hidden in misty bamboo forests. Cable car available.",
        meiNote: "About 1 hour from Chengdu. Can be combined with Dujiangyan for a full day trip — we arrange both.",
        image: `${CD}/qingcheng1.jpg`,
        tag: "Day trip",
        tagColor: "#059669",
      },
      {
        id: "cd-pick-3",
        emoji: "🌶️",
        type: "Food",
        title: "Sichuan Cooking Class",
        desc: "A hands-on class where you learn to cook mapo tofu, kung pao chicken, and dan dan noodles. Includes market visit to buy ingredients.",
        meiNote: "We arrange this with a local cooking school. Half day, includes lunch. You eat everything you cook.",
        image: `${CD}/cooking_class.jpg`,
        tag: "We can arrange",
        tagColor: "#D0021B",
      },
      {
        id: "cd-pick-4",
        emoji: "🎭",
        type: "Culture",
        title: "Sichuan Opera Face-Changing",
        desc: "A full Sichuan opera show with the famous 'face-changing' (bian lian) — performers swap painted masks in a fraction of a second. Nobody knows how.",
        meiNote: "Several theatres do this. We book the best one with good seats — tickets are Chinese-platform only.",
        image: `${CD}/face_changing.jpg`,
        tag: "We can book",
        tagColor: "#D0021B",
      },
      {
        id: "cd-pick-5",
        emoji: "💧",
        type: "UNESCO",
        title: "Dujiangyan Irrigation System",
        desc: "A 2,280-year-old irrigation system that still works — no dam, no modern technology, just ancient engineering genius. UNESCO World Heritage.",
        meiNote: "About 1 hour from Chengdu. Can combine with Mount Qingcheng for a full day.",
        image: `${CD}/dujiangyan.jpg`,
        tag: "Day trip",
        tagColor: "#7C3AED",
      },
    ],
  };
}
