// Pipeline A · Stages 3+4 ingest — read enriched cache files into SQLite.
//
// The enrichment + ai_summary were generated by parallel Claude Code agents
// and written to /data/cache/place/<id>.json. This script is pure file I/O —
// no API calls, no AI. It reads each cache file and UPDATEs the matching
// `places` row.
import "../lib/env";
import fs from "node:fs";
import path from "node:path";
import { getDb, closeDb } from "../../src/lib/db/client";
import { migrate } from "../../src/lib/db/schema";

interface CacheFile {
  id: string;
  name_cn: string;
  category: string;
  enrichment: {
    kid_suitability: string[] | null;
    mobility: string | null;
    indoor_outdoor: string | null;
    weather_resilience: string | null;
    energy_intensity: string | null;
    foreigner_friction_score: number | null;
    best_time_of_day: string[] | null;
    dietary_flags: Record<string, unknown> | null;
    narrative_role: string | null;
    interest_tags: string[] | null;
  } | null;
  ai_summary: string | null;
  quality_flags?: string[];
  generated_at?: string;
}

/**
 * Some agents stored dietary_flags using v2 schema field names with boolean
 * values (`halal: false`, `vegetarian: true`) instead of the spec's normalized
 * names (`halal_ok`, `veg_ok`). Coerce to the canonical shape on the way in.
 */
function normalizeDietary(d: Record<string, unknown> | null): Record<string, unknown> | null {
  if (!d) return null;
  const out: Record<string, unknown> = {};
  out.halal_ok =
    "halal_ok" in d ? d.halal_ok :
    "halal" in d ? coerceBool(d.halal) :
    null;
  out.veg_ok =
    "veg_ok" in d ? d.veg_ok :
    "vegetarian" in d ? coerceBool(d.vegetarian) :
    null;
  out.vegan_ok =
    "vegan_ok" in d ? d.vegan_ok :
    "vegan" in d ? coerceBool(d.vegan) :
    null;
  out.pork_free = "pork_free" in d ? coerceBool(d.pork_free) : null;
  out.note = typeof d.note === "string" ? d.note : null;
  return out;
}

function coerceBool(v: unknown): boolean | null {
  if (typeof v === "boolean") return v;
  if (typeof v === "number") return v !== 0;
  if (typeof v === "string") {
    const s = v.trim().toLowerCase();
    if (["yes", "true", "1", "limited", "possible"].includes(s)) return true;
    if (["no", "false", "0"].includes(s)) return false;
  }
  return null;
}

const CACHE_DIR = path.join(
  process.cwd(),
  "data",
  "cache",
  "place"
);

const db = getDb();
migrate(db);

if (!fs.existsSync(CACHE_DIR)) {
  console.error(`✗ Cache dir does not exist: ${CACHE_DIR}`);
  process.exit(1);
}

const files = fs
  .readdirSync(CACHE_DIR)
  .filter((f) => f.endsWith(".json"));
console.log(`Found ${files.length} cache files in ${CACHE_DIR}`);

const update = db.prepare(`
  UPDATE places SET
    kid_suitability          = @kid_suitability,
    mobility                 = @mobility,
    indoor_outdoor           = @indoor_outdoor,
    weather_resilience       = @weather_resilience,
    energy_intensity         = @energy_intensity,
    foreigner_friction_score = @foreigner_friction_score,
    best_time_of_day         = @best_time_of_day,
    dietary_flags            = COALESCE(@dietary_flags, dietary_flags),
    narrative_role           = @narrative_role,
    interest_tags            = @interest_tags,
    ai_summary               = @ai_summary,
    quality_flags            = @quality_flags,
    updated_at               = datetime('now')
  WHERE id = @id
`);

let updated = 0;
let missing = 0;
let errors = 0;
const flagged: string[] = [];

const tx = db.transaction((entries: CacheFile[]) => {
  for (const e of entries) {
    if (!e.id) {
      errors++;
      console.error(`  ✗ no id field in cache entry`);
      continue;
    }
    try {
      const enrich = e.enrichment;
      const result = update.run({
        id: e.id,
        kid_suitability: enrich?.kid_suitability ? JSON.stringify(enrich.kid_suitability) : null,
        mobility: enrich?.mobility ?? null,
        indoor_outdoor: enrich?.indoor_outdoor ?? null,
        weather_resilience: enrich?.weather_resilience ?? null,
        energy_intensity: enrich?.energy_intensity ?? null,
        foreigner_friction_score: enrich?.foreigner_friction_score ?? null,
        best_time_of_day: enrich?.best_time_of_day ? JSON.stringify(enrich.best_time_of_day) : null,
        dietary_flags: enrich?.dietary_flags
          ? JSON.stringify(normalizeDietary(enrich.dietary_flags))
          : null,
        narrative_role: enrich?.narrative_role ?? null,
        interest_tags: enrich?.interest_tags ? JSON.stringify(enrich.interest_tags) : null,
        ai_summary: e.ai_summary ?? null,
        quality_flags: e.quality_flags ? JSON.stringify(e.quality_flags) : null,
      });
      if (result.changes === 0) {
        missing++;
        console.error(`  ✗ no matching place row for id=${e.id} (${e.name_cn})`);
      } else {
        updated++;
        if (e.quality_flags?.length) flagged.push(`${e.id} ${e.name_cn}`);
      }
    } catch (err) {
      errors++;
      console.error(`  ✗ ${e.id} ${e.name_cn}: ${(err as Error).message}`);
    }
  }
});

const entries: CacheFile[] = [];
let parseErrors = 0;
for (const f of files) {
  try {
    const raw = fs.readFileSync(path.join(CACHE_DIR, f), "utf8");
    entries.push(JSON.parse(raw) as CacheFile);
  } catch (err) {
    parseErrors++;
    console.error(`  ✗ parse failed for ${f}: ${(err as Error).message}`);
  }
}

tx(entries);

// Coverage report
const coverage = db
  .prepare(
    `SELECT
       category,
       count(*) as total,
       sum(CASE WHEN ai_summary IS NOT NULL THEN 1 ELSE 0 END) as with_summary,
       sum(CASE WHEN interest_tags IS NOT NULL THEN 1 ELSE 0 END) as with_tags,
       sum(CASE WHEN narrative_role IS NOT NULL THEN 1 ELSE 0 END) as with_role
     FROM places WHERE city = ? GROUP BY category ORDER BY category`
  )
  .all("shanghai");

console.log("\n── Merge results ──────────────────────────────");
console.log(`  cache files read:    ${files.length}`);
console.log(`  parse errors:        ${parseErrors}`);
console.log(`  rows updated:        ${updated}`);
console.log(`  rows not in DB:      ${missing}`);
console.log(`  write errors:        ${errors}`);
console.log("────────────────────────────────────────────────");
console.log("\nCoverage by category:");
for (const c of coverage as any[]) {
  console.log(
    `  ${c.category.padEnd(12)} ${c.with_summary}/${c.total} summarized, ${c.with_tags}/${c.total} tagged, ${c.with_role}/${c.total} roled`
  );
}
if (flagged.length) {
  console.log(`\nQuality-flagged places (${flagged.length}):`);
  for (const f of flagged) console.log(`  • ${f}`);
}

closeDb();
